/**
 * Interval painting for traffic signals — the pure model behind the timeline
 * lane (traffic-light timeline plan 2026-07-25, Phase 1).
 *
 * The author paints coloured spans on a time axis. That is a VIEW over the
 * existing `program` mode, not a new schema mode: `SignalPhaseInterval.states`
 * is already a per-movement colour map inside one time slice, which is exactly a
 * painted band sliced at the union of boundaries. So painting compiles bands →
 * `SignalPhaseProgram`, opening decompiles the program → bands, and neither the
 * worker, the xosc writer nor the preview engine learns anything new.
 *
 * Three properties hold this together, and the round-trip test is the gate:
 *
 * 1. **One-shot, not cyclic.** A painted timeline means "green from 4 s onward",
 *    but a program is a repeating cycle in all three runtimes. The compiler's
 *    last phase therefore holds for {@link SIGNAL_HOLD_TAIL_S} = 3600 s, which
 *    no real scenario reaches. Not `Infinity`: `0 * Infinity` is `NaN` and would
 *    poison the xosc writer's boundary unroll, and JSON round-trips it to null.
 *
 * 2. **Auto-yellow is DERIVED, never authored intent.** Compiling inserts
 *    {@link SIGNAL_AUTO_YELLOW_S} of yellow ENDING at each green→red boundary —
 *    eating the green's tail, so "red at 4" still means red at 4. Decompiling
 *    marks such a band `derived`, and compiling strips derived bands (giving the
 *    time back to the green before it) before re-deriving them. That is what
 *    makes the operation idempotent across any number of round-trips. A yellow
 *    the author hand-paints in exactly that shape simply becomes derived, which
 *    is fine: the compiled output is identical either way.
 *
 * 3. **Paint is destructive within a row.** A span replaces whatever is under
 *    it — neighbours truncate, covered bands vanish, same-colour neighbours
 *    merge. Overlap is never a stored state; it is resolved at paint time.
 *
 * Rows are DERIVED, never stored: conflict-free groups from the shared
 * `deriveConflictFreeGroups` (the same partition `detectSignalPlanWarnings`
 * checks against, so a group-tier paint cannot produce a `conflicting_green`),
 * split further by identical band signature so a hand-edited or
 * worker-round-tripped program still displays sensibly. No schema field, and no
 * way for a stored group to disagree with the plan it describes.
 */

import {
  type BehaviorSignalState,
} from "@simforge-oss/scenario/contracts";
import {
  deriveConflictFreeGroups,
  synthesizeSignalProgram,
  type JunctionMovementBinding,
  type JunctionSignalPlan,
  type SignalPhaseInterval,
  type SignalPhaseProgram,
} from "@simforge-oss/studio-shared";
import {
  nextSignalState,
  programBands,
} from "@/app/lib/scenario-editor/signals/signal-plan-model";

/** Yellow inserted at every green→red flip, ending at the boundary. */
export const SIGNAL_AUTO_YELLOW_S = 3.0;

/**
 * The final phase's duration. Long enough that no scenario reaches the wrap, so
 * a painted (one-shot) timeline never repeats; short enough to read as "one
 * hour" in the phase list and to survive a JSON round-trip.
 */
export const SIGNAL_HOLD_TAIL_S = 3600;

/** Painted edges snap here. Program boundaries have no such constraint — this
 *  is for the author's benefit (and to keep round-trips float-exact). */
export const TIMELINE_TIME_GRID_S = 0.1;

/** Below this a band is not worth keeping; paints and retimes clamp to it. */
export const TIMELINE_MIN_BAND_S = 0.2;

const EPSILON = 1e-6;

export type TimelineBand = {
  state: BehaviorSignalState;
  start_s: number;
  end_s: number;
  /** Regenerated by the compiler: hatched, and not draggable. */
  derived?: boolean;
};

/** One paintable lane row: a set of movements that move as one. */
export type TimelineRow = {
  /** Stable across re-derivations: the sorted movement ids. */
  id: string;
  label: string;
  movement_ids: string[];
  bands: TimelineBand[];
};

/** How far down the junction → group → movement disclosure the lane is open. */
export type TimelineTier = "junction" | "group" | "movement";

export function snapTimelineSeconds(seconds: number): number {
  const snapped = Math.round(seconds / TIMELINE_TIME_GRID_S) * TIMELINE_TIME_GRID_S;
  return Math.round(snapped * 1e6) / 1e6;
}

function roundSeconds(seconds: number): number {
  return Math.round(seconds * 1e6) / 1e6;
}

/**
 * The colour a conflicting group takes when this one is painted.
 *
 * Yellow maps to red rather than to green: yellow is a clearing interval, and
 * the cross traffic is not released until it is over.
 */
export function oppositeSignalState(state: BehaviorSignalState): BehaviorSignalState {
  return state === "red" ? "green" : "red";
}

// ---------------------------------------------------------------------------
// Rows
// ---------------------------------------------------------------------------

/**
 * The conflict-free groups the lane paints, with shared heads fused.
 *
 * Fusing matters here and nowhere else: two movements on one physical head
 * cannot show different colours, so a surface that paints whole groups must not
 * offer to try.
 */
export function timelineGroups(
  movements: readonly JunctionMovementBinding[],
): string[][] {
  return deriveConflictFreeGroups(movements, { unionSharedHeads: true });
}

export function timelineRowId(movementIds: readonly string[]): string {
  return [...movementIds].sort().join("|");
}

/** A row header that names the movements without becoming a paragraph. */
export function timelineRowLabel(
  movements: readonly JunctionMovementBinding[],
  movementIds: readonly string[],
): string {
  const byId = new Map(movements.map((movement) => [movement.movement_id, movement]));
  const labels = movementIds.map((id) => byId.get(id)?.label ?? id);
  if (labels.length === 0) return "No movements";
  if (labels.length === 1) return labels[0]!;
  return `${labels[0]} +${labels.length - 1}`;
}

function bandSignature(bands: readonly TimelineBand[]): string {
  return bands
    .map((band) => `${band.state}@${roundSeconds(band.start_s)}-${roundSeconds(band.end_s)}`)
    .join(",");
}

/**
 * Every movement's colour over time, from the plan's program.
 *
 * `programBands` is the existing, exact, already-tested decompiler — it applies
 * the same hold-your-colour rule `movementStateAt` does, so what comes back is
 * the sequence a viewer would actually see rather than one band per interval.
 */
function bandsByMovement(
  plan: JunctionSignalPlan,
  durationSeconds: number,
  autoYellow: boolean,
): Map<string, TimelineBand[]> {
  const byMovement = new Map<string, TimelineBand[]>();
  const program = plan.program;
  if (program && program.cycle.length > 0 && durationSeconds > 0) {
    for (const band of programBands(program, plan.movements, durationSeconds)) {
      const bands = byMovement.get(band.movement_id) ?? [];
      // Rounded because `programBands` accumulates a cursor across the cycle, so
      // a boundary the author put at 29.6 comes back as 29.599999999999998 —
      // enough to make an otherwise exact round trip fail on its last band.
      bands.push({
        state: band.state,
        start_s: roundSeconds(band.start_s),
        end_s: roundSeconds(band.end_s),
      });
      byMovement.set(band.movement_id, bands);
    }
  }
  for (const movement of plan.movements) {
    // A movement the cycle never names has no authored colour. Forced green is
    // the scenario-wide default (plan §11), so that is what it is showing, and
    // saying so here makes the next compile state it explicitly.
    if (!byMovement.has(movement.movement_id)) {
      byMovement.set(movement.movement_id, [
        { state: "green", start_s: 0, end_s: durationSeconds },
      ]);
    }
  }
  for (const bands of byMovement.values()) {
    bands.sort((left, right) => left.start_s - right.start_s);
    if (autoYellow) markDerivedYellows(bands);
  }
  return byMovement;
}

/**
 * Mark the yellows the compiler would have produced anyway.
 *
 * Exactly {@link SIGNAL_AUTO_YELLOW_S} long, immediately after a green and
 * immediately before a red. Nothing else qualifies, so a 2 s yellow an author
 * drew by hand stays theirs.
 */
function markDerivedYellows(bands: TimelineBand[]): void {
  for (const [index, band] of bands.entries()) {
    const previous = bands[index - 1];
    const next = bands[index + 1];
    if (
      band.state === "yellow" &&
      previous?.state === "green" &&
      next?.state === "red" &&
      Math.abs(band.end_s - band.start_s - SIGNAL_AUTO_YELLOW_S) < EPSILON
    ) {
      band.derived = true;
    }
  }
}

/**
 * The lane's rows for one plan.
 *
 * Conflict-free groups first (so every row is safely paintable), then split by
 * band signature (so a hand-edited program that gave two members of one group
 * different colours still shows both truthfully).
 */
export function decompileProgramToRows(
  plan: JunctionSignalPlan,
  durationSeconds: number,
  options: { autoYellow?: boolean; tier?: TimelineTier } = {},
): TimelineRow[] {
  if (durationSeconds <= 0) return [];
  const autoYellow = options.autoYellow ?? true;
  const byMovement = bandsByMovement(plan, durationSeconds, autoYellow);
  const known = new Set(plan.movements.map((movement) => movement.movement_id));
  const orphans = [...byMovement.keys()].filter((id) => !known.has(id)).sort();

  const groups =
    options.tier === "movement"
      ? [...known].sort().map((id) => [id])
      : timelineGroups(plan.movements);

  const rows: TimelineRow[] = [];
  for (const group of [...groups, ...orphans.map((id) => [id])]) {
    const bySignature = new Map<string, string[]>();
    for (const movementId of group) {
      const signature = bandSignature(byMovement.get(movementId) ?? []);
      bySignature.set(signature, [...(bySignature.get(signature) ?? []), movementId]);
    }
    for (const movementIds of bySignature.values()) {
      const sorted = [...movementIds].sort();
      rows.push({
        id: timelineRowId(sorted),
        label: timelineRowLabel(plan.movements, sorted),
        movement_ids: sorted,
        bands: (byMovement.get(sorted[0]!) ?? []).map((band) => ({ ...band })),
      });
    }
  }
  return rows;
}

// ---------------------------------------------------------------------------
// Compiling
// ---------------------------------------------------------------------------

/**
 * Give a derived band's time back to the band before it.
 *
 * The compiler re-derives auto-yellow from scratch, so it must first see the
 * bands as the author drew them — a green that runs all the way to the red.
 */
export function stripDerivedBands(bands: readonly TimelineBand[]): TimelineBand[] {
  const out: TimelineBand[] = [];
  for (const band of bands) {
    if (!band.derived) {
      out.push({ state: band.state, start_s: band.start_s, end_s: band.end_s });
      continue;
    }
    const previous = out[out.length - 1];
    if (previous) previous.end_s = band.end_s;
    else out.push({ state: band.state, start_s: band.start_s, end_s: band.end_s });
  }
  return out;
}

/** Insert the yellow every green→red flip needs, ending at the boundary. */
export function withAutoYellow(bands: readonly TimelineBand[]): TimelineBand[] {
  const out: TimelineBand[] = [];
  for (const [index, band] of bands.entries()) {
    const next = bands[index + 1];
    const duration = band.end_s - band.start_s;
    if (
      band.state !== "green" ||
      next?.state !== "red" ||
      // A green shorter than the yellow would be replaced by it rather than
      // trimmed. The author asked for that green; leave the flip raw.
      duration <= SIGNAL_AUTO_YELLOW_S + EPSILON
    ) {
      out.push({ ...band });
      continue;
    }
    const boundary = band.end_s;
    out.push({ ...band, end_s: roundSeconds(boundary - SIGNAL_AUTO_YELLOW_S) });
    out.push({
      state: "yellow",
      start_s: roundSeconds(boundary - SIGNAL_AUTO_YELLOW_S),
      end_s: boundary,
      derived: true,
    });
  }
  return out;
}

function stateAt(bands: readonly TimelineBand[], t: number): BehaviorSignalState | null {
  let held: BehaviorSignalState | null = null;
  for (const band of bands) {
    if (band.start_s <= t && band.end_s > t) return band.state;
    if (band.end_s <= t) held = band.state;
  }
  return held;
}

/**
 * Bands → `SignalPhaseProgram`.
 *
 * Slices at the union of every row's boundaries and emits a FULL state map per
 * slice — every movement, every time. That is deliberate on three counts: it
 * drives the `incomplete_phase` warning count to zero, it guarantees the
 * compiler can never name a movement outside the table (one parse throw drops
 * the signal layer for the WHOLE scenario, not just this plan), and it makes the
 * round-trip exact, because nothing depends on the hold-your-colour walk.
 */
export function compileRowsToProgram(
  rows: readonly TimelineRow[],
  movements: readonly JunctionMovementBinding[],
  durationSeconds: number,
  options: { autoYellow?: boolean } = {},
): SignalPhaseProgram | null {
  if (durationSeconds <= 0) return null;
  const autoYellow = options.autoYellow ?? true;

  const byMovement = new Map<string, TimelineBand[]>();
  for (const row of rows) {
    const normalized = normalizeBands(row.bands, durationSeconds);
    const stripped = stripDerivedBands(normalized);
    const compiled = autoYellow ? withAutoYellow(stripped) : stripped;
    for (const movementId of row.movement_ids) {
      byMovement.set(movementId, compiled.map((band) => ({ ...band })));
    }
  }
  for (const movement of movements) {
    if (!byMovement.has(movement.movement_id)) {
      byMovement.set(movement.movement_id, [
        { state: "green", start_s: 0, end_s: durationSeconds },
      ]);
    }
  }
  if (byMovement.size === 0) return null;

  const edges = new Set<number>([0, durationSeconds]);
  for (const bands of byMovement.values()) {
    for (const band of bands) {
      if (band.start_s > 0 && band.start_s < durationSeconds) edges.add(roundSeconds(band.start_s));
      if (band.end_s > 0 && band.end_s < durationSeconds) edges.add(roundSeconds(band.end_s));
    }
  }
  const boundaries = [...edges].sort((left, right) => left - right);

  const cycle: SignalPhaseInterval[] = [];
  for (const [index, start] of boundaries.slice(0, -1).entries()) {
    const end = boundaries[index + 1]!;
    const duration = roundSeconds(end - start);
    if (duration <= EPSILON) continue;
    const mid = (start + end) / 2;
    const states: Record<string, BehaviorSignalState> = {};
    for (const [movementId, bands] of byMovement) {
      states[movementId] = stateAt(bands, mid) ?? "green";
    }
    const previous = cycle[cycle.length - 1];
    if (previous && sameStates(previous.states, states)) {
      previous.duration_s = roundSeconds(previous.duration_s + duration);
      continue;
    }
    cycle.push({ duration_s: duration, states });
  }
  if (cycle.length === 0) return null;

  // The tail holds instead of wrapping: a painted timeline is one-shot.
  cycle[cycle.length - 1] = {
    ...cycle[cycle.length - 1]!,
    duration_s: SIGNAL_HOLD_TAIL_S,
    label: "Holds",
  };
  return { cycle, offset_s: 0 };
}

function sameStates(
  left: Record<string, BehaviorSignalState>,
  right: Record<string, BehaviorSignalState>,
): boolean {
  const keys = Object.keys(left);
  if (keys.length !== Object.keys(right).length) return false;
  return keys.every((key) => left[key] === right[key]);
}

/**
 * Clamp to the timeline, drop slivers, close gaps.
 *
 * Painting cannot produce a gap, but a plan that arrived from somewhere else
 * can; a gap would compile to a slice whose colour came from the hold-your-
 * colour walk instead of from the lane the author is looking at.
 */
export function normalizeBands(
  bands: readonly TimelineBand[],
  durationSeconds: number,
): TimelineBand[] {
  const clipped = bands
    .map((band) => ({
      ...band,
      start_s: Math.max(0, roundSeconds(band.start_s)),
      end_s: Math.min(durationSeconds, roundSeconds(band.end_s)),
    }))
    .filter((band) => band.end_s - band.start_s > EPSILON)
    .sort((left, right) => left.start_s - right.start_s);
  if (clipped.length === 0) return [];

  const out: TimelineBand[] = [];
  for (const band of clipped) {
    const previous = out[out.length - 1];
    if (!previous) {
      // Anything before the first band holds its colour — the same rule the
      // executor applies when a cycle starts mid-phase.
      out.push({ ...band, start_s: 0 });
      continue;
    }
    if (band.start_s < previous.end_s) band.start_s = previous.end_s;
    if (band.end_s - band.start_s <= EPSILON) continue;
    if (band.start_s > previous.end_s) previous.end_s = band.start_s;
    if (previous.state === band.state && previous.derived === band.derived) {
      previous.end_s = band.end_s;
      continue;
    }
    out.push({ ...band });
  }
  out[out.length - 1]!.end_s = durationSeconds;
  return out;
}

// ---------------------------------------------------------------------------
// Seeding
// ---------------------------------------------------------------------------

/**
 * The seed for a junction nobody has authored: green, everywhere, all scenario.
 *
 * This is not a design flourish — it is what the runtime already does. Michael's
 * 2026-07-26 decision (plan §11) forces every dynamic light green on any
 * junction with no authored plan, and the browser engine reads an unauthored
 * junction as "proceed", so an all-green full-duration program is the one seed
 * that changes NOTHING when the author opens the timeline. The synthesized
 * alternating cycle is one click away for authors who want a real intersection.
 */
export function seedForcedGreenProgram(
  movements: readonly JunctionMovementBinding[],
): SignalPhaseProgram | null {
  if (movements.length === 0) return null;
  return {
    cycle: [
      {
        duration_s: SIGNAL_HOLD_TAIL_S,
        label: "Forced green",
        states: Object.fromEntries(
          movements.map((movement) => [movement.movement_id, "green" as const]),
        ),
      },
    ],
    offset_s: 0,
  };
}

/** The alternating cycle behind "Seed cycle" — the shared synthesizer. */
export function seedCycleProgram(
  movements: readonly JunctionMovementBinding[],
): SignalPhaseProgram | null {
  return synthesizeSignalProgram(movements);
}

/**
 * Switch a plan into the timeline view.
 *
 * Writes `program` mode, because the timeline IS the program — no fourth
 * executor branch, no schema bump. Anything already authored survives: an author
 * who painted, tried Static, and came back finds their timeline intact.
 */
export function withTimelineMode(plan: JunctionSignalPlan): JunctionSignalPlan {
  const next: JunctionSignalPlan = { ...plan, mode: "program" };
  if ((next.program?.cycle.length ?? 0) === 0) {
    const seeded = seedForcedGreenProgram(plan.movements);
    if (seeded) next.program = seeded;
  }
  return next;
}

/** True when the plan is still the untouched forced-green seed. */
export function isForcedGreenSeed(plan: JunctionSignalPlan): boolean {
  const cycle = plan.program?.cycle ?? [];
  if (cycle.length !== 1) return false;
  const states = Object.values(cycle[0]!.states);
  return states.length > 0 && states.every((state) => state === "green");
}

// ---------------------------------------------------------------------------
// Editing one row
// ---------------------------------------------------------------------------

/**
 * Paint a span, destructively.
 *
 * Neighbours truncate at the span's edges, fully covered bands disappear, and
 * same-colour neighbours merge. This is the rule that makes drag-paint feel like
 * a paint bucket rather than an insert, and it is why overlap is never stored.
 */
export function paintBands(
  bands: readonly TimelineBand[],
  span: { start_s: number; end_s: number },
  state: BehaviorSignalState,
  durationSeconds: number,
): TimelineBand[] {
  const start = Math.max(0, snapTimelineSeconds(Math.min(span.start_s, span.end_s)));
  const end = Math.min(durationSeconds, snapTimelineSeconds(Math.max(span.start_s, span.end_s)));
  if (end - start < EPSILON) return [...bands];

  const out: TimelineBand[] = [];
  for (const band of bands) {
    // A derived yellow under the brush stops being derived the moment its
    // shape changes; the compiler will re-derive whatever the result needs.
    if (band.end_s <= start || band.start_s >= end) {
      out.push({ ...band });
      continue;
    }
    if (band.start_s < start) out.push({ ...band, end_s: start });
    if (band.end_s > end) out.push({ ...band, start_s: end });
  }
  out.push({ state, start_s: start, end_s: end });
  return normalizeBands(out, durationSeconds);
}

/** Interior boundaries — the draggable edges between bands. */
export function bandBoundaries(bands: readonly TimelineBand[]): number[] {
  return bands.slice(0, -1).map((band) => band.end_s);
}

/**
 * Move the boundary between bands `index` and `index + 1`.
 *
 * Both neighbours resize; neither may collapse past
 * {@link TIMELINE_MIN_BAND_S}. A derived yellow is not draggable — the compiler
 * owns its edges — so a retime that would move one is refused rather than
 * silently ignored downstream.
 */
export function retimeBoundary(
  bands: readonly TimelineBand[],
  index: number,
  timeSeconds: number,
  durationSeconds: number,
): TimelineBand[] {
  const left = bands[index];
  const right = bands[index + 1];
  if (!left || !right) return [...bands];
  if (left.derived || right.derived) return [...bands];
  const lowest = left.start_s + TIMELINE_MIN_BAND_S;
  const highest = right.end_s - TIMELINE_MIN_BAND_S;
  if (highest < lowest) return [...bands];
  const at = Math.min(highest, Math.max(lowest, snapTimelineSeconds(timeSeconds)));
  return normalizeBands(
    bands.map((band, position) => {
      if (position === index) return { ...band, end_s: at };
      if (position === index + 1) return { ...band, start_s: at };
      return { ...band };
    }),
    durationSeconds,
  );
}

/** Delete a boundary: the two bands merge, taking the LEFT band's colour. */
export function deleteBoundary(
  bands: readonly TimelineBand[],
  index: number,
  durationSeconds: number,
): TimelineBand[] {
  const left = bands[index];
  const right = bands[index + 1];
  if (!left || !right) return [...bands];
  const merged = bands.map((band, position) =>
    position === index + 1
      ? { state: left.state, start_s: band.start_s, end_s: band.end_s }
      : { ...band },
  );
  return normalizeBands(merged, durationSeconds);
}

/** Advance one band's colour: red → green → yellow, the panel's order. */
export function cycleBand(
  bands: readonly TimelineBand[],
  index: number,
  durationSeconds: number,
): TimelineBand[] {
  const band = bands[index];
  if (!band) return [...bands];
  return normalizeBands(
    bands.map((entry, position) =>
      position === index
        ? { state: nextSignalState(entry.state), start_s: entry.start_s, end_s: entry.end_s }
        : { ...entry },
    ),
    durationSeconds,
  );
}

// ---------------------------------------------------------------------------
// Editing across rows
// ---------------------------------------------------------------------------

function rowsConflict(
  movements: readonly JunctionMovementBinding[],
  left: TimelineRow,
  right: TimelineRow,
): boolean {
  const conflicts = new Map(
    movements.map((movement) => [movement.movement_id, new Set(movement.conflicts_with)]),
  );
  return left.movement_ids.some((id) =>
    right.movement_ids.some((other) => conflicts.get(id)?.has(other) ?? false),
  );
}

/**
 * Paint one row and settle the junction around it.
 *
 * Every conflicting row takes the opposite colour over the same span. This is
 * the whole "I should not have to micromanage every single light" requirement:
 * one gesture leaves the junction in a state that runs. It also makes
 * `conflicting_green` unreachable from this tier, which turns that warning into
 * a precise signal that the author descended to the movement tier on purpose.
 */
export function paintRows(
  rows: readonly TimelineRow[],
  movements: readonly JunctionMovementBinding[],
  targetRowId: string,
  span: { start_s: number; end_s: number },
  state: BehaviorSignalState,
  durationSeconds: number,
): TimelineRow[] {
  const target = rows.find((row) => row.id === targetRowId);
  if (!target) return [...rows];
  const opposite = oppositeSignalState(state);
  return rows.map((row) => {
    if (row.id === targetRowId) {
      return { ...row, bands: paintBands(row.bands, span, state, durationSeconds) };
    }
    if (!rowsConflict(movements, target, row)) return row;
    return { ...row, bands: paintBands(row.bands, span, opposite, durationSeconds) };
  });
}

/**
 * Where two conflicting rows are green at the same time.
 *
 * `detectSignalPlanWarnings` already reports this per phase; the lane wants it
 * per SPAN, so the hatch lands on the seconds that are wrong instead of on a
 * list item that names a phase index the author never sees. Unreachable from the
 * junction and group tiers by construction, so anything drawn here is a precise
 * report that the author descended to the movement tier.
 */
export function conflictingGreenSpans(
  rows: readonly TimelineRow[],
  movements: readonly JunctionMovementBinding[],
): Array<{ rowId: string; start_s: number; end_s: number }> {
  const spans: Array<{ rowId: string; start_s: number; end_s: number }> = [];
  for (const row of rows) {
    for (const other of rows) {
      if (row.id === other.id || !rowsConflict(movements, row, other)) continue;
      for (const band of row.bands) {
        if (band.state !== "green") continue;
        for (const rival of other.bands) {
          if (rival.state !== "green") continue;
          const start = Math.max(band.start_s, rival.start_s);
          const end = Math.min(band.end_s, rival.end_s);
          if (end - start > EPSILON) spans.push({ rowId: row.id, start_s: start, end_s: end });
        }
      }
    }
  }
  return spans;
}

/**
 * The row an author means when they paint the collapsed junction row.
 *
 * Precedence, most specific first:
 *
 * 1. **The light they clicked.** Pointing at a physical head is the most
 *    explicit statement of intent available — the author walked up to one light
 *    and said "this one" — so it outranks everything inferred.
 * 2. **The selected actor's approach.** Select the subject, paint the junction row,
 *    and you have painted the subject's light.
 * 3. **The first group**, which is the one the synthesizer greens first.
 *
 * A reference naming several movements (one head commonly drives both the
 * through and the right) matches the row holding ANY of them: `timelineGroups`
 * fuses movements that share a head, so they are all in one row anyway.
 */
export function primaryRowId(
  rows: readonly TimelineRow[],
  reference: string | null | { referenceMovementIds?: readonly string[]; subjectMovementId?: string | null },
): string | null {
  if (rows.length === 0) return null;
  const referenceIds =
    typeof reference === "string" || reference == null
      ? []
      : (reference.referenceMovementIds ?? []);
  const subjectMovementId =
    typeof reference === "string" ? reference : (reference?.subjectMovementId ?? null);

  if (referenceIds.length > 0) {
    const owning = rows.find((row) =>
      row.movement_ids.some((id) => referenceIds.includes(id)),
    );
    if (owning) return owning.id;
  }
  if (subjectMovementId) {
    const owning = rows.find((row) => row.movement_ids.includes(subjectMovementId));
    if (owning) return owning.id;
  }
  return rows[0]!.id;
}

/**
 * Move every row's boundary that sits at `fromSeconds` (Alt+drag).
 *
 * Junctions are coordinated: the moment one approach turns green the other
 * turns red, and retiming one edge alone would break that. Rows with no
 * boundary there are untouched.
 */
export function retimeRowsAt(
  rows: readonly TimelineRow[],
  fromSeconds: number,
  toSeconds: number,
  durationSeconds: number,
): TimelineRow[] {
  return rows.map((row) => {
    const index = row.bands.findIndex(
      (band, position) =>
        position < row.bands.length - 1 &&
        Math.abs(band.end_s - fromSeconds) < TIMELINE_TIME_GRID_S / 2 + EPSILON,
    );
    if (index === -1) return row;
    return { ...row, bands: retimeBoundary(row.bands, index, toSeconds, durationSeconds) };
  });
}

// ---------------------------------------------------------------------------
// The subject marker
// ---------------------------------------------------------------------------

function normalizeDegrees(degrees: number): number {
  return ((((degrees + 180) % 360) + 360) % 360) - 180;
}

/**
 * Which movement an actor standing at `from` will meet at this junction.
 *
 * Matches the bearing the actor must travel to reach the junction against each
 * movement's approach heading, both in the CARLA basis the movement table
 * stores. Deliberately crude — it reads a straight line, not a route — so it is
 * gated hard on distance and angle and answers null rather than guess. The
 * precise answer lives in `PreviewRouteLandmark`, which is server-side only
 * today (plan §4.3, Phase 4).
 */
export function nearestApproachMovementId(
  movements: readonly JunctionMovementBinding[],
  from: { x: number; y: number } | null,
  junctionCenter: { x: number; y: number } | null,
  options: { maxDistanceM?: number; maxHeadingDeltaDeg?: number } = {},
): string | null {
  if (!from || !junctionCenter) return null;
  const maxDistance = options.maxDistanceM ?? 200;
  const maxDelta = options.maxHeadingDeltaDeg ?? 60;
  const dx = junctionCenter.x - from.x;
  const dy = junctionCenter.y - from.y;
  const distance = Math.hypot(dx, dy);
  if (distance > maxDistance || distance < EPSILON) return null;

  const bearing = (Math.atan2(dy, dx) * 180) / Math.PI;
  let best: { movementId: string; delta: number } | null = null;
  for (const movement of movements) {
    if (movement.approach_heading_deg == null) continue;
    const delta = Math.abs(normalizeDegrees(movement.approach_heading_deg - bearing));
    if (delta > maxDelta) continue;
    if (!best || delta < best.delta) best = { movementId: movement.movement_id, delta };
  }
  return best?.movementId ?? null;
}
