//! `simforge package inspect|verify|import` over the scenario-package
//! fixture corpus (oss/fixtures/scenario-package, generated by the
//! simforge-package crate): every valid package verifies to its id, every
//! hostile one is refused with its code and rule, through the CLI contract.

use std::path::{Path, PathBuf};
use std::process::Command;

use serde_json::Value;

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../fixtures/scenario-package")
}

fn simforge(home: &Path) -> Command {
    let mut cmd = Command::new(env!("CARGO_BIN_EXE_simforge"));
    cmd.env_remove("SIMFORGE_MAPS_CACHE_ROOT")
        .env_remove("SIMFORGE_ACTOR_ASSETS_ROOT")
        .env_remove("XDG_DATA_HOME")
        .env("HOME", home);
    cmd
}

fn run(cmd: &mut Command) -> (i32, Value, Value) {
    let out = cmd.output().unwrap();
    let parse = |bytes: &[u8]| -> Value {
        let text = String::from_utf8_lossy(bytes);
        match text.lines().last() {
            Some(line) if !line.is_empty() => {
                serde_json::from_str(line).unwrap_or_else(|e| panic!("not JSON ({e}): {text}"))
            }
            _ => Value::Null,
        }
    };
    (
        out.status.code().unwrap(),
        parse(&out.stdout),
        parse(&out.stderr),
    )
}

fn expectations() -> Vec<Value> {
    let doc: Value =
        serde_json::from_slice(&std::fs::read(fixtures().join("expectations.json")).unwrap())
            .unwrap();
    doc["fixtures"].as_array().unwrap().clone()
}

#[test]
fn every_fixture_verifies_or_is_refused_with_its_code_and_rule() {
    let home = tempfile::tempdir().unwrap();
    let all = expectations();
    assert!(all.len() > 20, "the fixture corpus shrank?");
    for fixture in &all {
        let file = fixtures().join(fixture["file"].as_str().unwrap());
        let (code, doc, err) = run(simforge(home.path()).args(["package", "verify"]).arg(&file));
        if fixture["valid"] == true {
            assert_eq!(code, 0, "{}: {err}", fixture["file"]);
            assert_eq!(
                doc["packageId"], fixture["packageId"],
                "{}",
                fixture["file"]
            );
            assert_eq!(doc["form"], fixture["form"]);
            assert_eq!(doc["verified"], true);
        } else {
            let expected_exit = if fixture["code"] == "package_io_error" {
                1
            } else {
                2
            };
            assert_eq!(code, expected_exit, "{}: {doc}", fixture["file"]);
            assert_eq!(
                doc,
                Value::Null,
                "{}: a refusal writes nothing on stdout",
                fixture["file"]
            );
            assert_eq!(err["code"], fixture["code"], "{}: {err}", fixture["file"]);
            assert_eq!(
                err["detail"]["rule"], fixture["rule"],
                "{}: {err}",
                fixture["file"]
            );
        }
    }
}

#[test]
fn inspect_reads_the_manifest_without_verifying_members() {
    let home = tempfile::tempdir().unwrap();
    let (code, doc, err) = run(simforge(home.path())
        .args(["package", "inspect"])
        .arg(fixtures().join("valid/thin.scenario.zip")));
    assert_eq!(code, 0, "{err}");
    assert_eq!(doc["verified"], false);
    assert_eq!(
        doc["packageId"],
        "df647f6e1f59caaf83c4b7ce8fd9076a9ca6e3eb7af228e080f134f6a6a6f1c0"
    );
    assert!(doc["members"].as_array().unwrap().len() >= 6);
    assert!(doc["producer"]["minCli"].is_string());
    assert!(doc["map"]["xodrSha256"].is_string());

    // A member-digest refusal is only found by verify, not inspect.
    let tampered = fixtures().join("invalid/member-digest.scenario.zip");
    let (code, _, _) = run(simforge(home.path())
        .args(["package", "inspect"])
        .arg(&tampered));
    assert_eq!(code, 0);
    let (code, _, err) = run(simforge(home.path())
        .args(["package", "verify"])
        .arg(&tampered));
    assert_eq!(code, 2);
    assert_eq!(err["code"], "package_digest_mismatch");

    // A missing file is "could not run".
    let (code, _, err) = run(simforge(home.path())
        .args(["package", "verify"])
        .arg(home.path().join("nope.scenario.zip")));
    assert_eq!((code, err["code"].as_str()), (1, Some("missing_file")));
}

#[test]
fn import_unpacks_a_workspace_and_reports_what_is_missing_locally() {
    let home = tempfile::tempdir().unwrap();
    let ws = home.path().join("ws");
    let (code, doc, err) = run(simforge(home.path())
        .args(["package", "import"])
        .arg(fixtures().join("valid/full.scenario.zip"))
        .arg("--into")
        .arg(&ws));
    assert_eq!(code, 0, "{err}");
    assert_eq!(doc["workspace"], ws.to_str().unwrap());
    for member in [
        "manifest.json",
        "document.json",
        "simulation/trace.json.gz",
        "map/closure.json",
        "actors/closure.json",
    ] {
        assert!(ws.join(member).is_file(), "{member}");
    }
    // The full form carries its blobs.
    assert!(ws.join("blobs/sha256").is_dir());
    // Nothing is installed in this empty home: both are reported, never fetched.
    assert_eq!(doc["local"]["map"]["native"], Value::Null);
    assert_eq!(doc["local"]["actorClosure"]["installed"], false);
    assert_eq!(doc["next"].as_array().unwrap().len(), 2);

    // The workspace is readable by the workspace commands.
    let (code, doc, err) = run(simforge(home.path())
        .args(["timeline", "build", "--height", "flat"])
        .arg(&ws));
    assert_eq!(code, 0, "{err}");
    assert_eq!(doc["traceSha256"].as_str().map(str::len), Some(64));

    // A second import into the same directory is refused.
    let (code, _, err) = run(simforge(home.path())
        .args(["package", "import"])
        .arg(fixtures().join("valid/full.scenario.zip"))
        .arg("--into")
        .arg(&ws));
    assert_eq!(
        (code, err["code"].as_str()),
        (1, Some("workspace_not_empty"))
    );

    // A refused package leaves nothing behind.
    let bad = home.path().join("bad");
    let (code, _, _) = run(simforge(home.path())
        .args(["package", "import"])
        .arg(fixtures().join("invalid/member-digest.scenario.zip"))
        .arg("--into")
        .arg(&bad));
    assert_eq!(code, 2);
    assert!(!bad.join("manifest.json").exists());
}

#[test]
fn the_release_smoke_package_verifies_and_imports() {
    let home = tempfile::tempdir().unwrap();
    let smoke = fixtures().join("smoke/richmond-public.scenario.zip");
    let meta: Value =
        serde_json::from_slice(&std::fs::read(fixtures().join("smoke/smoke.json")).unwrap())
            .unwrap();
    let (code, doc, err) = run(simforge(home.path())
        .args(["package", "verify"])
        .arg(&smoke));
    assert_eq!(code, 0, "{err}");
    assert_eq!(doc["packageId"], meta["packageId"]);
    let ws = home.path().join("smoke");
    let (code, doc, err) = run(simforge(home.path())
        .args(["package", "import"])
        .arg(&smoke)
        .arg("--into")
        .arg(&ws));
    assert_eq!(code, 0, "{err}");
    assert_eq!(
        doc["local"]["actorClosure"]["digest"],
        meta["actors"]["closureDigest"]
    );
}
