import * as stylex from "@stylexjs/stylex";
import { colors, text, space, motion } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

export const styles = stylex.create({
  candidateCard: {
    width: "100%",
    borderWidth: "1px",
    borderStyle: "solid",
    paddingInline: "0.625rem",
    paddingBlock: space.s2,
    textAlign: "left",
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  candidateCardSelected: {
    borderColor: "rgba(251, 146, 60, 0.7)",
    backgroundColor: "rgba(249, 115, 22, 0.1)",
  },
  candidateCardIdle: {
    borderColor: colors.border,
    backgroundColor: { default: "hsl(var(--muted) / 0.2)", ":hover": "hsl(var(--muted) / 0.4)" },
  },
  candidateHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: space.s2,
  },
  candidateLabel: {
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 500,
    color: colors.text,
  },
  confidenceBadge: {
    flexShrink: 0,
    paddingInline: space.s1,
    paddingBlock: space.s0_5,
    fontSize: "10px",
    fontWeight: 500,
  },
  confidenceHigh: {
    backgroundColor: "rgba(2, 44, 34, 0.4)",
    color: "#34d399",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(4, 120, 87, 0.4)",
  },
  confidenceMedium: {
    backgroundColor: "rgba(23, 37, 84, 0.4)",
    color: "#60a5fa",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(29, 78, 216, 0.4)",
  },
  confidenceLow: {
    backgroundColor: colors.muted,
    color: colors.mutedForeground,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
  },
  candidateExplanation: {
    marginTop: space.s1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "10px",
    color: "hsl(var(--muted-foreground) / 0.7)",
  },
  candidateTagsRow: {
    marginTop: space.s1_5,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: space.s1,
  },
  familyChip: {
    backgroundColor: "hsl(var(--muted) / 0.6)",
    paddingInline: space.s2,
    paddingBlock: "1px",
    fontSize: "10px",
    fontWeight: 500,
    color: colors.mutedForeground,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
  },
  tagChip: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: "hsl(var(--muted) / 0.4)",
    paddingInline: space.s1,
    paddingBlock: "1px",
    fontSize: "10px",
    color: colors.mutedForeground,
  },
  tagOverflowChip: {
    paddingInline: space.s1,
    fontSize: "10px",
    color: "hsl(var(--muted-foreground) / 0.6)",
  },
  compactEvidence: {
    marginTop: space.s0_5,
    fontSize: "10px",
    color: "hsl(var(--muted-foreground) / 0.5)",
  },
  tooltipContent: {
    maxWidth: "20rem",
    whiteSpace: "pre-line",
    fontSize: text.sizeXs,
    lineHeight: 1.625,
  },
});
