import * as stylex from "@stylexjs/stylex";
import { colors, text, space, motion } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

export const styles = stylex.create({
  panel: {
    display: "flex",
    flexDirection: "column",
    gap: space.s4,
  },
  qualityLabel: {
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 600,
  },
  qualityOptions: {
    display: "flex",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: "hsl(var(--muted) / 0.3)",
    padding: space.s0_5,
  },
  stackY1_5: { marginTop: { default: space.s1_5, ":first-child": 0 } },
  qualitySegment: {
    flex: "1 1 0%",
    paddingLeft: space.s2,
    paddingRight: space.s2,
    paddingTop: space.s1,
    paddingBottom: space.s1,
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  qualitySegmentActive: {
    backgroundColor: colors.bg,
    fontWeight: 500,
    color: colors.text,
    boxShadow: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
  },
  qualitySegmentInactive: {
    color: { default: colors.mutedForeground, ":hover": colors.text },
  },
  qualityDescription: {
    fontSize: "11px",
    lineHeight: 1.625,
    color: colors.mutedForeground,
  },
  layerStatusList: {
    display: "flex",
    flexDirection: "column",
    gap: space.s2,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "hsl(var(--border) / 0.7)",
    padding: "0.625rem",
  },
  clearCacheButton: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    gap: space.s1_5,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    paddingInline: space.s2,
    paddingBlock: space.s1_5,
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    color: { default: colors.mutedForeground, ":hover": colors.text },
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
    backgroundColor: { default: null, ":hover": colors.muted },
    opacity: { default: null, ":disabled": 0.5 },
  },
  clearCacheIcon: {
    width: "0.75rem",
    height: "0.75rem",
  },
  layerStatusRow: {
    display: "flex",
    alignItems: "center",
    gap: space.s2,
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    color: colors.text,
  },
  layerIcon: {
    width: "0.75rem",
    height: "0.75rem",
    color: colors.mutedForeground,
  },
  layerLabel: {
    flex: "1 1 0%",
  },
  layerCheckIcon: {
    width: "0.75rem",
    height: "0.75rem",
    color: "#22c55e",
  },
});
