import * as stylex from "@stylexjs/stylex";
import { colors, text, space, motion } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

export const styles = stylex.create({
  collapsibleSectionToggle: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    gap: space.s1_5,
    paddingBottom: space.s1_5,
  },
  chevronMutedShrink: {
    width: "0.75rem",
    height: "0.75rem",
    flexShrink: 0,
    color: colors.mutedForeground,
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  rotate90: {
    transform: "rotate(90deg)",
  },
  sectionIcon: {
    width: "0.75rem",
    height: "0.75rem",
    color: colors.mutedForeground,
    flexShrink: 0,
  },
  sectionLabel: {
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 600,
  },
  sectionContent: {
    display: "flex",
    flexDirection: "column",
    gap: space.s0_5,
    marginLeft: "18px",
  },
  statRow: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: space.s2,
    paddingBlock: space.s0_5,
  },
  statLabel: {
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    color: colors.mutedForeground,
  },
  statValue: {
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 500,
    fontVariantNumeric: "tabular-nums",
    textAlign: "right",
  },
  statsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: space.s3,
    paddingTop: space.s1,
  },
  expansionControls: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  expandCollapseButton: {
    display: "flex",
    alignItems: "center",
    gap: space.s1,
    fontSize: "10px",
    color: { default: colors.mutedForeground, ":hover": colors.text },
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  expandCollapseIcon: {
    width: "0.75rem",
    height: "0.75rem",
  },
  lodSummary: {
    marginTop: space.s2,
    marginBottom: space.s1,
  },
  lodSummaryTitle: {
    fontSize: "10px",
    fontWeight: 500,
    color: "hsl(var(--muted-foreground) / 0.7)",
    textTransform: "uppercase",
    letterSpacing: "0.025em",
    marginBottom: space.s1_5,
  },
  lodSummaryRows: {
    display: "flex",
    flexDirection: "column",
    gap: space.s0_5,
  },
  readinessSignals: {
    display: "flex",
    flexDirection: "column",
    gap: space.s2,
    paddingBlock: space.s1,
  },
  limitationsList: {
    display: "flex",
    flexDirection: "column",
    gap: space.s1_5,
    paddingBlock: space.s1,
  },
  limitationItem: {
    fontSize: text.sizeXs,
    lineHeight: 1.625,
    color: colors.mutedForeground,
  },
  strengthStrong: {
    backgroundColor: "rgba(34, 197, 94, 0.1)",
    color: "#4ade80",
    borderColor: "rgba(34, 197, 94, 0.2)",
  },
  strengthModerate: {
    backgroundColor: "rgba(245, 158, 11, 0.1)",
    color: "#fbbf24",
    borderColor: "rgba(245, 158, 11, 0.2)",
  },
  strengthLimited: {
    backgroundColor: colors.muted,
    color: colors.mutedForeground,
    borderColor: colors.border,
  },
  readinessSignalHeader: {
    display: "flex",
    alignItems: "center",
    gap: space.s1_5,
    marginBottom: space.s0_5,
  },
  strengthBadge: {
    display: "inline-flex",
    alignItems: "center",
    paddingInline: space.s1_5,
    paddingBlock: "1px",
    fontSize: "10px",
    fontWeight: 500,
    borderWidth: "1px",
    borderStyle: "solid",
  },
  readinessSignalLabel: {
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 500,
  },
  readinessSignalDescription: {
    fontSize: "11px",
    color: colors.mutedForeground,
    lineHeight: 1.625,
    marginLeft: space.s0_5,
  },
});
