import * as stylex from "@stylexjs/stylex";
import { colors, text, space, motion } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

export const styles = stylex.create({
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: space.s2,
    paddingBlock: space.s8,
    textAlign: "center",
    color: colors.mutedForeground,
  },
  emptyStateIcon: {
    width: "2rem",
    height: "2rem",
    opacity: 0.5,
  },
  emptyStateMessage: {
    fontSize: text.sizeXs,
    lineHeight: "1rem",
  },
  inspectorContainer: {
    display: "flex",
    flexDirection: "column",
    gap: space.s2,
  },
  selectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  selectionTitle: {
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 600,
    color: colors.mutedForeground,
  },
  clearSelectionButton: {
    display: "flex",
    width: "1.25rem",
    height: "1.25rem",
    alignItems: "center",
    justifyContent: "center",
    color: { default: colors.mutedForeground, ":hover": colors.text },
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
    backgroundColor: { default: null, ":hover": "hsl(var(--muted) / 0.5)" },
  },
  clearSelectionIcon: {
    width: "0.875rem",
    height: "0.875rem",
  },
  featureList: {
    display: "flex",
    flexDirection: "column",
    gap: space.s1,
  },
  elementCard: {
    borderWidth: "1px",
    borderStyle: "solid",
    textAlign: "left",
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  elementCardSelected: {
    borderColor: colors.primary,
    backgroundColor: "hsl(var(--primary) / 0.1)",
  },
  elementCardIdle: {
    borderColor: colors.border,
    backgroundColor: { default: "hsl(var(--muted) / 0.2)", ":hover": "hsl(var(--muted) / 0.4)" },
  },
  featureToggleButton: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    gap: space.s1_5,
    paddingInline: "0.625rem",
    paddingBlock: space.s2,
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 500,
    color: colors.text,
  },
  chevronLg: {
    width: "0.875rem",
    height: "0.875rem",
    flexShrink: 0,
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  rotate90: {
    transform: "rotate(90deg)",
  },
  featureSummary: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  expandedDetails: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderColor: colors.border,
    paddingInline: "0.625rem",
    paddingBlock: space.s2,
  },
  featureActionRow: {
    marginBottom: space.s2,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.s2,
  },
  geometryLabel: {
    fontSize: "11px",
    color: colors.mutedForeground,
  },
  detailValue: {
    fontWeight: 500,
    color: colors.text,
  },
  copyGeoJsonButton: {
    display: "flex",
    alignItems: "center",
    gap: space.s1,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    paddingInline: space.s1_5,
    paddingBlock: space.s0_5,
    fontSize: "11px",
    color: { default: colors.mutedForeground, ":hover": colors.text },
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
    backgroundColor: { default: null, ":hover": "hsl(var(--muted) / 0.5)" },
  },
  copiedIcon: {
    width: "0.75rem",
    height: "0.75rem",
    color: "#22c55e",
  },
  copyIcon: {
    width: "0.75rem",
    height: "0.75rem",
  },
  streetFactsSection: {
    display: "flex",
    flexDirection: "column",
    gap: space.s1,
    marginBottom: space.s2,
  },
  streetFactsHeading: {
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.025em",
    color: colors.mutedForeground,
  },
  detailRow: {
    display: "flex",
    alignItems: "baseline",
    gap: space.s2,
    fontSize: text.sizeXs,
    lineHeight: "1rem",
  },
  detailLabel: {
    flexShrink: 0,
    color: colors.mutedForeground,
  },
  overtureSource: {
    marginLeft: space.s1,
    fontWeight: 400,
    color: colors.mutedForeground,
  },
  sectionDivider: {
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderColor: "hsl(var(--border) / 0.5)",
    paddingTop: space.s1,
  },
  identifierSection: {
    display: "flex",
    flexDirection: "column",
    gap: space.s1,
    marginBottom: space.s2,
  },
  identifierValue: {
    fontFamily: "var(--font-mono), ui-monospace, monospace",
    color: "hsl(var(--foreground) / 0.8)",
    fontSize: "10px",
    wordBreak: "break-all",
  },
  propertiesHeading: {
    marginBottom: space.s1_5,
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.025em",
    color: colors.mutedForeground,
  },
});
