import * as stylex from "@stylexjs/stylex";
import { colors, text, space, motion } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

export const styles = stylex.create({
  mapLayersToggle: {
    display: "flex",
    alignItems: "center",
    gap: space.sm,
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.025em",
    color: { default: colors.mutedForeground, ":hover": colors.text },
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  chevron: {
    width: "0.75rem",
    height: "0.75rem",
    flexShrink: 0,
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  rotate90: {
    transform: "rotate(90deg)",
  },
  layerGroupsList: {
    display: "flex",
    flexDirection: "column",
    gap: space.md,
    marginTop: space.md,
  },
  groupHeaderRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.625rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: "hsl(var(--muted) / 0.2)",
    paddingInline: "0.625rem",
    paddingBlock: space.sm,
  },
  groupExpandButton: {
    flexShrink: 0,
  },
  chevronMuted: {
    width: "0.75rem",
    height: "0.75rem",
    color: colors.mutedForeground,
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  groupTitle: {
    minWidth: 0,
    flex: "1 1 0%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 500,
    color: "hsl(var(--foreground) / 0.9)",
  },
  loadingIndicator: {
    width: "0.875rem",
    height: "0.875rem",
    flexShrink: 0,
    animationName: spin,
    animationDuration: "1s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
    color: colors.mutedForeground,
  },
  partiallyEnabled: {
    opacity: 0.6,
  },
  groupItemsList: {
    display: "flex",
    flexDirection: "column",
    gap: space.sm,
    marginLeft: space.xl,
  },
  layerLabel: {
    minWidth: 0,
    flex: "1 1 0%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    color: "hsl(var(--foreground) / 0.9)",
  },
  laneModeToggleGroup: {
    display: "flex",
    flexShrink: 0,
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
  },
  laneModeButton: {
    paddingInline: space.md,
    paddingBlock: space.xxs,
    fontSize: "11px",
    fontWeight: 500,
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  laneModeButtonActive: {
    backgroundColor: colors.primary,
    color: colors.primaryForeground,
  },
  laneModeButtonIdle: {
    backgroundColor: "hsl(var(--muted) / 0.3)",
    color: { default: colors.mutedForeground, ":hover": colors.text },
  },
  layerRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.625rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: "hsl(var(--muted) / 0.2)",
    paddingInline: "0.625rem",
    paddingBlock: space.xs,
  },
  layerRowEmpty: {
    opacity: 0.4,
  },
  layerColorDot: {
    width: "0.5rem",
    height: "0.5rem",
    flexShrink: 0,
  },
  layerCount: {
    flexShrink: 0,
    fontFamily: "var(--font-mono), ui-monospace, monospace",
    fontSize: "11px",
    color: colors.mutedForeground,
  },
  compactLayerRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.625rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: "hsl(var(--muted) / 0.2)",
    paddingInline: "0.625rem",
    paddingBlock: space.xs,
  },
  dotInHouseSpeedLimits: { backgroundColor: "#111111" },
  enrichmentEmptyState: {
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: colors.border,
    paddingInline: "0.625rem",
    paddingBlock: "0.625rem",
  },
  enrichmentEmptyMessage: {
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    color: colors.mutedForeground,
    marginBottom: space.md,
  },
  enrichmentActionButton: {
    width: "100%",
  },
  enrichmentLoadingIcon: {
    marginRight: space.sm,
    width: "0.875rem",
    height: "0.875rem",
    animationName: spin,
    animationDuration: "1s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
  },
  enrichmentActionIcon: {
    marginRight: space.sm,
    width: "0.875rem",
    height: "0.875rem",
  },
  providerReleaseRow: {
    display: "flex",
    alignItems: "center",
    gap: space.sm,
    paddingInline: space.xs,
    fontSize: "10px",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: colors.mutedForeground,
  },
  providerReleaseLabel: {
    fontFamily: "var(--font-mono), ui-monospace, monospace",
    color: "hsl(var(--muted-foreground) / 0.7)",
  },
  enrichmentGlyphDot: {
    display: "flex",
    width: "1rem",
    height: "1rem",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  enrichmentGlyphIcon: {
    width: "0.625rem",
    height: "0.625rem",
  },
  dotOvertureSpeedLimits: { backgroundColor: "#2563eb" },
  dotScenarioCandidate: { backgroundColor: "#f97316" },
  twinMetadataRow: {
    paddingInline: space.xs,
    fontSize: "10px",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: colors.mutedForeground,
  },
  twinReferenceVersion: {
    marginLeft: space.xs,
    fontFamily: "var(--font-mono), ui-monospace, monospace",
    color: "hsl(var(--muted-foreground) / 0.7)",
  },
  resolutionSelectorRow: {
    display: "flex",
    alignItems: "center",
    gap: space.sm,
    paddingInline: space.xs,
  },
  resolutionLabel: {
    fontSize: "10px",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: colors.mutedForeground,
  },
  resolutionButton: {
    borderWidth: "1px",
    borderStyle: "solid",
    paddingInline: space.sm,
    paddingBlock: space.xxs,
    fontSize: "10px",
    fontFamily: "var(--font-mono), ui-monospace, monospace",
  },
  resolutionButtonActive: {
    borderColor: "hsl(var(--primary) / 0.6)",
    backgroundColor: "hsl(var(--primary) / 0.15)",
    color: colors.text,
  },
  resolutionButtonIdle: {
    borderColor: colors.border,
    backgroundColor: "hsl(var(--muted) / 0.2)",
    color: { default: colors.mutedForeground, ":hover": colors.text },
  },
  twinFidelityLegend: {
    paddingInline: space.xs,
    fontSize: "10px",
    color: colors.mutedForeground,
  },
});
