import * as stylex from "@stylexjs/stylex";
import { colors, motion, space, stroke, text } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

export const styles = stylex.create({
  sliderRow: {
    marginTop: space.s1_5,
    display: "flex",
    alignItems: "center",
    gap: space.s2,
  },
  sliderLabel: {
    width: "3.5rem",
    flexShrink: 0,
    fontSize: "10px",
    textTransform: "uppercase",
    letterSpacing: text.trackingWider,
    color: colors.mutedForeground,
  },
  sliderInput: {
    height: "0.25rem",
    flex: "1 1 0%",
    cursor: "pointer",
    accentColor: colors.primary,
  },
  sliderValue: {
    width: "2rem",
    flexShrink: 0,
    textAlign: "right",
    fontFamily: text.fontMono,
    fontSize: "10px",
    color: colors.mutedForeground,
  },
  uploadHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  uploadTitle: {
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    fontWeight: text.weightSemibold,
    textTransform: "uppercase",
    letterSpacing: text.trackingWide,
    color: colors.mutedForeground,
  },
  uploadButton: {
    display: "flex",
    alignItems: "center",
    gap: space.s1_5,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: { default: "hsl(var(--muted) / 0.2)", ":hover": "hsl(var(--muted) / 0.4)" },
    paddingInline: space.s2,
    paddingBlock: space.s1,
    fontSize: "11px",
    fontWeight: text.weightMedium,
    color: "hsl(var(--foreground) / 0.9)",
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durStandard,
  },
  uploadIcon: {
    width: "0.75rem",
    height: "0.75rem",
  },
  fileInput: {
    display: "none",
  },
  errorMessage: {
    marginTop: space.s2,
    display: "flex",
    alignItems: "flex-start",
    gap: space.s1_5,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: "hsl(var(--destructive) / 0.4)",
    backgroundColor: "hsl(var(--destructive) / 0.1)",
    paddingInline: space.s2_5,
    paddingBlock: space.s1_5,
    fontSize: "11px",
    color: colors.danger,
  },
  errorIcon: {
    marginTop: "1px",
    width: "0.875rem",
    height: "0.875rem",
    flexShrink: 0,
  },
  layerList: {
    display: "flex",
    flexDirection: "column",
    gap: space.s1_5,
    marginTop: space.s2,
  },
  layerItem: {
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: "hsl(var(--muted) / 0.2)",
    paddingInline: space.s2_5,
    paddingBlock: space.s1_5,
  },
  layerControls: {
    display: "flex",
    alignItems: "center",
    gap: space.s2,
  },
  colorButton: {
    position: "relative",
    display: "flex",
    width: "1rem",
    height: "1rem",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "inset 0 0 0 1px rgba(0, 0, 0, 0.2)",
  },
  paletteIcon: {
    width: "0.625rem",
    height: "0.625rem",
    color: "rgba(255, 255, 255, 0.8)",
  },
  layerName: {
    minWidth: 0,
    flex: "1 1 0%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: "hsl(var(--foreground) / 0.9)",
  },
  featureCount: {
    flexShrink: 0,
    fontFamily: text.fontMono,
    fontSize: "11px",
    color: colors.mutedForeground,
  },
  removeButton: {
    display: "flex",
    width: "1.25rem",
    height: "1.25rem",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    color: { default: colors.mutedForeground, ":hover": colors.danger },
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durStandard,
    backgroundColor: { default: null, ":hover": "hsl(var(--destructive) / 0.15)" },
  },
  removeIcon: {
    width: "0.875rem",
    height: "0.875rem",
  },
  colorPalette: {
    marginTop: space.s2,
    display: "flex",
    flexWrap: "wrap",
    gap: space.s1_5,
  },
  colorSwatch: {
    width: "1rem",
    height: "1rem",
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durStandard,
    transform: { default: null, ":hover": "scale(1.1)" },
    boxShadow: "inset 0 0 0 1px rgba(0, 0, 0, 0.2)",
  },
  colorSwatchSelected: {
    boxShadow: "inset 0 0 0 2px hsl(var(--foreground))",
  },
});
