import * as stylex from "@stylexjs/stylex";
import { colors, space, stroke, text } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

export const styles = stylex.create({
  sliderRow: {
    marginTop: space.s1_5,
    display: "flex",
    alignItems: "center",
    gap: space.s2,
  },
  sliderLabel: {
    width: "3.5rem",
    flexShrink: 0,
    color: colors.mutedForeground,
  },
  sliderInput: {
    height: "0.25rem",
    flex: "1 1 0%",
    cursor: "pointer",
    accentColor: colors.primary,
  },
  sliderValue: {
    width: "2rem",
    flexShrink: 0,
    textAlign: "right",
    fontFamily: text.fontMono,
    fontSize: text.sizeMicro,
    color: colors.mutedForeground,
  },
  uploadHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  uploadTitle: {
    color: colors.mutedForeground,
  },
  uploadButton: {
    display: "flex",
    alignItems: "center",
    gap: space.s1_5,
    backgroundColor: { default: colors.fillFaint, ":hover": colors.fillSubtle },
    paddingInline: space.s2,
    paddingBlock: space.s1,
    fontSize: text.sizeMeta,
    fontWeight: text.weightMedium,
    color: colors.ink,
  },
  uploadIcon: {
    width: "0.75rem",
    height: "0.75rem",
  },
  fileInput: {
    display: "none",
  },
  errorMessage: {
    marginTop: space.s2,
    display: "flex",
    alignItems: "flex-start",
    gap: space.s1_5,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: colors.critical,
    backgroundColor: colors.criticalWash,
    paddingInline: space.s2_5,
    paddingBlock: space.s1_5,
    fontSize: text.sizeMeta,
    color: colors.danger,
  },
  errorIcon: {
    marginTop: "1px",
    width: "0.875rem",
    height: "0.875rem",
    flexShrink: 0,
  },
  layerList: {
    display: "flex",
    flexDirection: "column",
    gap: space.s1_5,
    marginTop: space.s2,
  },
  layerItem: {
    backgroundColor: colors.fillFaint,
    paddingInline: space.s2_5,
    paddingBlock: space.s1_5,
  },
  layerControls: {
    display: "flex",
    alignItems: "center",
    gap: space.s2,
  },
  colorButton: {
    position: "relative",
    display: "flex",
    width: "1rem",
    height: "1rem",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "inset 0 0 0 1px rgba(0, 0, 0, 0.2)",
  },
  paletteIcon: {
    width: "0.625rem",
    height: "0.625rem",
    color: colors.inkSecondary,
  },
  layerName: {
    minWidth: 0,
    flex: "1 1 0%",
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.ink,
  },
  featureCount: {
    flexShrink: 0,
    fontFamily: text.fontMono,
    fontSize: text.sizeMeta,
    color: colors.mutedForeground,
  },
  removeButton: {
    display: "flex",
    width: "1.25rem",
    height: "1.25rem",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    color: { default: colors.mutedForeground, ":hover": colors.danger },
    backgroundColor: { default: null, ":hover": colors.criticalWash },
  },
  removeIcon: {
    width: "0.875rem",
    height: "0.875rem",
  },
  colorPalette: {
    marginTop: space.s2,
    display: "flex",
    flexWrap: "wrap",
    gap: space.s1_5,
  },
  colorSwatch: {
    width: "1rem",
    height: "1rem",
    transform: { default: null, ":hover": "scale(1.1)" },
    boxShadow: "inset 0 0 0 1px rgba(0, 0, 0, 0.2)",
  },
  colorSwatchSelected: {
    boxShadow: "inset 0 0 0 2px hsl(var(--foreground))",
  },
});
