// Generated by packages/asset-catalog/scripts/generate-catalog.ts. Do not edit.
pub const CATALOG_ALIASES: &[(&str, &str)] = &[
    ("pedestrian.adult_standing", "pedestrian.adult"),
    ("pedestrian.adult_walking", "pedestrian.adult"),
    ("pedestrian.child_standing", "pedestrian.child"),
    ("pedestrian.child_walking", "pedestrian.child"),
    ("object.tyre", "hazard.tire_debris"),
    ("object.tire", "hazard.tire_debris"),
    ("object.box", "hazard.cardboard_box"),
    ("object.cardboard_box", "hazard.cardboard_box"),
    ("object.branch", "hazard.downed_branch"),
    ("object.trash_bags", "hazard.trash_bags"),
    ("object.ladder", "hazard.ladder"),
    ("object.mattress", "hazard.mattress"),
    ("object.debris", "hazard.debris"),
    ("object.shed_load", "hazard.debris"),
    ("object.shopping_cart", "street.shopping_cart"),
    ("object.cone", "construction.traffic_cone"),
    ("object.traffic_cone", "construction.traffic_cone"),
    ("object.barrel", "construction.channelizer_drum"),
    ("object.drum", "construction.channelizer_drum"),
    ("object.barrier", "construction.jersey_barrier"),
    ("object.jersey_barrier", "construction.jersey_barrier"),
    ("object.barrier_run", "construction.jersey_barrier_run"),
    ("object.barricade", "construction.barricade_type3"),
    ("object.pedestrian_barrier", "construction.pedestrian_barrier"),
    ("object.sign_board", "construction.sign_road_work"),
    ("object.arrow_board", "construction.arrow_board"),
    ("object.stop_sign", "construction.temporary_stop_sign"),
    ("animal.doe", "animal.deer"),
    ("animal.buck", "animal.deer"),
    ("animal.stray_dog", "animal.dog"),
];

pub fn canonical_catalog_id(id: &str) -> &str {
    CATALOG_ALIASES.iter().find(|(alias, _)| *alias == id).map_or(id, |(_, target)| *target)
}
