import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { z } from "zod";
import { MODEL_CATALOG, MODEL_FAMILIES, type ModelFamilyId } from "./catalog";

/**
 * `simforge.model-lock/v1` — the integrity contract for every model install.
 *
 * Generated by `studio/desktop/gen-models-lock.mjs` from upstream metadata and
 * committed. Two digest kinds, both published by upstream so a reviewer can
 * confirm them without trusting this repository:
 *
 *  - `hf-lfs`        `lfs.sha256` verbatim. Every weight shard.
 *  - `git-blob-sha1` the `blobId` Hugging Face publishes for non-LFS files,
 *                    which is `sha1("blob " + size + "\0" + content)` and is
 *                    therefore recomputable from downloaded bytes. Used for
 *                    config/tokenizer text, including in the gated
 *                    Cosmos-Reason2 sidecar whose content needs a token the
 *                    lock generator deliberately does not require.
 *
 * The lock lives under `studio/app` rather than `studio/desktop` because the
 * desktop shell is bundled into a single `main.mjs` where a sibling JSON file
 * would not exist at runtime, while the whole studio tree is copied into the
 * packaged app's resources.
 */
export const MODEL_LOCK_SCHEMA = "simforge.model-lock/v1";

const LockFileSchema = z
  .object({
    path: z.string().min(1),
    digestSource: z.enum(["hf-lfs", "git-blob-sha1"]),
    sha256: z.string().regex(/^[0-9a-f]{64}$/).nullable(),
    blobId: z.string().regex(/^[0-9a-f]{40}$/).nullable(),
    sizeBytes: z.number().int().nonnegative().nullable(),
  })
  .superRefine((file, ctx) => {
    // A record with neither digest is not a pin, and silently accepting one
    // would make "verified" mean nothing for that file.
    if (file.digestSource === "hf-lfs" && !file.sha256) {
      ctx.addIssue({ code: "custom", message: `${file.path}: hf-lfs record without sha256` });
    }
    if (file.digestSource === "git-blob-sha1" && !file.blobId) {
      ctx.addIssue({ code: "custom", message: `${file.path}: git-blob-sha1 record without blobId` });
    }
    if (file.digestSource === "git-blob-sha1" && file.sizeBytes === null) {
      // The git blob header contains the length, so the size is part of the
      // digest, not an independent extra.
      ctx.addIssue({ code: "custom", message: `${file.path}: blob-id pin requires sizeBytes` });
    }
  });

export type ModelLockFile = z.infer<typeof LockFileSchema>;

const SidecarSchema = z.object({
  repo: z.string().min(1),
  revision: z.string().regex(/^[0-9a-f]{40}$/),
  gated: z.union([z.literal(false), z.literal(true), z.literal("auto")]),
  license: z.string().nullable(),
  files: z.array(LockFileSchema).min(1),
});

const ModelEntrySchema = z.object({
  displayName: z.string().min(1),
  weights: z.object({
    repo: z.string().min(1),
    revision: z.string().regex(/^[0-9a-f]{40}$/),
    license: z.literal("OpenMDW-1.1"),
    licenseBlobSha: z.string().regex(/^[0-9a-f]{40}$/),
    // Bare 64-hex: the exact string `model_versions.checkpoint_digest`
    // stores and the model-run worker compares against the live engine.
    checkpointDigest: z.string().regex(/^[0-9a-f]{64}$/),
    totalBytes: z.number().int().positive(),
    weightBytes: z.number().int().positive(),
    files: z.array(LockFileSchema).min(2),
  }),
  sidecars: z.array(SidecarSchema),
  code: z.object({
    git: z.string().url(),
    commit: z.string().regex(/^[0-9a-f]{40}$/),
    treeSha: z.string().regex(/^[0-9a-f]{40}$/).nullable(),
    committedAt: z.string().nullable(),
    license: z.string().min(1),
    lock: z.string().min(1),
  }),
  runtime: z.object({
    python: z.string().min(1),
    attn: z.string().min(1),
    torch: z.string().min(1),
    package: z.string().min(1),
  }),
});

export type ModelLockEntry = z.infer<typeof ModelEntrySchema>;

export const ModelLockSchema = z
  .object({
    schema: z.literal(MODEL_LOCK_SCHEMA),
    note: z.string().optional(),
    generator: z.string().optional(),
    models: z.record(z.string(), ModelEntrySchema),
  })
  .superRefine((lock, ctx) => {
    for (const family of MODEL_FAMILIES) {
      const entry = lock.models[family];
      if (!entry) {
        ctx.addIssue({ code: "custom", message: `lock is missing family ${family}` });
        continue;
      }
      // The catalog is what the product shows; the lock is what the installer
      // fetches. If they disagree, the UI would describe one checkpoint while
      // the store materialized another, so this is a hard validation failure
      // rather than a warning.
      const catalog = MODEL_CATALOG[family];
      if (entry.weights.repo !== catalog.weightsRepo) {
        ctx.addIssue({
          code: "custom",
          message: `${family}: lock repo ${entry.weights.repo} != catalog ${catalog.weightsRepo}`,
        });
      }
      if (entry.weights.revision !== catalog.weightsRevision) {
        ctx.addIssue({
          code: "custom",
          message:
            `${family}: lock revision ${entry.weights.revision} != catalog ` +
            `${catalog.weightsRevision}`,
        });
      }
      if (entry.code.commit !== catalog.codeRevision) {
        ctx.addIssue({
          code: "custom",
          message: `${family}: lock code commit != catalog ${catalog.codeRevision}`,
        });
      }
      if (entry.runtime.package !== catalog.pythonPackage) {
        ctx.addIssue({
          code: "custom",
          message: `${family}: lock package != catalog ${catalog.pythonPackage}`,
        });
      }
      if (entry.weights.licenseBlobSha !== catalog.license.blobSha) {
        ctx.addIssue({
          code: "custom",
          message: `${family}: LICENSE blob differs from the catalog pin`,
        });
      }
      const lockGated = entry.sidecars.some((sidecar) => sidecar.gated !== false);
      if (lockGated !== catalog.requiresUserHfToken) {
        ctx.addIssue({
          code: "custom",
          message:
            `${family}: lock says gated sidecar=${lockGated} but the catalog says ` +
            `requiresUserHfToken=${catalog.requiresUserHfToken}; the install flow ` +
            "gates the token prompt on the catalog value",
        });
      }
      const catalogSidecars = catalog.sidecars.map((sidecar) => `${sidecar.repo}@${sidecar.revision}`).sort();
      const lockSidecars = entry.sidecars.map((sidecar) => `${sidecar.repo}@${sidecar.revision}`).sort();
      if (catalogSidecars.join("|") !== lockSidecars.join("|")) {
        ctx.addIssue({
          code: "custom",
          message: `${family}: sidecar pins differ — lock [${lockSidecars}] vs catalog [${catalogSidecars}]`,
        });
      }
    }
  });

export type ModelLock = z.infer<typeof ModelLockSchema>;

/**
 * The lock sits at the package root and is listed in `files`, so it is
 * present both in the source tree (`src/../models.lock.json`) and in a
 * published/staged install (`dist/../models.lock.json`). Resolving it
 * relative to this module therefore works in dev, in the built package and
 * inside the packaged desktop app's `node_modules`.
 */
export const LOCK_FILENAME = "models.lock.json";

let cached: ModelLock | null = null;

/**
 * Parse and validate the committed lock. Cached: it is an immutable build
 * artifact, and every request that lists model state would otherwise re-read
 * and re-validate ~90 file records.
 */
export async function loadModelLock(): Promise<ModelLock> {
  if (cached) return cached;
  const raw = await readFile(new URL(`../${LOCK_FILENAME}`, import.meta.url), "utf8");
  const parsed = ModelLockSchema.safeParse(JSON.parse(raw));
  if (!parsed.success) {
    throw new Error(
      `models.lock.json failed validation: ${parsed.error.issues
        .map((issue) => issue.message)
        .join("; ")}`,
    );
  }
  cached = parsed.data;
  return cached;
}

export async function lockEntry(family: ModelFamilyId): Promise<ModelLockEntry> {
  const lock = await loadModelLock();
  const entry = lock.models[family];
  if (!entry) throw new Error(`models.lock.json has no entry for ${family}`);
  return entry;
}

/** Every file an install of one family must materialize, with its destination. */
export function installFiles(
  entry: ModelLockEntry,
): { role: "weights" | "sidecar"; repo: string; revision: string; gated: boolean | "auto"; file: ModelLockFile; destination: string }[] {
  const out = entry.weights.files.map((file) => ({
    role: "weights" as const,
    repo: entry.weights.repo,
    revision: entry.weights.revision,
    gated: false as const,
    file,
    destination: join("weights", file.path),
  }));
  for (const sidecar of entry.sidecars) {
    for (const file of sidecar.files) {
      out.push({
        role: "sidecar",
        repo: sidecar.repo,
        revision: sidecar.revision,
        gated: sidecar.gated,
        file,
        destination: join("sidecars", sidecar.repo.replace("/", "--"), file.path),
      });
    }
  }
  return out;
}
