import * as stylex from "@stylexjs/stylex";
import { colors, layers, radii, text } from "../../stylex/tokens.stylex";

const TRANSITION = "color, background-color, border-color, text-decoration-color, fill, stroke";

export const styles = stylex.create({
  subTrigger: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    cursor: "default",
    userSelect: "none",
    borderRadius: radii.sm,
    paddingInline: "0.5rem",
    paddingBlock: "0.375rem",
    fontSize: text.sizeSm,
    outline: "none",
    backgroundColor: { default: null, ":focus": colors.muted, "[data-state=open]": colors.muted },
  },
  subContent: {
    zIndex: 100,
    minWidth: "8rem",
    overflow: "hidden",
    borderRadius: radii.md,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.popover,
    padding: "0.25rem",
    color: colors.text,
    boxShadow: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
  },
  content: {
    zIndex: 100,
    minWidth: "8rem",
    overflow: "hidden",
    borderRadius: radii.md,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.popover,
    padding: "0.25rem",
    color: colors.text,
    boxShadow: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
  },
  item: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    cursor: "default",
    userSelect: "none",
    borderRadius: radii.sm,
    paddingInline: "0.5rem",
    paddingBlock: "0.375rem",
    fontSize: text.sizeSm,
    outline: "none",
    transitionProperty: TRANSITION,
    transitionDuration: "150ms",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    backgroundColor: { default: null, ":focus": colors.muted },
    color: { default: null, ":focus": colors.text },
  },
  checkboxItem: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    cursor: "default",
    userSelect: "none",
    borderRadius: radii.sm,
    paddingTop: "0.375rem",
    paddingBottom: "0.375rem",
    paddingLeft: "2rem",
    paddingRight: "0.5rem",
    fontSize: text.sizeSm,
    outline: "none",
    transitionProperty: TRANSITION,
    transitionDuration: "150ms",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    backgroundColor: { default: null, ":focus": colors.muted },
    color: { default: null, ":focus": colors.text },
  },
  radioItem: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    cursor: "default",
    userSelect: "none",
    borderRadius: radii.sm,
    paddingTop: "0.375rem",
    paddingBottom: "0.375rem",
    paddingLeft: "2rem",
    paddingRight: "0.5rem",
    fontSize: text.sizeSm,
    outline: "none",
    transitionProperty: TRANSITION,
    transitionDuration: "150ms",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    backgroundColor: { default: null, ":focus": colors.muted },
    color: { default: null, ":focus": colors.text },
  },
  label: {
    paddingInline: "0.5rem",
    paddingBlock: "0.375rem",
    fontSize: text.sizeSm,
    fontWeight: 600,
  },
  separator: {
    marginInline: "-0.25rem",
    marginBlock: "0.25rem",
    height: 1,
    backgroundColor: colors.muted,
  },
  shortcut: { marginLeft: "auto", fontSize: text.sizeXs, letterSpacing: "0.1em", opacity: 0.6 },
  indicator: { position: "absolute", left: "0.5rem", display: "flex", width: "0.875rem", height: "0.875rem", alignItems: "center", justifyContent: "center" },
  icon: { pointerEvents: "none", width: "1rem", height: "1rem", flexShrink: 0 },
  itemIcon: { width: "1rem", height: "1rem", flexShrink: 0 },
  inset: { paddingLeft: "2rem" },
});
