import * as stylex from "@stylexjs/stylex";
import { colors, layers, motion, radii, shadows, space, stroke, text } from "../../stylex/tokens.stylex";

const TRANSITION = "color, background-color, border-color, text-decoration-color, fill, stroke";

export const styles = stylex.create({
  subTrigger: {
    display: "flex",
    alignItems: "center",
    gap: space.s2,
    cursor: "default",
    userSelect: "none",
    borderRadius: radii.sm,
    paddingInline: space.s2,
    paddingBlock: space.s1_5,
    fontSize: text.sizeSm,
    lineHeight: text.lineSm,
    // `outline-none`: Tailwind's transparent 2px outline, not `outline: none`,
    // so forced-colours mode still has an outline to repaint.
    outlineWidth: stroke.thick,
    outlineStyle: "solid",
    outlineColor: "transparent",
    outlineOffset: "2px",
    backgroundColor: { default: null, ":focus": colors.muted, "[data-state=open]": colors.muted },
  },
  subContent: {
    zIndex: layers.popover,
    minWidth: "8rem",
    overflow: "hidden",
    borderRadius: radii.md,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.popover,
    padding: space.s1,
    color: colors.text,
    boxShadow: shadows.elevationLg,
  },
  content: {
    zIndex: layers.popover,
    minWidth: "8rem",
    overflow: "hidden",
    borderRadius: radii.md,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.popover,
    padding: space.s1,
    color: colors.text,
    boxShadow: shadows.elevationLg,
  },
  item: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: space.s2,
    cursor: "default",
    userSelect: "none",
    borderRadius: radii.sm,
    paddingInline: space.s2,
    paddingBlock: space.s1_5,
    fontSize: text.sizeSm,
    lineHeight: text.lineSm,
    // `outline-none`: transparent 2px outline (see subTrigger).
    outlineWidth: stroke.thick,
    outlineStyle: "solid",
    outlineColor: "transparent",
    outlineOffset: "2px",
    transitionProperty: TRANSITION,
    transitionDuration: motion.durStandard,
    transitionTimingFunction: motion.easeStandard,
    backgroundColor: { default: null, ":focus": colors.muted },
    color: { default: null, ":focus": colors.text },
  },
  checkboxItem: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    cursor: "default",
    userSelect: "none",
    borderRadius: radii.sm,
    paddingTop: space.s1_5,
    paddingBottom: space.s1_5,
    paddingLeft: space.s8,
    paddingRight: space.s2,
    fontSize: text.sizeSm,
    lineHeight: text.lineSm,
    // `outline-none`: transparent 2px outline (see subTrigger).
    outlineWidth: stroke.thick,
    outlineStyle: "solid",
    outlineColor: "transparent",
    outlineOffset: "2px",
    transitionProperty: TRANSITION,
    transitionDuration: motion.durStandard,
    transitionTimingFunction: motion.easeStandard,
    backgroundColor: { default: null, ":focus": colors.muted },
    color: { default: null, ":focus": colors.text },
  },
  radioItem: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    cursor: "default",
    userSelect: "none",
    borderRadius: radii.sm,
    paddingTop: space.s1_5,
    paddingBottom: space.s1_5,
    paddingLeft: space.s8,
    paddingRight: space.s2,
    fontSize: text.sizeSm,
    lineHeight: text.lineSm,
    // `outline-none`: transparent 2px outline (see subTrigger).
    outlineWidth: stroke.thick,
    outlineStyle: "solid",
    outlineColor: "transparent",
    outlineOffset: "2px",
    transitionProperty: TRANSITION,
    transitionDuration: motion.durStandard,
    transitionTimingFunction: motion.easeStandard,
    backgroundColor: { default: null, ":focus": colors.muted },
    color: { default: null, ":focus": colors.text },
  },
  label: {
    paddingInline: space.s2,
    paddingBlock: space.s1_5,
    fontSize: text.sizeSm,
    lineHeight: text.lineSm,
    fontWeight: text.weightSemibold,
  },
  separator: {
    marginInline: "-0.25rem",
    marginBlock: space.s1,
    height: 1,
    backgroundColor: colors.muted,
  },
  shortcut: { marginLeft: "auto", fontSize: text.sizeXs, lineHeight: text.lineXs, letterSpacing: text.trackingMetaNarrow, opacity: 0.6 },
  indicator: { position: "absolute", left: "0.5rem", display: "flex", width: "0.875rem", height: "0.875rem", alignItems: "center", justifyContent: "center" },
  icon: { pointerEvents: "none", width: "1rem", height: "1rem", flexShrink: 0 },
  /** Radio indicator dot: `h-2 w-2 fill-current` — overrides lucide's `fill="none"`. */
  radioDot: { width: "0.5rem", height: "0.5rem", fill: "currentColor" },
  inset: { paddingLeft: space.s8 },
});
