import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  fullscreen: { position: "absolute", inset: 0, width: "100%", height: "100%" },
  map: { width: "100%", height: "100%" },
  control: { position: "absolute", zIndex: 30 },
  modeControl: { bottom: "0.75rem", right: "0.75rem", display: "flex", alignItems: "center", borderRadius: "999px", overflow: "hidden", boxShadow: "0 2px 8px rgba(0,0,0,0.4)", fontFamily: "system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif" },
  modeButton: { padding: "0.3rem 0.85rem", fontSize: "0.75rem", letterSpacing: "0.02em", border: "none", whiteSpace: "nowrap", display: "flex", alignItems: "center", gap: "0.35rem", transition: "background 0.15s, color 0.15s" },
  modeFollow: { display: "flex", alignItems: "center", justifyContent: "center", width: 30, padding: 0, border: "none", transition: "background 0.15s, color 0.15s" },
  spinner: { width: 8, height: 8, borderRadius: "999px", animation: "mapViewModeSpin 700ms linear infinite" },
  icon13: { width: 13, height: 13 },
  measureControl: { bottom: "2.5rem", right: "0.75rem" },
  satelliteControl: { bottom: "0.75rem", left: "0.75rem" },
  toggleButton: { padding: "0.3rem 0.75rem", fontSize: "0.75rem", borderRadius: "6px", fontFamily: "system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif" },
  loading: { display: "flex", height: "100%", minHeight: "400px", alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0,0,0,0.5)", fontSize: "0.875rem" },
  tooltipText: { opacity: 0.7 },
  popoverHeading: { marginBottom: "0.5rem", fontWeight: 500 },
  popoverList: { listStyle: "none", margin: 0, padding: 0 },
  popoverItem: { marginBottom: "0.25rem" },
  popoverAsset: { display: "block", width: "100%", textAlign: "left", padding: "0.5rem 0.6rem", backgroundColor: "rgba(255,255,255,0.05)", border: "1px solid rgba(255,255,255,0.15)", borderRadius: "6px", fontSize: "0.8125rem", cursor: "pointer" },
  popoverClose: { marginTop: "0.5rem", padding: "0.25rem 0.5rem", fontSize: "0.75rem", backgroundColor: "transparent", border: "none", cursor: "pointer" },
  svgBlock: { display: "block" },
  svgOverflow: { display: "block", overflow: "visible" },
  featurePrimary: { fontSize: "0.75rem", fontWeight: 600, lineHeight: 1.35 },
  featureList: { listStyle: "none", margin: "0.35rem 0 0", padding: 0, display: "flex", flexDirection: "column", gap: "0.2rem" },
  featureItem: { fontSize: "0.72rem", lineHeight: 1.3 },
  resetButton: { position: "absolute", top: "0.75rem", left: "50%", transform: "translateX(-50%)", zIndex: 10, padding: "0.3rem 0.85rem", borderRadius: "999px", fontSize: "0.75rem", whiteSpace: "nowrap", cursor: "pointer", boxShadow: "0 2px 8px rgba(0,0,0,0.4)" },
  loadingPill: { position: "absolute", bottom: "0.75rem", left: "50%", transform: "translateX(-50%)", zIndex: 10, padding: "0.3rem 0.75rem", borderRadius: "999px", fontSize: "0.75rem", pointerEvents: "none", border: "1px solid rgba(255,255,255,0.15)", whiteSpace: "nowrap" },
  sensorMarker: { position: "relative", width: "48px", height: "48px", overflow: "visible", pointerEvents: "auto", transformOrigin: "center center" },
  sensorLabel: { position: "absolute", left: "50%", top: "100%", whiteSpace: "nowrap", fontSize: "11px", fontFamily: "'Open Sans', sans-serif", fontWeight: 600, color: "#ffffff", textShadow: "-1px -1px 0 #0f172a, 1px -1px 0 #0f172a, -1px 1px 0 #0f172a, 1px 1px 0 #0f172a", pointerEvents: "none", marginTop: "2px" },
  pinSvg: { display: "block", filter: "drop-shadow(0 1px 2px rgba(0,0,0,0.5))" },
});
