import * as stylex from "@stylexjs/stylex";
import { colors, text, space, layers, motion } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

export const styles = stylex.create({
  mapForm: {
    display: "flex",
    height: "100%",
    width: "100%",
    minHeight: 0,
    minWidth: 0,
    overflowY: "auto",
    flexDirection: "column",
  },
  topSection: {
    display: "flex",
    flexDirection: { default: "column", "@media (min-width: 1024px)": "row" },
    flexShrink: 0,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderColor: colors.border,
  },
  formFieldsColumn: {
    display: "flex",
    flexDirection: "column",
    gap: space.s4,
    flex: { default: "0 0 auto", "@media (min-width: 1024px)": "1 1 0%" },
    minWidth: 0,
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderColor: colors.border,
    paddingInline: space.s6,
    paddingBlock: "1.25rem",
  },
  errorMessage: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "hsl(var(--destructive) / 0.5)",
    backgroundColor: "hsl(var(--destructive) / 0.1)",
    paddingInline: space.s3,
    paddingBlock: space.s2,
    fontSize: text.sizeSm,
    lineHeight: "1.25rem",
    color: colors.danger,
  },
  fieldHelperText: {
    marginBottom: space.s2,
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    color: colors.mutedForeground,
  },
  fileUploadRow: {
    display: "flex",
    alignItems: "center",
    gap: space.s3,
  },
  attachmentIcon: {
    marginRight: space.s1_5,
    width: "0.875rem",
    height: "0.875rem",
  },
  selectedFilename: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    color: colors.mutedForeground,
  },
  hiddenFileInput: {
    display: "none",
  },
  parseErrorMessage: {
    marginTop: space.s1_5,
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    color: colors.danger,
  },
  metadataSummary: {
    marginTop: space.s2,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: "hsl(var(--muted) / 0.3)",
    paddingInline: space.s3,
    paddingBlock: space.s2,
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    color: colors.mutedForeground,
  },
  metadataDetails: {
    display: "grid",
    gridTemplateColumns: "auto 1fr",
    columnGap: space.s3,
    rowGap: space.s0_5,
  },
  metadataLabel: {
    fontWeight: 500,
    color: colors.text,
  },
  metadataValue: {
    fontFamily: "var(--font-mono), ui-monospace, monospace",
  },
  descriptionTextarea: {
    width: "100%",
    resize: "none",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "hsl(var(--input))",
    backgroundColor: colors.bg,
    paddingInline: space.s3,
    paddingBlock: space.s2,
    fontSize: text.sizeSm,
    lineHeight: "1.25rem",
    color: colors.text,
    boxShadow: { default: "0 1px 2px 0 rgba(0, 0, 0, 0.05)", ":focus-visible": "0 0 0 1px hsl(var(--ring))" },
    /*
     * `focus-visible:outline-none` is Tailwind's transparent 2px outline, not
     * `outline: none`: the focus ring above is a box-shadow, which
     * forced-colours mode discards, and this transparent outline is what
     * remains visible there.
     */
    outlineWidth: { default: null, ":focus-visible": "2px" },
    outlineStyle: { default: null, ":focus-visible": "solid" },
    outlineColor: { default: null, ":focus-visible": "transparent" },
    outlineOffset: { default: null, ":focus-visible": "2px" },
    "::placeholder": { color: colors.mutedForeground },
  },
  carlaMapHelperText: {
    marginTop: space.s1,
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    color: colors.mutedForeground,
  },
  crsSelect: {
    width: "100%",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "hsl(var(--input))",
    backgroundColor: colors.bg,
    paddingInline: space.s3,
    paddingBlock: space.s2,
    fontSize: text.sizeSm,
    lineHeight: "1.25rem",
    color: colors.text,
    boxShadow: { default: "0 1px 2px 0 rgba(0, 0, 0, 0.05)", ":focus-visible": "0 0 0 1px hsl(var(--ring))" },
    /*
     * `focus-visible:outline-none` is Tailwind's transparent 2px outline, not
     * `outline: none`: the focus ring above is a box-shadow, which
     * forced-colours mode discards, and this transparent outline is what
     * remains visible there.
     */
    outlineWidth: { default: null, ":focus-visible": "2px" },
    outlineStyle: { default: null, ":focus-visible": "solid" },
    outlineColor: { default: null, ":focus-visible": "transparent" },
    outlineOffset: { default: null, ":focus-visible": "2px" },
  },
  mapPreview: {
    position: "relative",
    aspectRatio: "1",
    width: { default: "100%", "@media (min-width: 1024px)": "400px" },
    maxWidth: "400px",
    flexShrink: 0,
    alignSelf: "flex-start",
  },
  thumbnailStatus: {
    position: "absolute",
    bottom: "0.5rem",
    right: "0.5rem",
    zIndex: layers.raised,
    display: "flex",
    alignItems: "center",
    gap: space.s1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    paddingInline: space.s2,
    paddingBlock: space.s1,
    fontSize: "10px",
    color: "#34d399",
  },
  cameraIcon: {
    width: "0.75rem",
    height: "0.75rem",
  },
  emptyPreview: {
    display: "flex",
    height: "100%",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: space.s3,
    color: colors.mutedForeground,
  },
  mapPinIcon: {
    width: "2rem",
    height: "2rem",
    opacity: 0.3,
  },
  emptyPreviewMessage: {
    fontSize: text.sizeSm,
    lineHeight: "1.25rem",
  },
  bottomSection: {
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    gap: space.s6,
    padding: space.s6,
  },
  actionButtons: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: space.s3,
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderColor: colors.border,
    paddingTop: space.s4,
  },
  debugSection: {
    flexShrink: 0,
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderColor: colors.border,
    paddingInline: space.s6,
    paddingBlock: space.s3,
  },
  debugToggle: {
    display: "flex",
    alignItems: "center",
    gap: space.s1_5,
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    color: { default: colors.mutedForeground, ":hover": colors.text },
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  chevronLg: {
    width: "0.875rem",
    height: "0.875rem",
    flexShrink: 0,
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  rotateMinus90: {
    transform: "rotate(-90deg)",
  },
  debugPayload: {
    marginTop: space.s2,
    maxHeight: "24rem",
    overflow: "auto",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: "hsl(var(--muted) / 0.2)",
    padding: space.s3,
    fontSize: "11px",
    lineHeight: 1.625,
    color: colors.mutedForeground,
  },
});
