import * as stylex from "@stylexjs/stylex";
import { colors, layers, shadows, space, stroke, text } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

export const styles = stylex.create({
  sectionHeader: {
    marginBottom: space.s3,
    display: "flex",
    alignItems: "center",
    gap: space.s3,
  },
  sectionTitle: {
    fontSize: text.sizeSm,
    lineHeight: text.lineSm,
    fontWeight: text.weightSemibold,
    color: colors.text,
  },
  tagCount: {
    paddingInline: space.s2_5,
    paddingBlock: space.s0_5,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    fontWeight: text.weightSemibold,
    fontVariantNumeric: "tabular-nums",
  },
  tagCountFilled: {
    backgroundColor: "rgba(66, 32, 6, 0.6)",
    color: colors.warning,
  },
  tagCountEmpty: {
    backgroundColor: colors.fillSubtle,
    color: colors.mutedForeground,
  },
  loadingStatus: {
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.mutedForeground,
  },
  tagList: {
    marginBottom: space.s3,
    display: "flex",
    flexWrap: "wrap",
    gap: space.s1_5,
  },
  tagChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.s1,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    paddingInline: space.s1_5,
    paddingBlock: space.s0_5,
    fontFamily: text.fontMono,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
  },
  tagChipAuto: {
    borderColor: "rgba(29, 78, 216, 0.6)",
    backgroundColor: "rgba(23, 37, 84, 0.4)",
    color: colors.info,
  },
  tagChipManual: {
    borderColor: "rgba(161, 98, 7, 0.6)",
    backgroundColor: "rgba(66, 32, 6, 0.4)",
    color: colors.warning,
  },
  autoBadge: {
    backgroundColor: "rgba(30, 64, 175, 0.5)",
    paddingInline: space.s1,
    paddingBlock: "1px",
    fontSize: text.sizeTag,
    fontWeight: text.weightSemibold,
    textTransform: "uppercase",
    lineHeight: 1,
    color: colors.info,
  },
  tagRemove: {
    marginLeft: space.s0_5,
  },
  tagRemoveAuto: {
    color: { default: colors.info, ":hover": "#bfdbfe" },
  },
  tagRemoveManual: {
    color: { default: colors.warning, ":hover": "#fef08a" },
  },
  removeIcon: {
    width: "0.625rem",
    height: "0.625rem",
  },
  addTagSection: {
    position: "relative",
    marginBottom: space.s3,
  },
  compactOutlineControl: {
    height: "1.75rem",
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
  },
  tagDropdownPanel: {
    position: "absolute",
    left: "0",
    top: "2rem",
    zIndex: layers.float,
    width: "20rem",
    backgroundColor: colors.bg,
    boxShadow: shadows.elevationLg,
  },
  searchInputWrapper: {
    padding: space.s2,
  },
  tagOptionsList: {
    maxHeight: "12rem",
    overflowY: "auto",
  },
  noMatchingTags: {
    paddingInline: space.s3,
    paddingBlock: space.s2,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.mutedForeground,
  },
  tagOptionButton: {
    display: "flex",
    width: "100%",
    alignItems: "flex-start",
    gap: space.s2,
    paddingInline: space.s3,
    paddingBlock: space.s1_5,
    textAlign: "left",
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    backgroundColor: { default: null, ":hover": colors.fillSubtle },
  },
  tagOptionLabel: {
    flexShrink: 0,
    fontFamily: text.fontMono,
    fontWeight: text.weightMedium,
    color: colors.text,
  },
  tagOptionDescription: {
    color: colors.mutedForeground,
  },
  csvToggle: {
    display: "flex",
    alignItems: "center",
    gap: space.s1_5,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: { default: colors.mutedForeground, ":hover": colors.text },
  },
  chevron: {
    width: "0.75rem",
    height: "0.75rem",
    flexShrink: 0,
  },
  rotateMinus90: {
    transform: "rotate(-90deg)",
  },
  csvPanel: {
    marginTop: space.s2,
    maxWidth: "32rem",
  },
  csvTextarea: {
    width: "100%",
    resize: "none",
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: colors.input,
    backgroundColor: colors.bg,
    paddingInline: space.s2_5,
    paddingBlock: space.s1_5,
    fontFamily: text.fontMono,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.text,
    "::placeholder": { color: colors.inkFaint },
  },
  stackY1_5: { marginTop: { default: space.s1_5, ":first-child": 0 } },
  csvErrorMessage: {
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.danger,
  },
  csvErrorList: {
    fontFamily: text.fontMono,
  },
});
