import * as stylex from "@stylexjs/stylex";
import { colors, text, space, layers, motion } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

export const styles = stylex.create({
  s_211: {
    position: "fixed",
    inset: "0",
    zIndex: 40,
    display: "grid",
    placeItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    backdropFilter: "blur(4px)",
  },
  s_212: {
    display: "flex",
    alignItems: "center",
    gap: space.md,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    paddingInline: space.xl,
    paddingBlock: space.lg,
    fontSize: text.sizeSm,
    lineHeight: "1.25rem",
    color: "#fff",
  },
  s_213: {
    width: "1rem",
    height: "1rem",
    animationName: spin,
    animationDuration: "1s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
    color: colors.accent,
  },
  s_214: {
    position: "absolute",
    inset: "0",
    isolation: "isolate",
  },
  s_847: {
    width: "1rem",
    height: "1rem",
  },
  s_216: {
    display: "grid",
    width: "2.5rem",
    height: "2.5rem",
    placeItems: "center",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: "rgba(255, 255, 255, 0.2)", ":hover": "rgba(255, 255, 255, 0.45)" },
    backgroundColor: { default: colors.overlayMat, ":hover": colors.chip },
    color: { default: "rgba(255, 255, 255, 0.85)", ":hover": "#fff" },
    backdropFilter: motion.blurGlass,
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
    /*
     * `focus-visible:outline-none` is Tailwind's transparent 2px outline, not
     * `outline: none`: the focus ring above is a box-shadow, which
     * forced-colours mode discards, and this transparent outline is what
     * remains visible there.
     */
    outlineWidth: { default: null, ":focus-visible": "2px" },
    outlineStyle: { default: null, ":focus-visible": "solid" },
    outlineColor: { default: null, ":focus-visible": "transparent" },
    outlineOffset: { default: null, ":focus-visible": "2px" },
    pointerEvents: { default: null, ":disabled": "none" },
    opacity: { default: null, ":disabled": 0.3 },
    boxShadow: { default: null, ":focus-visible": "0 0 0 2px #E8E044" },
  },
  s_251: {
    width: "18px",
    height: "18px",
  },
  s_946: {
    width: "1.75rem",
    height: "1.75rem",
  },
  s_219: {
    marginRight: space.sm,
    width: "1rem",
    height: "1rem",
  },
  s_220: {
    height: "100%",
  },
  s_221: {
    position: "relative",
    height: "100%",
    minHeight: "32rem",
    overflow: "hidden",
    backgroundColor: "#07100d",
    color: "#fff",
  },
  s_801: {
    position: "absolute",
    inset: "0",
  },
  s_223: {
    position: "absolute",
    inset: "0",
    backgroundImage: "radial-gradient(ellipse at center,rgba(232,224,68,0.08),transparent 60%)",
  },
  s_224: {
    pointerEvents: "none",
    position: "absolute",
    left: "0",
    right: "0",
    bottom: "0",
    zIndex: layers.raised,
    height: "50%",
    backgroundImage: "linear-gradient(to top, rgba(0, 0, 0, 0.45), rgba(0, 0, 0, 0.1), transparent)",
  },
  s_225: {
    pointerEvents: "none",
    position: "absolute",
    left: "0",
    right: "0",
    top: "0",
    zIndex: layers.raised,
    height: "6rem",
    backgroundImage: "linear-gradient(to bottom, rgba(0, 0, 0, 0.25), transparent)",
  },
  s_226: {
    position: "absolute",
    right: { default: "1.25rem", "@media (min-width: 640px)": "2rem" },
    top: { default: "1.25rem", "@media (min-width: 640px)": "2rem" },
    zIndex: layers.sticky,
    display: "flex",
    alignItems: "center",
    gap: space.md,
  },
  sumoToggle: {
    display: "inline-flex",
    height: "2.5rem",
    alignItems: "center",
    gap: space.md,
    borderWidth: "1px",
    borderStyle: "solid",
    paddingInline: "0.875rem",
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 600,
    backdropFilter: motion.blurGlass,
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
    /*
     * `focus-visible:outline-none` is Tailwind's transparent 2px outline, not
     * `outline: none`: the focus ring above is a box-shadow, which
     * forced-colours mode discards, and this transparent outline is what
     * remains visible there.
     */
    outlineWidth: { default: null, ":focus-visible": "2px" },
    outlineStyle: { default: null, ":focus-visible": "solid" },
    outlineColor: { default: null, ":focus-visible": "transparent" },
    outlineOffset: { default: null, ":focus-visible": "2px" },
    boxShadow: { default: null, ":focus-visible": "0 0 0 2px #E8E044" },
  },
  sumoToggleOn: {
    borderColor: "rgba(232, 224, 68, 0.65)",
    backgroundColor: { default: "rgba(232, 224, 68, 0.14)", ":hover": "rgba(232, 224, 68, 0.22)" },
    color: colors.accent,
  },
  sumoToggleOff: {
    borderColor: { default: "rgba(255, 255, 255, 0.2)", ":hover": "rgba(255, 255, 255, 0.4)" },
    backgroundColor: colors.overlayScrim,
    color: { default: "rgba(255, 255, 255, 0.7)", ":hover": "#fff" },
  },
  sumoToggleUnavailable: {
    cursor: "not-allowed",
    opacity: 0.45,
  },
  s_254: {
    width: "1rem",
    height: "1rem",
    animationName: spin,
    animationDuration: "1s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
  },
  s_230: {
    fontFamily: "var(--font-mono), ui-monospace, monospace",
    fontSize: "9px",
    color: "color-mix(in srgb, currentColor 65%, transparent)",
  },
  s_231: {
    display: "inline-flex",
    height: "2.5rem",
    alignItems: "center",
    gap: space.md,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: "rgba(255, 255, 255, 0.2)", ":hover": "rgba(232, 224, 68, 0.7)" },
    backgroundColor: { default: colors.overlayScrim, ":hover": "rgba(0, 0, 0, 0.65)" },
    paddingInline: "0.875rem",
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 600,
    color: "#fff",
    backdropFilter: motion.blurGlass,
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
    /*
     * `focus-visible:outline-none` is Tailwind's transparent 2px outline, not
     * `outline: none`: the focus ring above is a box-shadow, which
     * forced-colours mode discards, and this transparent outline is what
     * remains visible there.
     */
    outlineWidth: { default: null, ":focus-visible": "2px" },
    outlineStyle: { default: null, ":focus-visible": "solid" },
    outlineColor: { default: null, ":focus-visible": "transparent" },
    outlineOffset: { default: null, ":focus-visible": "2px" },
    cursor: { default: null, ":disabled": "not-allowed" },
    opacity: { default: null, ":disabled": 0.4 },
    boxShadow: { default: null, ":focus-visible": "0 0 0 2px #E8E044" },
  },
  s_232: {
    width: "1rem",
    height: "1rem",
    color: colors.accent,
  },
  s_233: {
    pointerEvents: "none",
    position: "absolute",
    bottom: "0",
    left: "0",
    zIndex: layers.raised,
    height: "88%",
    width: { default: "92%", "@media (min-width: 640px)": "78%", "@media (min-width: 1024px)": "68%" },
    backgroundImage: "radial-gradient(ellipse at bottom left,rgba(2,8,6,0.76) 0%,rgba(2,8,6,0.58) 30%,rgba(2,8,6,0.2) 55%,transparent 76%)",
    backdropFilter: "blur(14px)",
  },
  diagonalVeilMask: {
    maskImage:
      "radial-gradient(ellipse 92% 105% at 0% 100%, black 0%, black 38%, rgba(0,0,0,0.76) 52%, transparent 78%)",
    WebkitMaskImage:
      "radial-gradient(ellipse 92% 105% at 0% 100%, black 0%, black 38%, rgba(0,0,0,0.76) 52%, transparent 78%)",
  },
  s_234: {
    position: "absolute",
    left: "0",
    right: "0",
    bottom: "0",
    zIndex: 20,
  },
  s_235: {
    marginInline: "auto",
    width: "100%",
    maxWidth: "1440px",
    paddingInline: { default: "1.25rem", "@media (min-width: 640px)": space.xxxl, "@media (min-width: 1024px)": space.datasetStripWidth },
    paddingBottom: { default: "1.25rem", "@media (min-width: 640px)": space.xxxl, "@media (min-width: 1024px)": "2.5rem" },
  },
  s_236: {
    maxWidth: "42rem",
  },
  s_237: {
    display: "flex",
    alignItems: "center",
    gap: space.md,
    fontSize: { default: "10px", "@media (min-width: 640px)": "11px" },
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.24em",
    color: colors.accent,
  },
  s_991: {
    width: "0.875rem",
    height: "0.875rem",
  },
  s_239: {
    marginTop: space.lg,
    maxWidth: "48rem",
    textWrap: "balance",
    fontSize: "clamp(2.25rem,4.2vw,4.5rem)",
    fontWeight: 600,
    lineHeight: "0.96",
    letterSpacing: "-0.045em",
    color: "#fff",
  },
  heroTitleShadow: { textShadow: "0 4px 28px rgba(0,0,0,0.5)" },
  s_240: {
    marginTop: space.lg,
    display: "flex",
    alignItems: "center",
    gap: space.sm,
    fontSize: { default: text.sizeSm, "@media (min-width: 640px)": text.sizeBase },
    lineHeight: { default: "1.25rem", "@media (min-width: 640px)": "1.5rem" },
    color: "rgba(255, 255, 255, 0.72)",
  },
  s_241: {
    width: "0.875rem",
    height: "0.875rem",
    color: colors.accent,
  },
  s_242: {
    marginTop: space.md,
    overflow: "hidden",
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
    maxWidth: "36rem",
    fontSize: text.sizeSm,
    lineHeight: "1.5rem",
    color: "rgba(255, 255, 255, 0.62)",
  },
  s_243: {
    marginTop: space.lg,
    display: "flex",
    minHeight: "1.25rem",
    flexWrap: "wrap",
    alignItems: "center",
    columnGap: space.xl,
    rowGap: space.xs,
    fontSize: { default: "11px", "@media (min-width: 640px)": text.sizeXs },
    color: colors.textSubtle,
    lineHeight: { default: null, "@media (min-width: 640px)": "1rem" },
  },
  s_940: {
    fontFamily: "var(--font-mono), ui-monospace, monospace",
  },
  s_245: {
    pointerEvents: "auto",
    display: "inline-flex",
    alignItems: "center",
    gap: space.xs,
    color: { default: "rgba(255, 255, 255, 0.58)", ":hover": "#fff" },
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  s_247: {
    marginTop: space.xl,
  },
  s_248: {
    marginTop: { default: "1.25rem", "@media (min-width: 640px)": "1.75rem" },
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.xl,
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.2)",
    paddingTop: { default: space.xl, "@media (min-width: 640px)": "1.25rem" },
  },
  s_908: {
    display: "flex",
    alignItems: "center",
    gap: space.md,
  },
  s_250: {
    display: "grid",
    width: "2.5rem",
    height: "2.5rem",
    placeItems: "center",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: "rgba(255, 255, 255, 0.2)", ":hover": "rgba(232, 224, 68, 0.7)" },
    backgroundColor: { default: colors.overlayMat, ":hover": "rgba(232, 224, 68, 0.1)" },
    color: { default: "rgba(255, 255, 255, 0.85)", ":hover": colors.accent },
    backdropFilter: motion.blurGlass,
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
    /*
     * `focus-visible:outline-none` is Tailwind's transparent 2px outline, not
     * `outline: none`: the focus ring above is a box-shadow, which
     * forced-colours mode discards, and this transparent outline is what
     * remains visible there.
     */
    outlineWidth: { default: null, ":focus-visible": "2px" },
    outlineStyle: { default: null, ":focus-visible": "solid" },
    outlineColor: { default: null, ":focus-visible": "transparent" },
    outlineOffset: { default: null, ":focus-visible": "2px" },
    boxShadow: { default: null, ":focus-visible": "0 0 0 2px #E8E044" },
  },
  s_252: {
    marginLeft: space.md,
    fontFamily: "var(--font-mono), ui-monospace, monospace",
    fontSize: "11px",
    letterSpacing: "0.16em",
    color: colors.textSubtle,
  },
  heroActions: {
    display: "flex",
    alignItems: "center",
    gap: space.md,
  },
  s_253: {
    height: "2.75rem",
    backgroundColor: { default: colors.accent, ":hover": "#f0e84e" },
    paddingInline: { default: space.xl, "@media (min-width: 640px)": "1.25rem" },
    fontSize: text.sizeSm,
    lineHeight: "1.25rem",
    fontWeight: 600,
    color: "#000",
    boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)",
  },
});
