import * as stylex from "@stylexjs/stylex";
import { colors, layers, layout, motion, shadows, space, stroke, text } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

export const styles = stylex.create({
  s_211: {
    position: "fixed",
    inset: "0",
    zIndex: layers.overlay,
    display: "grid",
    placeItems: "center",
    backgroundColor: colors.scrimHeavy,
    backdropFilter: motion.blurSm,
  },
  s_212: {
    display: "flex",
    alignItems: "center",
    gap: space.s2,
    backgroundColor: colors.scrimHeavy,
    paddingInline: space.s4,
    paddingBlock: space.s3,
    fontSize: text.sizeSm,
    lineHeight: text.lineSm,
    color: colors.ink,
  },
  s_213: {
    width: "1rem",
    height: "1rem",
    animationName: spin,
    animationDuration: motion.durSpin,
    animationTimingFunction: motion.easeLinear,
    animationIterationCount: "infinite",
    color: colors.accent,
  },
  s_214: {
    position: "absolute",
    inset: "0",
    isolation: "isolate",
  },
  s_847: {
    width: "1rem",
    height: "1rem",
  },
  s_216: {
    display: "grid",
    width: "2.5rem",
    height: "2.5rem",
    placeItems: "center",
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: { default: colors.hairlineStrong, ":hover": colors.hairlineStrong },
    backgroundColor: { default: colors.scrimLight, ":hover": colors.fillStrong },
    color: { default: colors.ink, ":hover": colors.ink },
    backdropFilter: motion.blurGlass,
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durStandard,
    /*
     * `focus-visible:outline-none` is Tailwind's transparent 2px outline, not
     * `outline: none`: the focus ring above is a box-shadow, which
     * forced-colours mode discards, and this transparent outline is what
     * remains visible there.
     */
    outlineWidth: { default: null, ":focus-visible": stroke.thick },
    outlineStyle: { default: null, ":focus-visible": "solid" },
    outlineColor: { default: null, ":focus-visible": "transparent" },
    outlineOffset: { default: null, ":focus-visible": "2px" },
    pointerEvents: { default: null, ":disabled": "none" },
    opacity: { default: null, ":disabled": 0.3 },
    boxShadow: { default: null, ":focus-visible": shadows.ring },
  },
  s_251: {
    width: "18px",
    height: "18px",
  },
  s_946: {
    width: "1.75rem",
    height: "1.75rem",
  },
  s_219: {
    marginRight: space.s1_5,
    width: "1rem",
    height: "1rem",
  },
  s_220: {
    height: "100%",
  },
  s_221: {
    position: "relative",
    height: "100%",
    minHeight: "32rem",
    overflow: "hidden",
    backgroundColor: "#07100d",
    color: colors.ink,
  },
  s_801: {
    position: "absolute",
    inset: "0",
  },
  s_223: {
    position: "absolute",
    inset: "0",
    backgroundImage: "radial-gradient(ellipse at center,rgba(232,224,68,0.08),transparent 60%)",
  },
  s_224: {
    pointerEvents: "none",
    position: "absolute",
    left: "0",
    right: "0",
    bottom: "0",
    zIndex: layers.raised,
    height: "50%",
    backgroundImage: "linear-gradient(to top, rgba(0, 0, 0, 0.45), rgba(0, 0, 0, 0.1), transparent)",
  },
  s_225: {
    pointerEvents: "none",
    position: "absolute",
    left: "0",
    right: "0",
    top: "0",
    zIndex: layers.raised,
    height: "6rem",
    backgroundImage: "linear-gradient(to bottom, rgba(0, 0, 0, 0.25), transparent)",
  },
  s_226: {
    position: "absolute",
    right: { default: "1.25rem", [layout.bpSm]: "2rem" },
    top: { default: "1.25rem", [layout.bpSm]: "2rem" },
    zIndex: layers.sticky,
    display: "flex",
    alignItems: "center",
    gap: space.s2,
  },
  sumoToggle: {
    display: "inline-flex",
    height: "2.5rem",
    alignItems: "center",
    gap: space.s2,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    paddingInline: space.s3_5,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    fontWeight: text.weightSemibold,
    backdropFilter: motion.blurGlass,
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durStandard,
    /*
     * `focus-visible:outline-none` is Tailwind's transparent 2px outline, not
     * `outline: none`: the focus ring above is a box-shadow, which
     * forced-colours mode discards, and this transparent outline is what
     * remains visible there.
     */
    outlineWidth: { default: null, ":focus-visible": stroke.thick },
    outlineStyle: { default: null, ":focus-visible": "solid" },
    outlineColor: { default: null, ":focus-visible": "transparent" },
    outlineOffset: { default: null, ":focus-visible": "2px" },
    boxShadow: { default: null, ":focus-visible": shadows.ring },
  },
  sumoToggleOn: {
    borderColor: colors.accentLine,
    backgroundColor: { default: colors.accentWash, ":hover": "rgba(232, 224, 68, 0.22)" },
    color: colors.accent,
  },
  sumoToggleOff: {
    borderColor: { default: colors.hairlineStrong, ":hover": colors.hairlineStrong },
    backgroundColor: colors.scrim,
    color: { default: colors.inkSecondary, ":hover": colors.ink },
  },
  sumoToggleUnavailable: {
    cursor: "not-allowed",
    opacity: 0.45,
  },
  s_254: {
    width: "1rem",
    height: "1rem",
    animationName: spin,
    animationDuration: motion.durSpin,
    animationTimingFunction: motion.easeLinear,
    animationIterationCount: "infinite",
  },
  s_230: {
    fontFamily: text.fontMono,
    fontSize: text.sizeTag,
    color: "color-mix(in srgb, currentColor 65%, transparent)",
  },
  s_231: {
    display: "inline-flex",
    height: "2.5rem",
    alignItems: "center",
    gap: space.s2,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: { default: colors.hairlineStrong, ":hover": colors.accentLine },
    backgroundColor: { default: colors.scrim, ":hover": colors.scrimHeavy },
    paddingInline: space.s3_5,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    fontWeight: text.weightSemibold,
    color: colors.ink,
    backdropFilter: motion.blurGlass,
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durStandard,
    /*
     * `focus-visible:outline-none` is Tailwind's transparent 2px outline, not
     * `outline: none`: the focus ring above is a box-shadow, which
     * forced-colours mode discards, and this transparent outline is what
     * remains visible there.
     */
    outlineWidth: { default: null, ":focus-visible": stroke.thick },
    outlineStyle: { default: null, ":focus-visible": "solid" },
    outlineColor: { default: null, ":focus-visible": "transparent" },
    outlineOffset: { default: null, ":focus-visible": "2px" },
    cursor: { default: null, ":disabled": "not-allowed" },
    opacity: { default: null, ":disabled": 0.4 },
    boxShadow: { default: null, ":focus-visible": shadows.ring },
  },
  s_232: {
    width: "1rem",
    height: "1rem",
    color: colors.accent,
  },
  s_233: {
    pointerEvents: "none",
    position: "absolute",
    bottom: "0",
    left: "0",
    zIndex: layers.raised,
    height: "88%",
    width: { default: "92%", "@media (min-width: 640px)": "78%", "@media (min-width: 1024px)": "68%" },
    backgroundImage: "radial-gradient(ellipse at bottom left,rgba(2,8,6,0.76) 0%,rgba(2,8,6,0.58) 30%,rgba(2,8,6,0.2) 55%,transparent 76%)",
    backdropFilter: motion.blurGlass,
  },
  diagonalVeilMask: {
    maskImage:
      "radial-gradient(ellipse 92% 105% at 0% 100%, black 0%, black 38%, rgba(0,0,0,0.76) 52%, transparent 78%)",
    WebkitMaskImage:
      "radial-gradient(ellipse 92% 105% at 0% 100%, black 0%, black 38%, rgba(0,0,0,0.76) 52%, transparent 78%)",
  },
  s_234: {
    position: "absolute",
    left: "0",
    right: "0",
    bottom: "0",
    zIndex: layers.float,
  },
  s_235: {
    marginInline: "auto",
    width: "100%",
    maxWidth: "1440px",
    paddingInline: { default: space.s5, "@media (min-width: 640px)": space.s8, "@media (min-width: 1024px)": space.datasetStripWidth },
    paddingBottom: { default: space.s5, "@media (min-width: 640px)": space.s8, "@media (min-width: 1024px)": space.s10 },
  },
  s_236: {
    maxWidth: "42rem",
  },
  s_237: {
    display: "flex",
    alignItems: "center",
    gap: space.s2,
    fontSize: { default: text.sizeMicro, [layout.bpSm]: text.sizeMeta },
    fontWeight: text.weightSemibold,
    textTransform: "uppercase",
    letterSpacing: text.trackingMetaWidest,
    color: colors.accent,
  },
  s_991: {
    width: "0.875rem",
    height: "0.875rem",
  },
  s_239: {
    marginTop: space.s3,
    maxWidth: "48rem",
    textWrap: "balance",
    fontSize: "clamp(2.25rem,4.2vw,4.5rem)",
    fontWeight: text.weightSemibold,
    lineHeight: "0.96",
    letterSpacing: text.trackingTight,
    color: colors.ink,
  },
  heroTitleShadow: { textShadow: "0 4px 28px rgba(0,0,0,0.5)" },
  s_240: {
    marginTop: space.s3,
    display: "flex",
    alignItems: "center",
    gap: space.s1_5,
    fontSize: { default: text.sizeSm, [layout.bpSm]: text.sizeBase },
    lineHeight: { default: text.lineSm, [layout.bpSm]: text.lineBase },
    color: colors.inkSecondary,
  },
  s_241: {
    width: "0.875rem",
    height: "0.875rem",
    color: colors.accent,
  },
  s_242: {
    marginTop: space.s2,
    overflow: "hidden",
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
    maxWidth: "36rem",
    fontSize: text.sizeSm,
    lineHeight: text.lineBase,
    color: colors.inkSecondary,
  },
  s_243: {
    marginTop: space.s3,
    display: "flex",
    minHeight: "1.25rem",
    flexWrap: "wrap",
    alignItems: "center",
    columnGap: space.s4,
    rowGap: space.s1,
    fontSize: { default: text.sizeMeta, [layout.bpSm]: text.sizeXs },
    color: colors.inkMuted,
    lineHeight: { default: null, [layout.bpSm]: text.lineXs },
  },
  s_940: {
    fontFamily: text.fontMono,
  },
  s_245: {
    pointerEvents: "auto",
    display: "inline-flex",
    alignItems: "center",
    gap: space.s1,
    color: { default: colors.inkSecondary, ":hover": colors.ink },
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durStandard,
  },
  s_247: {
    marginTop: space.s4,
  },
  s_248: {
    marginTop: { default: space.s5, [layout.bpSm]: space.s7 },
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.s4,
    borderTopWidth: stroke.hairline,
    borderTopStyle: "solid",
    borderColor: colors.hairlineStrong,
    paddingTop: { default: space.s4, [layout.bpSm]: space.s5 },
  },
  s_908: {
    display: "flex",
    alignItems: "center",
    gap: space.s2,
  },
  s_250: {
    display: "grid",
    width: "2.5rem",
    height: "2.5rem",
    placeItems: "center",
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: { default: colors.hairlineStrong, ":hover": colors.accentLine },
    backgroundColor: { default: colors.scrimLight, ":hover": colors.accentWash },
    color: { default: colors.ink, ":hover": colors.accent },
    backdropFilter: motion.blurGlass,
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durStandard,
    /*
     * `focus-visible:outline-none` is Tailwind's transparent 2px outline, not
     * `outline: none`: the focus ring above is a box-shadow, which
     * forced-colours mode discards, and this transparent outline is what
     * remains visible there.
     */
    outlineWidth: { default: null, ":focus-visible": stroke.thick },
    outlineStyle: { default: null, ":focus-visible": "solid" },
    outlineColor: { default: null, ":focus-visible": "transparent" },
    outlineOffset: { default: null, ":focus-visible": "2px" },
    boxShadow: { default: null, ":focus-visible": shadows.ring },
  },
  s_252: {
    marginLeft: space.s2,
    fontFamily: text.fontMono,
    fontSize: text.sizeMeta,
    letterSpacing: text.trackingMetaWide,
    color: colors.inkMuted,
  },
  heroActions: {
    display: "flex",
    alignItems: "center",
    gap: space.s2,
  },
  s_253: {
    height: "2.75rem",
    backgroundColor: { default: colors.accent, ":hover": colors.accent },
    paddingInline: { default: space.s4, [layout.bpSm]: space.s5 },
    fontSize: text.sizeSm,
    lineHeight: text.lineSm,
    fontWeight: text.weightSemibold,
    color: "#000",
    boxShadow: shadows.elevationXl,
  },
});
