import * as stylex from "@stylexjs/stylex";
import { colors, layers, motion, shadows, space, stroke, text } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

const slideInFromRight2 = stylex.keyframes({
  from: { transform: "translate3d(0.5rem, 0, 0)" },
});

export const styles = stylex.create({
  sectionHeading: {
    marginBottom: space.s2,
    color: colors.mutedForeground,
  },
  editPanel: {
    animationName: slideInFromRight2,
    animationDuration: motion.durBase,
    animationTimingFunction: motion.easeDecelerate,
    position: "absolute",
    right: "0",
    top: "0",
    zIndex: layers.float,
    display: "flex",
    height: "100%",
    width: "20rem",
    flexDirection: "column",
    borderLeftWidth: stroke.hairline,
    borderLeftStyle: "solid",
    borderColor: colors.hairline,
    backgroundColor: colors.bg,
    boxShadow: shadows.elevationXl,
  },
  header: {
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    gap: space.s2,
    borderBottomWidth: stroke.hairline,
    borderBottomStyle: "solid",
    borderColor: colors.hairline,
    paddingInline: space.s3,
    paddingBlock: space.s2_5,
  },
  backButton: {
    flexShrink: 0,
  },
  backIcon: {
    width: "0.875rem",
    height: "0.875rem",
  },
  headerText: {
    minWidth: 0,
    flex: "1 1 0%",
  },
  editingEyebrow: {
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.mutedForeground,
  },
  assetName: {
    fontSize: text.sizeSm,
    lineHeight: text.lineSnug,
    fontWeight: text.weightSemibold,
  },
  scrollBody: {
    display: "flex",
    flexDirection: "column",
    gap: space.s5,
    flex: "1 1 0%",
    overflowY: "auto",
    padding: space.s3,
  },
  sectionDescription: {
    marginBottom: space.s2,
    fontSize: text.sizeMeta,
    color: colors.mutedForeground,
  },
  locationFields: {
    display: "flex",
    flexDirection: "column",
    gap: space.s2,
  },
  fieldLabel: {
    marginBottom: space.s0_5,
    display: "block",
    fontSize: text.sizeMeta,
    color: colors.mutedForeground,
  },
  compactControl: {
    height: "1.75rem",
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
  },
  textInput: {
    fontFamily: text.fontMono,
  },
  emptyImageryMessage: {
    fontSize: text.sizeMeta,
    fontStyle: "italic",
    color: colors.mutedForeground,
  },
  stackY2: { marginTop: { default: space.s2, ":first-child": 0 } },
  imageryRow: {
    padding: space.s2,
  },
  imageryRowHeader: {
    marginBottom: space.s1,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  imageryRowLabel: {
    fontSize: text.sizeMeta,
    fontWeight: text.weightMedium,
    color: colors.mutedForeground,
  },
  removeImageryButton: {
    fontSize: text.sizeMeta,
    color: { default: colors.mutedForeground, ":hover": colors.danger },
  },
  imageryFields: {
    display: "flex",
    flexDirection: "column",
    gap: space.s1_5,
  },
  addImageryButton: {
    fontSize: text.sizeMeta,
    fontWeight: text.weightMedium,
    color: colors.primary,
    textDecorationLine: { default: null, ":hover": "underline" },
  },
  offsetFields: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: space.s2,
  },
  tagCount: {
    marginLeft: space.s1_5,
    backgroundColor: "rgba(66, 32, 6, 0.6)",
    paddingInline: space.s1_5,
    paddingBlock: "1px",
    fontSize: text.sizeMicro,
    fontWeight: text.weightSemibold,
    color: colors.warning,
  },
  selectedTags: {
    marginBottom: space.s2,
    display: "flex",
    flexWrap: "wrap",
    gap: space.s1,
  },
  tagChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.s1,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: "rgba(234, 179, 8, 0.4)",
    backgroundColor: "rgba(234, 179, 8, 0.1)",
    paddingInline: space.s1_5,
    paddingBlock: space.s0_5,
    fontFamily: text.fontMono,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.warning,
  },
  removeTagButton: {
    color: { default: colors.warning, ":hover": colors.warning },
  },
  removeTagIcon: {
    width: "0.625rem",
    height: "0.625rem",
  },
  tagDropdownContainer: {
    position: "relative",
    marginBottom: space.s2,
  },
  tagDropdown: {
    position: "absolute",
    left: "0",
    top: "2rem",
    zIndex: layers.float,
    width: "18rem",
    backgroundColor: colors.bg,
    boxShadow: shadows.elevationLg,
  },
  tagSearchWrapper: {
    padding: space.s2,
  },
  tagOptions: {
    maxHeight: "12rem",
    overflowY: "auto",
  },
  noTagResults: {
    paddingInline: space.s3,
    paddingBlock: space.s2,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.mutedForeground,
  },
  tagOptionButton: {
    display: "flex",
    width: "100%",
    alignItems: "flex-start",
    gap: space.s2,
    paddingInline: space.s3,
    paddingBlock: space.s1_5,
    textAlign: "left",
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    backgroundColor: { default: null, ":hover": colors.fillSubtle },
  },
  tagOptionName: {
    flexShrink: 0,
    fontFamily: text.fontMono,
    fontWeight: text.weightMedium,
    color: colors.text,
  },
  tagOptionDescription: {
    color: colors.mutedForeground,
  },
  csvSection: {
    marginTop: space.s2,
  },
  csvToggle: {
    display: "flex",
    alignItems: "center",
    gap: space.s1_5,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: { default: colors.mutedForeground, ":hover": colors.text },
  },
  chevron: {
    width: "0.75rem",
    height: "0.75rem",
    flexShrink: 0,
  },
  rotateMinus90: {
    transform: "rotate(-90deg)",
  },
  inlineStackMt2: { marginTop: space.s2 },
  csvTextarea: {
    width: "100%",
    resize: "none",
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: colors.input,
    backgroundColor: colors.bg,
    paddingInline: space.s2_5,
    paddingBlock: space.s1_5,
    fontFamily: text.fontMono,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.text,
    "::placeholder": { color: colors.inkFaint },
  },
  stackY1_5: { marginTop: { default: space.s1_5, ":first-child": 0 } },
  validationMessage: {
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.danger,
  },
  inlineCode: {
    fontFamily: text.fontMono,
  },
  artifactListOrUploadProgress: {
    display: "flex",
    flexDirection: "column",
    gap: space.s1,
    marginBottom: space.s2,
  },
  existingArtifactRow: {
    display: "flex",
    alignItems: "center",
    gap: space.s1_5,
    paddingInline: space.s2,
    paddingBlock: space.s1,
  },
  artifactIcon: {
    width: "0.75rem",
    height: "0.75rem",
    flexShrink: 0,
    color: colors.mutedForeground,
  },
  existingArtifactName: {
    minWidth: 0,
    flex: "1 1 0%",
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.mutedForeground,
  },
  artifactLabel: {
    fontWeight: text.weightMedium,
    color: colors.text,
  },
  removeArtifactButton: {
    flexShrink: 0,
    color: { default: colors.inkFaint, ":hover": colors.danger },
  },
  removeArtifactIcon: {
    width: "0.75rem",
    height: "0.75rem",
  },
  hiddenFileInput: {
    display: "none",
  },
  uploadButtonIcon: {
    marginRight: space.s1_5,
    width: "0.75rem",
    height: "0.75rem",
  },
  pendingUploads: {
    display: "flex",
    flexDirection: "column",
    gap: space.s1_5,
    marginTop: space.s2,
  },
  pendingUploadRow: {
    display: "flex",
    alignItems: "center",
    gap: space.s1_5,
    paddingInline: space.s2,
    paddingBlock: space.s1_5,
  },
  pendingFilename: {
    minWidth: 0,
    flex: "1 1 0%",
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
  },
  pendingLabelInput: {
    width: "5rem",
    flexShrink: 0,
    paddingInline: space.s1_5,
  },
  clearPendingButton: {
    flexShrink: 0,
    color: { default: colors.inkFaint, ":hover": colors.text },
  },
  available3dRow: {
    marginBottom: space.s2,
    display: "flex",
    alignItems: "center",
    gap: space.s2,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: colors.positive,
    backgroundColor: colors.positiveWash,
    paddingInline: space.s2,
    paddingBlock: space.s1_5,
  },
  available3dIcon: {
    width: "0.875rem",
    height: "0.875rem",
    flexShrink: 0,
    color: colors.positive,
  },
  available3dStatus: {
    flex: "1 1 0%",
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.positive,
  },
  delete3dButton: {
    flexShrink: 0,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: { default: colors.inkFaint, ":hover": colors.danger },
  },
  deleted3dRow: {
    marginBottom: space.s2,
    display: "flex",
    alignItems: "center",
    gap: space.s2,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: colors.warning,
    backgroundColor: colors.warningWash,
    paddingInline: space.s2,
    paddingBlock: space.s1_5,
  },
  warningIcon: {
    width: "0.875rem",
    height: "0.875rem",
    flexShrink: 0,
    color: colors.warning,
  },
  deleted3dStatus: {
    flex: "1 1 0%",
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.warning,
  },
  selectedFolderRow: {
    marginBottom: space.s2,
    display: "flex",
    alignItems: "center",
    gap: space.s2,
    paddingInline: space.s2,
    paddingBlock: space.s1_5,
  },
  folderIcon: {
    width: "0.875rem",
    height: "0.875rem",
    flexShrink: 0,
    color: colors.mutedForeground,
  },
  selectedFolderSummary: {
    flex: "1 1 0%",
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.mutedForeground,
  },
  folderName: {
    fontFamily: text.fontMono,
    color: colors.text,
  },
  progressTrack: {
    height: "0.375rem",
    width: "100%",
    overflow: "hidden",
    backgroundColor: colors.muted,
  },
  progressFill: {
    height: "100%",
    backgroundColor: colors.primary,
    transitionProperty: "all",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durBase,
  },
  progressCaption: {
    fontSize: text.sizeMicro,
    color: colors.mutedForeground,
  },
  stickyFooter: {
    display: "flex",
    flexDirection: "column",
    gap: space.s2,
    flexShrink: 0,
    borderTopWidth: stroke.hairline,
    borderTopStyle: "solid",
    borderColor: colors.hairline,
    padding: space.s3,
  },
  footerActions: {
    display: "flex",
    gap: space.s2,
  },
  saveButton: {
    flex: "1 1 0%",
  },
});
