/**
 * The Node binding of `simforge-package` is the hosted exporter's writer:
 * from the same inputs it must emit byte-identical containers to the Rust
 * crate (the committed fixtures are the crate's output), and it must refuse
 * every hostile fixture with the crate's code and rule.
 *
 * Fixtures: fixtures/scenario-package/ (generated by
 * native/crates/simforge-package/tests/fixtures.rs).
 */

import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
  ScenarioPackageError,
  readScenarioPackage,
  verifyScenarioPackage,
  verifyScenarioPackageFile,
  writeScenarioPackage,
  writeScenarioPackageFile,
  type WriteScenarioPackageInput,
} from '../index.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = resolve(HERE, '..', '..', '..', '..', 'fixtures', 'scenario-package');

interface Expectation {
  file: string;
  valid: boolean;
  form?: 'thin' | 'full';
  packageId?: string;
  code?: string;
  rule?: string;
}

const expectations = JSON.parse(readFileSync(join(FIXTURES, 'expectations.json'), 'utf8')) as {
  readerCli: string;
  fixtures: Expectation[];
};
const cliVersion = expectations.readerCli;
const bytesOf = (file: string) => readFileSync(join(FIXTURES, file));

/** Rebuild the writer's inputs from a verified package. */
function inputsOf(bytes: Uint8Array): WriteScenarioPackageInput {
  const contents = readScenarioPackage(bytes, { cliVersion });
  const manifest = JSON.parse(contents.manifestJson) as Record<string, unknown>;
  delete manifest['members'];
  const receipt = contents.receiptJson
    ? (JSON.parse(contents.receiptJson) as { exportedAt: string; exporterRelease: string; textureTier?: string })
    : null;
  return {
    manifest,
    members: contents.members.map((m) => ({ path: m.path, data: m.data })),
    blobs: contents.blobs.map((b) => ({ data: b.data })),
    receipt: receipt && { exportedAt: receipt.exportedAt, exporterRelease: receipt.exporterRelease, textureTier: receipt.textureTier },
  };
}

describe('scenario packages through the Node binding', () => {
  for (const f of expectations.fixtures.filter((x) => x.valid)) {
    it(`${f.file}: verifies, and the binding rewrites it byte for byte`, () => {
      const bytes = bytesOf(f.file);
      const verification = verifyScenarioPackage(bytes, { cliVersion });
      expect(verification.packageId).toBe(f.packageId);
      expect(verification.form).toBe(f.form);
      expect(verification.cliCheck).toBe('passed');

      const written = writeScenarioPackage(inputsOf(bytes));
      expect(written.packageId).toBe(f.packageId);
      expect(written.form).toBe(f.form);
      expect(Buffer.compare(written.bytes, bytes)).toBe(0);
    });
  }

  for (const f of expectations.fixtures.filter((x) => !x.valid)) {
    it(`${f.file}: refused with ${f.code}/${f.rule}`, () => {
      let caught: unknown;
      try {
        verifyScenarioPackage(bytesOf(f.file), { cliVersion });
      } catch (error) {
        caught = error;
      }
      expect(caught).toBeInstanceOf(ScenarioPackageError);
      const e = caught as ScenarioPackageError;
      expect([e.code, e.rule]).toEqual([f.code, f.rule]);
    });
  }

  it('writes to a file through a temporary sibling and verifies from the path', () => {
    const full = expectations.fixtures.find((x) => x.valid && x.form === 'full')!;
    const dir = mkdtempSync(join(tmpdir(), 'simforge-package-'));
    try {
      const out = join(dir, 'export.scenario.zip');
      const result = writeScenarioPackageFile(out, inputsOf(bytesOf(full.file)));
      expect(result.packageId).toBe(full.packageId);
      expect(Buffer.compare(readFileSync(out), bytesOf(full.file))).toBe(0);
      expect(verifyScenarioPackageFile(out, { cliVersion }).form).toBe('full');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('refuses a draft that carries members[] and names version skew dimensions', () => {
    const thin = expectations.fixtures.find((x) => x.valid && x.form === 'thin')!;
    const input = inputsOf(bytesOf(thin.file));
    expect(() => writeScenarioPackage({ ...input, manifest: { ...input.manifest, members: [] } })).toThrow(ScenarioPackageError);

    const tooOld = (() => {
      try {
        verifyScenarioPackage(bytesOf(thin.file), { cliVersion: '0.1.0' });
      } catch (error) {
        return error as ScenarioPackageError;
      }
      return null;
    })();
    expect(tooOld?.code).toBe('package_version_unsupported');
    expect(tooOld?.dimensions.map((d) => d.dimension)).toEqual(['cli']);
    // A producer re-checking its own output does not evaluate minCli, and says so.
    expect(verifyScenarioPackage(bytesOf(thin.file), { cliVersion: null }).cliCheck).toBe('not-evaluated');
  });
});
