#!/usr/bin/env node
/**
 * Studio style literal ratchet.
 *
 *   node scripts/style/ratchet.mjs            report (exit 0)
 *   node scripts/style/ratchet.mjs --check    fail on any regression
 *   node scripts/style/ratchet.mjs --update   lower the baseline to today's counts
 *   node scripts/style/ratchet.mjs --json     machine-readable summary
 *
 * Every file under `packages/studio-ui/src` and `studio/app` that calls
 * `stylex.create` has a literal budget in `ratchet-baseline.json`: the number
 * of raw colour/space/type/stroke/shadow/z-index/motion literals and literal
 * `@media (min-width…)` breakpoints it holds (see `ratchet-lib.mjs`). A file
 * may go down, never up, and a file the baseline has never seen starts at
 * zero. The fix for a violation is a token, a recipe or a primitive
 * (docs/engineering/studio-style-guide.md), never a baseline edit.
 *
 * `--update` only ever lowers budgets; pass `--allow-increase` as well to
 * accept a rise, which a reviewer should see in the diff.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { analyzeRepository, baselineFrom, budgetOf, compareWithBaseline, summarize } from "./ratchet-lib.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");
const baselinePath = join(here, "ratchet-baseline.json");
const args = new Set(process.argv.slice(2));

const files = analyzeRepository(repoRoot);
const summary = summarize(files);
let baseline = {};
try {
  baseline = JSON.parse(readFileSync(baselinePath, "utf8")).files ?? {};
} catch (error) {
  if (error.code !== "ENOENT") throw error;
}

if (args.has("--update")) {
  const next = baselineFrom(files);
  if (!args.has("--allow-increase")) {
    for (const [file, budget] of Object.entries(next)) {
      const allowed = baseline[file] ?? 0;
      if (budget > allowed) next[file] = allowed;
    }
    for (const [file, budget] of Object.entries(next)) if (budget === 0) delete next[file];
  }
  const payload = {
    "//": "Per-file StyleX literal budgets. Generated by scripts/style/ratchet.mjs --update; budgets only go down.",
    total: Object.values(next).reduce((sum, value) => sum + value, 0),
    files: next,
  };
  writeFileSync(baselinePath, `${JSON.stringify(payload, null, 2)}\n`);
  process.stdout.write(`baseline: ${Object.keys(next).length} files, ${payload.total} literals\n`);
  process.exit(0);
}

const { violations, improvements } = compareWithBaseline(files, baseline);

if (args.has("--json")) {
  process.stdout.write(`${JSON.stringify({ summary, violations: violations.map(({ values, ...rest }) => rest), improvements }, null, 2)}\n`);
  process.exit(args.has("--check") && violations.length > 0 ? 1 : 0);
}

const out = [];
out.push(`StyleX files: ${summary.files}   literals: ${summary.literals}   token refs: ${summary.tokens}   literal share: ${summary.literalPct}% (core ${summary.coreLiteralPct}%)`);
out.push(`literal breakpoints: ${summary.media}   keyframes: ${summary.keyframes}   baseline total: ${Object.values(baseline).reduce((a, b) => a + b, 0)}`);
if (args.has("--verbose")) {
  const worst = [...files].sort((a, b) => budgetOf(b) - budgetOf(a)).slice(0, 15);
  out.push("", "largest budgets:");
  for (const file of worst) out.push(`  ${String(budgetOf(file)).padStart(5)}  ${file.file}`);
}
if (improvements.length > 0) {
  out.push("", `${improvements.length} file(s) below budget; run \`pnpm style:ratchet --update\` to lock the gain in.`);
}
if (violations.length > 0) {
  out.push("", `${violations.length} file(s) over budget:`);
  for (const violation of violations) {
    out.push(`  ${violation.file}: ${violation.actual} literal(s), budget ${violation.allowed}${violation.isNew ? " (new file)" : ""}`);
    for (const value of violation.values.slice(0, 12)) out.push(`      :${value.line}  ${value.prop ?? value.category}: ${JSON.stringify(value.value)}`);
  }
  out.push("", "Replace them with tokens, recipes or primitives: docs/engineering/studio-style-guide.md");
}
process.stdout.write(`${out.join("\n")}\n`);
process.exit(args.has("--check") && violations.length > 0 ? 1 : 0);
