import * as stylex from "@stylexjs/stylex";
import { colors, motion, space, stroke, text } from "@simforge-oss/studio-ui/stylex/tokens.stylex";
export const styles = stylex.create({
 root:{fontSize:text.sizeXs, lineHeight: text.lineXs}, empty:{paddingBlock: space.s2,fontSize:text.sizeXs, lineHeight: text.lineXs,fontStyle:"italic",color:"hsl(var(--muted-foreground) / 0.5)"}, nullValue:{fontStyle:"italic",color:"hsl(var(--muted-foreground) / 0.5)"}, bool:{display:"inline-flex",alignItems:"center",borderRadius: ".25rem",paddingInline: space.s1_5,paddingBlock:"1px",fontSize:"10px",fontWeight:text.weightMedium}, boolTrue:{backgroundColor:"rgba(34,197,94,.1)",color:"#22c55e"}, boolFalse:{backgroundColor:colors.muted,color:colors.mutedForeground}, mono:{fontFamily:text.fontMono,color:colors.text}, /** `text-foreground break-words` — body face, not the code face. */ plain:{color:colors.text,overflowWrap:"break-word"}, uuid:{fontFamily:text.fontMono,color:"hsl(var(--foreground) / 0.8)",wordBreak:"break-all",fontSize:"10px"}, inline:{display:"inline-flex",alignItems:"center",gap:space.s1}, action:{display:"inline-flex",width:"1rem",height:"1rem",alignItems:"center",justifyContent:"center",borderRadius:".25rem",color:"hsl(var(--muted-foreground) / 0.5)",transitionProperty:"color,background-color",transitionDuration:motion.durStandard,":hover":{color:"#38bdf8",backgroundColor:"rgba(56,189,248,.1)"}}, actionSelect:{":hover":{color:colors.primary,backgroundColor:colors.accentWash}}, row:{display:"flex",alignItems:"baseline",gap:space.s2,paddingBlock:space.s0_5}, label:{flexShrink:0,color:colors.mutedForeground}, labelXs:{flexShrink:0,color:colors.mutedForeground,fontSize:text.sizeXs, lineHeight: text.lineXs}, header:{display:"flex",width:"100%",alignItems:"baseline",gap:space.s1_5,borderRadius:".25rem",paddingBlock:space.s0_5,fontSize:text.sizeXs, lineHeight: text.lineXs,transitionProperty:"background-color",transitionDuration:motion.durStandard,":hover":{backgroundColor:"rgba(148,163,184,.3)"}}, chevron:{width:".75rem",height:".75rem",flexShrink:0,color:colors.mutedForeground,transitionProperty:"transform",transitionDuration:motion.durStandard,marginTop:space.s0_5}, chevronOpen:{transform:"rotate(90deg)"}, preview:{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",fontFamily:text.fontMono,fontSize:"10px",color:"hsl(var(--muted-foreground) / 0.6)"}, count:{fontFamily:text.fontMono,fontSize:"10px",color:"hsl(var(--muted-foreground) / 0.6)"}, divider:{borderTopWidth:stroke.hairline, borderTopStyle:"solid", borderTopColor:"hsl(var(--border) / 0.3)",marginBlock:space.s0_5}, more:{paddingBlock:space.s0_5,fontSize:"10px",color:colors.primary,transitionProperty:"color",transitionDuration:motion.durStandard,":hover":{color:"rgba(232,224,68,.8)"}},
  // size-3
  eyeIcon: {
    width: space.s3,
    height: space.s3,
  },
  // size-3
  locatefixedIcon: {
    width: space.s3,
    height: space.s3,
  },
});