import * as stylex from "@stylexjs/stylex";
import { colors, radii, space, text } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

const SM = "@media (min-width: 640px)";
const spin = stylex.keyframes({ from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } });
const focusRing = { ":focus-visible": { outline: "none", boxShadow: `0 0 0 2px ${colors.accent}` } };

export const setup = stylex.create({
  shell: { position: "relative", display: "grid", minHeight: "100%", placeItems: "center", overflow: "hidden", paddingInline: "1.25rem", paddingBlock: "2.5rem", [SM]: { padding: "2rem" } },
  content: { position: "relative", width: "100%", maxWidth: "38rem", padding: "1.5rem", color: "white", [SM]: { padding: "2.25rem" } },
  header: { display: "flex", alignItems: "flex-start", gap: space.xl },
  headerIcon: { display: "grid", width: "3rem", height: "3rem", flexShrink: 0, placeItems: "center", color: colors.accent },
  eyebrow: { fontFamily: text.fontMeta, fontSize: "0.625rem", fontWeight: text.weightBold, lineHeight: text.lineMicro, textTransform: "uppercase", letterSpacing: text.trackingMetaWider, color: colors.accent },
  title: { marginTop: space.xs, fontSize: text.size2xl, lineHeight: text.lineTight, fontWeight: text.weightSemibold },
  description: { marginTop: space.md, fontSize: text.sizeSm, lineHeight: "1.5rem", color: colors.textSubtle },
  selection: { marginTop: space.xxl, borderBlock: "1px solid rgba(255,255,255,0.1)", paddingBlock: space.xl },
  selectionHead: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: space.md },
  selectionLegend: { fontFamily: text.fontMeta, fontSize: "0.5625rem", fontWeight: text.weightBold, lineHeight: text.lineMicro, textTransform: "uppercase", letterSpacing: text.trackingMetaWide, color: colors.textFaint },
  selectionActions: { display: "flex", gap: space.md, fontSize: text.sizeMeta },
  actionButton: { border: 0, padding: 0, backgroundColor: "transparent", color: colors.textSubtle, cursor: "pointer", ...focusRing, ":hover": { color: colors.text } },
  actionPrimary: { color: colors.accent },
  mapGrid: { display: "grid", maxHeight: "10rem", gap: space.xs, marginTop: space.md, overflowY: "auto", [SM]: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" } },
  mapOption: { display: "flex", minWidth: 0, alignItems: "center", gap: space.md, borderRadius: radii.lg, paddingInline: space.md, paddingBlock: space.md, fontSize: text.sizeXs, color: "rgba(255,255,255,0.65)" },
  checkbox: { width: "0.875rem", height: "0.875rem", accentColor: colors.accent },
  truncate: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  notice: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: space.md, marginTop: space.xl, border: "1px solid rgba(255,255,255,0.1)", borderRadius: radii.xl, backgroundColor: "rgba(255,255,255,0.03)", paddingInline: space.xl, paddingBlock: space.lg },
  noticeIcon: { width: space.xl, height: space.xl, flexShrink: 0, color: colors.accent },
  noticeText: { minWidth: 0, flexGrow: 1, fontSize: text.sizeXs, lineHeight: "1.25rem", color: "rgba(255,255,255,0.55)" },
  error: { marginTop: space.md, fontSize: text.sizeXs, color: "rgba(252,211,77,0.9)" },
  preparation: { marginTop: "2rem" },
  errorBox: { marginTop: "1.25rem", border: "1px solid color-mix(in srgb, hsl(var(--destructive)) 40%, transparent)", backgroundColor: "color-mix(in srgb, hsl(var(--destructive)) 10%, transparent)", padding: space.lg, fontSize: text.sizeSm, color: colors.danger },
  footer: { display: "flex", flexDirection: "column", gap: space.md, marginTop: "2rem", [SM]: { flexDirection: "row" } },
  loader: { animationName: spin, animationDuration: "1s", animationTimingFunction: "linear", animationIterationCount: "infinite" },
  panel: { pointerEvents: "auto", maxWidth: "36rem", borderTop: "1px solid rgba(255,255,255,0.15)", paddingTop: space.lg },
  panelLabel: { fontFamily: text.fontMeta, fontSize: "0.5625rem", fontWeight: text.weightBold, lineHeight: text.lineMicro, textTransform: "uppercase", letterSpacing: "0.16em", color: colors.textFaint },
  locked: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: space.md, marginTop: space.md, border: "1px solid rgba(255,255,255,0.1)", borderRadius: radii.xl, backgroundColor: "rgba(0,0,0,0.35)", paddingInline: space.xl, paddingBlock: space.lg },
  lockedIcon: { width: space.xl, height: space.xl, flexShrink: 0, color: colors.accent },
  lockedText: { minWidth: 0, flexGrow: 1, fontSize: text.sizeXs, lineHeight: "1.25rem", color: "rgba(255,255,255,0.65)" },
  rows: { marginTop: space.sm, borderBlock: 0 },
  row: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: space.md, paddingBlock: space.md, borderBottom: "1px solid rgba(255,255,255,0.1)" },
  rowIcon: { display: "grid", width: "1.75rem", height: "1.75rem", flexShrink: 0, placeItems: "center", color: colors.accent },
  rowBody: { minWidth: 0, flexGrow: 1 },
  rowTitle: { display: "flex", alignItems: "center", gap: space.md, fontSize: text.sizeXs, lineHeight: text.lineNormal, fontWeight: text.weightSemibold, color: "rgba(255,255,255,0.85)" },
  pill: { border: "1px solid rgba(255,255,255,0.1)", borderRadius: radii.full, paddingInline: space.md, paddingBlock: "0.125rem", fontFamily: text.fontMeta, fontSize: "0.5rem", fontWeight: text.weightBold, lineHeight: text.lineMicro, textTransform: "uppercase", letterSpacing: "0.13em", color: "rgba(255,255,255,0.45)" },
  pillReady: { borderColor: "rgba(232,224,68,0.3)", backgroundColor: "rgba(232,224,68,0.1)", color: colors.accent },
  rowDetail: { marginTop: "0.125rem", fontSize: "0.6875rem", lineHeight: "1rem", color: "rgba(255,255,255,0.45)" },
  track: { height: "0.25rem", marginTop: space.sm, overflow: "hidden", borderRadius: radii.full, backgroundColor: "rgba(255,255,255,0.1)" },
  fill: { height: "100%", width: "var(--map-install-progress)", borderRadius: radii.full, backgroundColor: colors.accent, transitionProperty: "width", transitionDuration: "500ms" },
  alert: { width: "100%", fontSize: "0.6875rem", color: "rgba(252,211,77,0.9)" },
  spinIcon: { animationName: spin, animationDuration: "1s", animationTimingFunction: "linear", animationIterationCount: "infinite" },
  gate: { height: "100%", minHeight: 0 },
  gateHidden: { visibility: "hidden" },
  compactButton: { height: "2rem", display: "inline-flex", alignItems: "center", gap: space.sm, borderRadius: radii.full, borderColor: "rgba(232,224,68,0.3)", backgroundColor: "rgba(232,224,68,0.1)", paddingInline: space.lg, fontSize: "0.6875rem", color: colors.accent },
  primaryButton: { height: "3rem", flexGrow: 1, borderRadius: radii.full, backgroundColor: colors.accent, color: colors.accentText },
  secondaryButton: { height: "3rem", borderRadius: radii.full },
  iconSmall: { width: "0.875rem", height: "0.875rem" },
  iconWithMargin: { width: "1rem", height: "1rem", marginInlineEnd: space.sm },
});
