import * as stylex from "@stylexjs/stylex";
import { colors, layers, space, text } from "../../stylex/tokens.stylex";

export const styles = stylex.create({
  overlay: {
    pointerEvents: "auto",
    position: "fixed",
    inset: "0",
    zIndex: layers.popover,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingInline: space.xl,
  },
  backdrop: {
    position: "absolute",
    inset: "0",
    backgroundColor: "rgb(0 0 0 / 0.7)",
    backdropFilter: "blur(4px)",
  },
  dialog: {
    position: "relative",
    zIndex: layers.raised,
    width: "100%",
    maxWidth: "40rem",
    maxHeight: "85vh",
    overflowY: "auto",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.bg,
    padding: "1.25rem",
    boxShadow: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
  },
  title: {
    fontSize: text.sizeBase,
    lineHeight: "1.5rem",
    fontWeight: text.weightSemibold,
    color: colors.text,
  },
  intro: {
    marginTop: space.xs,
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    color: colors.mutedForeground,
  },
  label: {
    display: "block",
    marginTop: space.xl,
    fontFamily: text.fontMeta,
    fontSize: text.sizeMicro,
    lineHeight: text.lineMicro,
    textTransform: "uppercase",
    letterSpacing: text.trackingMetaWide,
    color: colors.mutedForeground,
  },
  select: {
    width: "100%",
    marginTop: space.sm,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.bg,
    paddingInline: space.lg,
    paddingBlock: space.md,
    fontSize: text.sizeSm,
    color: colors.text,
  },
  issuePanel: {
    marginTop: space.xl,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.danger,
    backgroundColor: "color-mix(in srgb, var(--destructive) 10%, transparent)",
    padding: space.lg,
    color: colors.danger,
    fontSize: text.sizeXs,
  },
  issueList: {
    marginTop: space.md,
    paddingLeft: space.xl,
  },
  issueCode: {
    fontFamily: text.fontMono,
    fontWeight: text.weightSemibold,
  },
  error: {
    marginTop: space.lg,
    fontSize: text.sizeXs,
  },
  actions: {
    marginTop: "1.25rem",
    display: "flex",
    justifyContent: "flex-end",
    gap: space.md,
  },
});
