import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  panel: {
    position: "fixed",
    right: 16,
    bottom: 16,
    zIndex: 11,
    width: "min(720px, calc(100vw - 32px))",
    color: "#e5e7eb",
    backgroundColor: "rgba(15, 20, 29, 0.96)",
    border: "1px solid #46505f",
    borderRadius: 8,
    fontSize: 12,
    pointerEvents: "auto",
  },
  expanded: { position: "relative", right: "auto", bottom: "auto", width: "calc(100% - 32px)", margin: "0 16px 16px", flexShrink: 0 },
  toggle: {
    display: "block",
    width: "100%",
    textAlign: "left",
    padding: "10px 14px",
    fontWeight: 600,
    letterSpacing: "0.08em",
    cursor: "pointer",
    color: "inherit",
    backgroundColor: "transparent",
    border: 0,
  },
  content: { padding: "0 14px 12px", maxHeight: "38vh", overflow: "auto" },
  toolbar: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12 },
  summary: { marginTop: 8, overflowWrap: "anywhere", lineHeight: 1.6 },
  coverage: { width: "100%", marginTop: 8, textAlign: "left", fontVariantNumeric: "tabular-nums", fontSize: 11 },
  json: {
    maxHeight: "28vh",
    overflow: "auto",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    marginTop: 8,
    fontSize: 11,
    lineHeight: 1.5,
    userSelect: "text",
  },
});
