import type { ExternalModelBinding } from './types';

/**
 * CARLA vehicle models, generated by `scripts/generate-vehicle-models.ts` from
 * `catalog/vehicles-carla` — do not edit by hand.
 *
 * Frame and slot contract: `catalog/vehicles-carla/CONVENTIONS.md` (y-up, +X
 * forward, origin at ground under the CARLA pivot; `body`/`wheel_*`/`door_*`
 * nodes; neutral `body_paint` paint slot, authored `body_livery` never
 * tinted). Ids absent here have no CARLA counterpart and keep their builder.
 */
export const CARLA_VEHICLE_MODELS = {
  /** Lincoln MKZ 2017 */
  'vehicle.sedan': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_sedan_lincoln_mkz.glb',
    contentHash: '7243955057e273733036bb03dc9a4ece7f059cf9c20842e44fbbb3acec760b32',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
      doors: { left: ['door_fl'], right: ['door_fr'], rear: ['door_rl', 'door_rr'] },
    },
    paint: 'body_paint',
  },
  /** Mini Cooper S 2021 */
  'vehicle.hatchback': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_hatchback_mini_cooper.glb',
    contentHash: 'f49ec6e4b9fdaee6fb9e0b490a1b511ff719aad4a11ddb1554fdcd1bd3bb38d0',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
      doors: { left: ['door_fl'], right: ['door_fr'] },
    },
    paint: 'body_paint',
  },
  /** Nissan Patrol 2021 */
  'vehicle.suv': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_suv_nissan_patrol.glb',
    contentHash: 'edce2506049352e26a073efbcdf490cf2042542265850095f7df7d73f1d88e8b',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
      doors: { left: ['door_fl'], right: ['door_fr'], rear: ['door_rl', 'door_rr'] },
    },
    paint: 'body_paint',
  },
  /** Tesla Cybertruck — the only CARLA pickup; authored livery, not tintable */
  'vehicle.pickup': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_pickup_tesla_cybertruck.glb',
    contentHash: 'de8452597568d1579e8b981d6be0ac8d731e5cc38ea83e7e346497462c5f999e',
  },
  /** Mercedes Sprinter */
  'vehicle.van': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_van_mercedes_sprinter.glb',
    contentHash: 'c8f91488d67a51e8fa298df4598558f84315d071e471e213fe5d7a137034f908',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
      doors: { left: ['door_fl'], right: ['door_fr'] },
    },
    paint: 'body_paint',
  },
  /** Mercedes Sprinter */
  'vehicle.delivery_van': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_van_mercedes_sprinter.glb',
    contentHash: 'c8f91488d67a51e8fa298df4598558f84315d071e471e213fe5d7a137034f908',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
      doors: { left: ['door_fl'], right: ['door_fr'] },
    },
    paint: 'body_paint',
  },
  /** Mercedes Sprinter — a 7.4 m shuttle is a long-wheelbase minibus; the Fuso Rosa is 10 m and would scale to 0.7 */
  'vehicle.shuttle_bus': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_van_mercedes_sprinter.glb',
    contentHash: 'c8f91488d67a51e8fa298df4598558f84315d071e471e213fe5d7a137034f908',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
      doors: { left: ['door_fl'], right: ['door_fr'] },
    },
    paint: 'body_paint',
  },
  /** BMW Gran Tourer */
  'vehicle.minivan': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_minivan_bmw_gran_tourer.glb',
    contentHash: '6733c345fef27f85888667c8cd6dac9f1ff037cbf40da0367710c22125a6abd7',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
    },
    paint: 'body_paint',
  },
  /** BMW Gran Tourer */
  'vehicle.kia.carnival': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_minivan_bmw_gran_tourer.glb',
    contentHash: '6733c345fef27f85888667c8cd6dac9f1ff037cbf40da0367710c22125a6abd7',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
    },
    paint: 'body_paint',
  },
  /** CarlaCola box truck */
  'vehicle.box_truck': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_truck_carlacola.glb',
    contentHash: 'ac1003559a0e299acd8242b50b98e91f9851ad3724d11977ec64b23d3f2a87f7',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
      doors: { left: ['door_fl'], right: ['door_fr'] },
    },
    paint: 'body_paint',
  },
  /** Mitsubishi Fuso Rosa — CARLA has one bus; its authored livery is its identity, so it is not tintable */
  'vehicle.bus': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_bus_mitsubishi_fusorosa.glb',
    contentHash: '4c2061dac9d7351796029f6e8b79b1cedbaec43de660a9c6d29d510f88300048',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
    },
  },
  /** Harley-Davidson Low Rider */
  'vehicle.motorcycle': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_motorcycle_harley.glb',
    contentHash: '3a62ab86449571a6399673657db2a5679729b0b253b2e59636c17b5ee20b3eb9',
    nodes: {
      wheelsFront: ['wheel_f'],
      wheelsRear: ['wheel_r'],
      steered: ['handlebar'],
    },
    paint: 'body_paint',
  },
  /** Gazelle Omafiets — upright city bike: the closest silhouette to the catalog box, and scales ~1 */
  'vehicle.bicycle': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_bicycle_gazelle_omafiets.glb',
    contentHash: '8c07c8fcee87fb3b0acf622cc790f92cfcd848d5b72269d757fe6b2d27d494a2',
    nodes: {
      wheelsFront: ['wheel_f'],
      wheelsRear: ['wheel_r'],
      steered: ['handlebar'],
    },
    paint: 'body_paint',
  },
  /** Ford Ambulance */
  'vehicle.ambulance': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_ambulance_ford.glb',
    contentHash: '64566ed8a709afd21c5e7d8ca089c509446633606eb562193cc1b92be74831d8',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
      doors: { left: ['door_fl'], right: ['door_fr'] },
    },
  },
  /** Mercedes Actros Firetruck */
  'vehicle.fire_engine': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_firetruck_actros.glb',
    contentHash: '741ee999b05a12283f25ea46f646c71dff2195a34a936cfb9a716b4045c70c1d',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
      doors: { left: ['door_fl'], right: ['door_fr'] },
    },
  },
  /** Dodge Charger 2020 */
  'vehicle.honda_civic': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_sedan_dodge_charger.glb',
    contentHash: '68d993ff00d645564b349011eacfd1fec09d69f7a78f4e771f10538a6a7ce24e',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
      doors: { left: ['door_fl'], right: ['door_fr'], rear: ['door_rl', 'door_rr'] },
    },
    paint: 'body_paint',
  },
  /** Chevrolet Impala — a second rigged sedan, so Camry and Sedan are not the same model on screen */
  'vehicle.toyota_camry': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_sedan_chevrolet_impala.glb',
    contentHash: '46f70ab9110425a0dbcecc341b81fc491feeb3d7f802aa36df57d0fdc12ad491',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
    },
    paint: 'body_paint',
  },
  /** Tesla Model 3 — exact vehicle; CARLA ships it as a static mesh, so no wheel rig */
  'vehicle.tesla_model_3': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_sedan_tesla_model3.glb',
    contentHash: 'f4906b8afc82a69d95132146ced52aa960c6cfe4c502929a3a6283318ce2722b',
  },
  /** Ford Mustang */
  'vehicle.ford_mustang': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_coupe_ford_mustang.glb',
    contentHash: 'f4cc002c88e2126affeb7dd960bfc8aac34867e28841560014034a6136f0d937',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
    },
    paint: 'body_paint',
  },
  /** Audi TT — low sports coupe proportions */
  'vehicle.chevrolet_corvette': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_coupe_audi_tt.glb',
    contentHash: '2859e7ae360be1996e199acb8a38e2e5c131bdc27055cb5c7e467904f1f386a5',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
    },
    paint: 'body_paint',
  },
  /** Jeep Wrangler Rubicon — the same vehicle; CARLA models the short-wheelbase two-door */
  'vehicle.jeep_wrangler': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_suv_jeep_wrangler.glb',
    contentHash: '897ad79a7bb413a3d604d19afa4cbadc40ded774656be4dd8c3c0155a916fa86',
    paint: 'body_paint',
  },
  /** Ford Crown (taxi) — authored taxi livery */
  'vehicle.taxi': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_sedan_ford_crown.glb',
    contentHash: '2b0c17f12d850f91101cc5c0cade1e5cd3c21204a43c54c4dbea91f9931e08a9',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
      doors: { left: ['door_fl'], right: ['door_fr'], rear: ['door_rl', 'door_rr'] },
    },
  },
  /** Dodge Charger Police 2020 — authored police livery */
  'vehicle.police_cruiser': {
    kind: 'glb',
    url: '/catalog/vehicles-carla/models/vehicle_police_dodge_charger.glb',
    contentHash: '2d37575da0af3e815b41581a5b47d48440a2938bda5e75462c6cae76c5cfde89',
    nodes: {
      wheelsFront: ['wheel_fl', 'wheel_fr'],
      wheelsRear: ['wheel_rl', 'wheel_rr'],
      doors: { left: ['door_fl'], right: ['door_fr'], rear: ['door_rl', 'door_rr'] },
    },
  },
} as const satisfies Readonly<Record<string, ExternalModelBinding>>;
