import * as stylex from "@stylexjs/stylex";
import { text } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

const SM = "@media (min-width: 640px)";
const ACCENT = "#E8E044";
const SURFACE = "rgba(255,255,255,0.025)";
const spin = stylex.keyframes({ from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } });

export const dialog = stylex.create({
  overlay: { position: "fixed", inset: 0, zIndex: 200, backgroundColor: "rgba(0,0,0,0.75)", backdropFilter: "blur(8px)" },
  content: { position: "fixed", left: "50%", top: "50%", zIndex: 210, width: "min(760px, calc(100vw - 2rem))", maxHeight: "92vh", transform: "translate(-50%, -50%)", overflowY: "auto", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "1rem", backgroundColor: "#0d1014", padding: "1.5rem", color: "#fff", boxShadow: "0 25px 50px -12px rgba(0,0,0,0.5)", outline: "none" },
  title: { display: "flex", alignItems: "center", gap: "0.5rem", fontSize: "1.5rem", lineHeight: "2rem", fontWeight: 600, letterSpacing: "-0.025em" },
  description: { marginTop: "0.25rem", fontSize: text.sizeSm, color: "rgba(255,255,255,0.45)" },
  close: { position: "absolute", right: "1rem", top: "1rem", borderRadius: "0.375rem", padding: "0.5rem", color: "rgba(255,255,255,0.45)", ":hover": { backgroundColor: "rgba(255,255,255,0.05)", color: "#fff" }, ":disabled": { opacity: 0.4 } },
  form: { marginTop: "1.5rem", display: "flex", flexDirection: "column", gap: "1.25rem" },
  grid: { display: "grid", gap: "1rem", [SM]: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" } },
  span2: { [SM]: { gridColumn: "span 2" } },
  footer: { marginTop: "1.25rem", display: "flex", flexDirection: "column", gap: "1.25rem" },
  actions: { display: "flex", justifyContent: "flex-end", gap: "0.5rem" },
  progressText: { marginBottom: "0.25rem", display: "flex", justifyContent: "space-between", fontSize: text.sizeXs, color: "rgba(255,255,255,0.45)" },
  progress: { height: "0.375rem", overflow: "hidden", borderRadius: "9999px", backgroundColor: "rgba(255,255,255,0.07)" },
  progressBar: { height: "100%", backgroundColor: ACCENT, transitionProperty: "width", transitionDuration: "150ms" },
  progressPulse: { animationName: spin, animationDuration: "1s", animationIterationCount: "infinite" },
  drop: { display: "flex", minHeight: "8rem", width: "100%", flexDirection: "column", alignItems: "center", justifyContent: "center", border: "1px dashed rgba(255,255,255,0.15)", borderRadius: "0.75rem", backgroundColor: SURFACE, paddingInline: "1.5rem", textAlign: "center", transitionProperty: "border-color, background-color", transitionDuration: "150ms", ":hover": { borderColor: "rgba(232,224,68,0.4)", backgroundColor: "rgba(232,224,68,0.03)" }, ":focus-visible": { outline: "none", boxShadow: `0 0 0 2px ${ACCENT}` } },
  accentIcon: { marginBottom: "0.75rem", width: "1.5rem", height: "1.5rem", color: ACCENT },
  panel: { marginTop: "1.5rem", display: "flex", flexDirection: "column", gap: "1.25rem" },
  card: { border: "1px solid rgba(255,255,255,0.1)", borderRadius: "0.75rem", backgroundColor: SURFACE, padding: "1rem" },
  image: { aspectRatio: "1", width: "100%", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "0.75rem", background: "radial-gradient(circle,#27303a,#101317)", objectFit: "contain" },
  muted: { fontSize: text.sizeXs, color: "rgba(255,255,255,0.4)" },
  label: { fontSize: text.sizeXs, color: "rgba(255,255,255,0.45)" },
  error: { fontSize: text.sizeSm, color: "#fca5a5" },
  tabGroup: { display: "flex", width: "fit-content", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "0.375rem", backgroundColor: SURFACE, padding: "0.25rem" },
  tab: { display: "flex", alignItems: "center", gap: "0.375rem", borderRadius: "0.25rem", paddingInline: "1rem", paddingBlock: "0.375rem", fontSize: text.sizeXs, color: "rgba(255,255,255,0.4)", ":hover": { color: "#fff" }, ":disabled": { opacity: 0.4 } },
  tabActive: { backgroundColor: "rgba(255,255,255,0.1)", color: "#fff" },
  tableWrap: { overflow: "hidden", border: "1px solid rgba(255,255,255,0.08)", borderRadius: "0.75rem", backgroundColor: "rgba(255,255,255,0.02)" },
  tableTools: { display: "flex", flexDirection: "column", gap: "0.5rem", [SM]: { flexDirection: "row" } },
  stat: { border: "1px solid rgba(255,255,255,0.07)", borderRadius: "0.5rem", backgroundColor: "rgba(255,255,255,0.03)", padding: "0.75rem" },
  toolbar: { display: "flex", minWidth: 0, maxWidth: "1500px", marginInline: "auto", alignItems: "center", gap: "0.75rem", borderBottom: 0, backgroundColor: "transparent", paddingInline: 0 },
  icon: { width: "1rem", height: "1rem" },
  iconSm: { width: "0.875rem", height: "0.875rem" },
  iconAccent: { width: "1.5rem", height: "1.5rem", color: ACCENT },
  loadingPreview: { display: "grid", height: "18rem", placeItems: "center", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "0.75rem", backgroundColor: "rgba(255,255,255,0.025)", fontSize: text.sizeXs, color: "rgba(255,255,255,0.45)" },
  drawerTitle: { paddingRight: "2rem", fontSize: "1.5rem" },
  statTile: { border: "1px solid rgba(255,255,255,0.1)", borderRadius: "0.5rem", backgroundColor: "rgba(255,255,255,0.03)", padding: "0.75rem" },
  statLabel: { fontSize: "10px", textTransform: "uppercase", letterSpacing: "0.05em", color: "rgba(255,255,255,0.35)" },
  statValue: { marginTop: "0.25rem", fontSize: text.sizeSm, fontVariantNumeric: "tabular-nums" },
  mutedText: { fontSize: text.sizeXs, color: "rgba(255,255,255,0.4)" },
  bodyText: { fontSize: text.sizeSm, lineHeight: "1.5rem", color: "rgba(255,255,255,0.8)" },
  tagList: { display: "flex", flexWrap: "wrap", gap: "0.375rem" },
  tag: { border: "1px solid rgba(255,255,255,0.1)", borderRadius: "9999px", paddingInline: "0.625rem", paddingBlock: "0.25rem", fontSize: text.sizeXs, color: "rgba(255,255,255,0.45)" },
  sectionHeading: { fontSize: text.sizeXs, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.05em", color: "rgba(255,255,255,0.45)" },
  list: { marginTop: "0.5rem", display: "flex", flexDirection: "column", gap: "0.25rem", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "0.5rem", padding: "0.75rem", fontSize: text.sizeSm },
  listRow: { display: "flex", justifyContent: "space-between", gap: "0.75rem" },
  mono: { overflowWrap: "anywhere", borderRadius: "0.5rem", backgroundColor: "rgba(0,0,0,0.3)", paddingInline: "0.75rem", paddingBlock: "0.5rem", fontFamily: "monospace", fontSize: text.sizeXs, color: "rgba(255,255,255,0.6)" },
  fieldLabel: { fontSize: text.sizeXs, color: "rgba(255,255,255,0.45)" },
  fieldControl: { marginTop: "0.25rem" },
  row: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: "0.5rem" },
  actionsRow: { display: "flex", justifyContent: "flex-end", gap: "0.5rem" },
  preview: { aspectRatio: "1", width: "100%", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "0.75rem", background: "radial-gradient(circle,#27303a,#101317)", objectFit: "contain" },
  uploadDrop: { minHeight: "8rem" },
  stack: { display: "flex", flexDirection: "column", gap: "0.75rem" },
  grid2: { display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: "0.75rem" },
  errorText: { fontSize: text.sizeSm, color: "#fca5a5" },
  recent: { marginTop: "1.25rem", border: "1px solid rgba(232,224,68,0.2)", borderRadius: "0.75rem", backgroundColor: "rgba(232,224,68,0.04)", padding: "1rem" },
  recentList: { marginTop: "0.5rem", display: "flex", flexDirection: "column", gap: "0.5rem" },
  recentItem: { display: "flex", width: "100%", alignItems: "center", justifyContent: "space-between", borderRadius: "0.5rem", backgroundColor: "rgba(255,255,255,0.04)", paddingInline: "0.75rem", paddingBlock: "0.5rem", textAlign: "left", fontSize: text.sizeSm, ":hover": { backgroundColor: "rgba(255,255,255,0.07)" } },
  accentText: { color: ACCENT },
  subText: { marginTop: "0.25rem", display: "block", fontSize: "11px", lineHeight: "1rem", color: "rgba(255,255,255,0.35)" },
  cardSuccess: { border: "1px solid rgba(52,211,153,0.2)", borderRadius: "0.75rem", backgroundColor: "rgba(52,211,153,0.06)", padding: "1rem" },
  cardWarning: { border: "1px solid rgba(252,211,77,0.25)", borderRadius: "0.75rem", backgroundColor: "rgba(252,211,77,0.05)", padding: "1rem" },
  tableCell: { padding: "0.75rem" },
  tableEmpty: { paddingInline: "1rem", paddingBlock: "2.5rem", textAlign: "center", fontSize: text.sizeSm, color: "rgba(255,255,255,0.35)" },
  searchIcon: { pointerEvents: "none", position: "absolute", left: "0.75rem", top: "50%", width: "1rem", height: "1rem", transform: "translateY(-50%)", color: "rgba(255,255,255,0.45)" },
  clearButton: { position: "absolute", right: "0.5rem", top: "50%", display: "grid", width: "1.5rem", height: "1.5rem", placeItems: "center", transform: "translateY(-50%)", borderRadius: "0.25rem", color: "rgba(255,255,255,0.45)", ":hover": { color: "#fff" } },
  toolbarCount: { flexShrink: 0, fontSize: text.sizeXs, color: "rgba(255,255,255,0.45)" },
  tableToolsWide: { display: "flex", flexDirection: "column", gap: "0.5rem", [SM]: { flexDirection: "row" } },
  table: { width: "100%", fontSize: text.sizeSm },
  cellMuted: { color: "rgba(255,255,255,0.45)" },
  cellStrong: { fontWeight: 500 },
  srOnly: { position: "absolute", width: "1px", height: "1px", padding: 0, margin: "-1px", overflow: "hidden", clip: "rect(0,0,0,0)", whiteSpace: "nowrap", border: 0 },
  titleText: { fontWeight: 500 },
  searchWrap: { position: "relative", minWidth: 0, flex: 1 },
  generateCard: { border: "1px solid rgba(232,224,68,0.2)", borderRadius: "0.75rem", backgroundColor: "rgba(232,224,68,0.03)", padding: "1rem" },
  generateHeading: { fontSize: "10px", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.18em", color: ACCENT },
  generateText: { marginTop: "0.375rem", fontSize: text.sizeXs, lineHeight: "1.25rem", color: "rgba(255,255,255,0.5)" },
  artifactList: { marginTop: "0.75rem", display: "flex", flexDirection: "column", gap: "0.375rem" },
  artifactItem: { display: "flex", alignItems: "flex-start", gap: "0.5rem", fontSize: text.sizeXs, lineHeight: "1.25rem", color: "rgba(255,255,255,0.5)" },
  artifactDot: { marginTop: "0.5rem", width: "0.25rem", height: "0.25rem", flexShrink: 0, borderRadius: "9999px", backgroundColor: "rgba(232,224,68,0.6)" },
  toolbarGroup: { marginLeft: "auto" },
  toolbarCountValue: { fontVariantNumeric: "tabular-nums", color: "#fff" },
  iconButton: { width: "0.875rem", height: "0.875rem" },
  toolbarSelect: { height: "2.25rem", fontSize: text.sizeXs },
  toolbarActor: { width: "12rem" },
  toolbarCarla: { width: "10rem" },
  toolbarSort: { height: "2.25rem", display: "inline-flex", alignItems: "center", gap: "0.375rem", fontSize: text.sizeXs },
  detailSheet: { width: "100%", overflowY: "auto", borderColor: "hsl(var(--border))", backgroundColor: "hsl(var(--background))", [SM]: { maxWidth: "36rem" } },
  renameForm: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: "0.5rem" },
  inputCompact: { height: "2.25rem", minWidth: 0, flex: 1 },
  buttonCompact: { height: "2.25rem" },
  deleteBox: { border: "1px solid hsl(var(--destructive) / 0.5)", borderRadius: "0.5rem", backgroundColor: "hsl(var(--destructive) / 0.1)", padding: "0.75rem" },
  deleteHeading: { fontSize: text.sizeSm, fontWeight: 600 },
  usageLoading: { marginTop: "0.5rem", display: "inline-flex", alignItems: "center", gap: "0.375rem", fontSize: text.sizeXs, color: "hsl(var(--muted-foreground))" },
  usageIcon: { width: "0.75rem", height: "0.75rem" },
  usageWarning: { marginTop: "0.5rem", display: "inline-flex", alignItems: "center", gap: "0.5rem", border: "1px solid hsl(var(--primary) / 0.4)", borderRadius: "0.375rem", backgroundColor: "hsl(var(--primary) / 0.1)", paddingInline: "0.625rem", paddingBlock: "0.375rem", fontSize: text.sizeSm, fontWeight: 600, color: "hsl(var(--primary))" },
  usageWarningIcon: { width: "1rem", height: "1rem" },
  usageNote: { marginTop: "0.5rem", fontSize: text.sizeXs, color: "hsl(var(--muted-foreground))" },
  deleteActions: { marginTop: "0.75rem", display: "flex", flexWrap: "wrap", gap: "0.5rem" },
  errorDanger: { fontSize: text.sizeSm, color: "#fca5a5" },
  uploadPreviewGrid: { display: "grid", gap: "1.25rem", [SM]: { gridTemplateColumns: "240px minmax(0, 1fr)" } },
  uploadControls: { display: "flex", flexDirection: "column", gap: "0.75rem" },
  uploadGrid2: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "0.75rem" },
  uploadGrid: { display: "grid", gap: "1rem", [SM]: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" } },
  uploadSpan2: { [SM]: { gridColumn: "span 2" } },
  uploadRow: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: "0.5rem" },
  uploadBottom: { marginTop: "1.25rem", display: "flex", flexDirection: "column", gap: "1.25rem" },
  uploadStatus: { marginBottom: "0.25rem", display: "flex", justifyContent: "space-between", fontSize: text.sizeXs, color: "rgba(255,255,255,0.45)" },
  uploadBar: { height: "0.375rem", overflow: "hidden", borderRadius: "9999px", backgroundColor: "rgba(255,255,255,0.07)" },
  uploadBarFill: { height: "100%", backgroundColor: ACCENT, transitionProperty: "width", transitionDuration: "150ms" },
  uploadText: { fontSize: text.sizeSm, color: "#fca5a5" },
  uploadActions: { display: "flex", justifyContent: "flex-end", gap: "0.5rem" },
  uploadDropLabel: { fontSize: text.sizeSm, fontWeight: 500 },
  uploadImage: { aspectRatio: "1", width: "100%", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "0.75rem", background: "radial-gradient(circle,#27303a,#101317)", objectFit: "contain" },
  uploadMeta: { marginTop: "0.5rem", fontSize: text.sizeXs, color: "rgba(255,255,255,0.4)" },
  uploadLabel: { fontSize: text.sizeXs, color: "rgba(255,255,255,0.45)" },
  uploadField: { marginTop: "0.25rem" },
  motionOption: { border: "1px solid rgba(255,255,255,0.12)", borderRadius: "0.5rem", backgroundColor: "rgba(255,255,255,0.03)", padding: "0.75rem", textAlign: "left", ":hover": { backgroundColor: "rgba(255,255,255,0.06)" } },
  motionOptionActive: { borderColor: "rgba(232,224,68,0.6)", backgroundColor: "rgba(232,224,68,0.1)" },
  motionTitle: { display: "block", fontSize: text.sizeSm, color: "#fff" },
  motionDescription: { marginTop: "0.125rem", display: "block", fontSize: text.sizeXs, lineHeight: "1.25rem", color: "rgba(255,255,255,0.55)" },
  warningText: { fontSize: text.sizeXs, color: "rgba(254,215,170,0.7)" },
  clipsTitle: { fontSize: text.sizeXs, color: "rgba(255,255,255,0.45)" },
  clipsText: { marginTop: "0.25rem", fontSize: text.sizeSm, color: "rgba(255,255,255,0.7)" },
  successText: { fontSize: text.sizeSm, color: "#d1fae5" },
  uploadFullButton: { width: "100%", borderColor: "rgba(255,255,255,0.1)", backgroundColor: "transparent" },
  uploadTransparent: { borderColor: "rgba(255,255,255,0.1)", backgroundColor: "transparent" },
  autoSize: { borderColor: "rgba(232,224,68,0.4)", backgroundColor: "transparent", color: "#E8E044", ":hover": { backgroundColor: "rgba(232,224,68,0.1)" } },
  uploadMotionGrid: { display: "grid", gap: "0.5rem", [SM]: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" } },
});

export const drawer = stylex.create({
  root: { display: "flex", flexDirection: "column", gap: "1.5rem" },
  stats: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "0.75rem", fontSize: text.sizeSm },
  tile: { border: "1px solid rgba(255,255,255,0.1)", borderRadius: "0.5rem", backgroundColor: "rgba(255,255,255,0.03)", padding: "0.75rem" },
  eyebrow: { fontSize: "10px", textTransform: "uppercase", letterSpacing: "0.05em", color: "rgba(255,255,255,0.4)" },
  value: { marginTop: "0.25rem", fontVariantNumeric: "tabular-nums" },
  actions: { display: "flex", flexWrap: "wrap", gap: "0.5rem" },
  section: { display: "flex", flexDirection: "column", gap: "0.75rem" },
});