import * as stylex from "@stylexjs/stylex";
import { text } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

const SM = "@media (min-width: 640px)";
const ACCENT = "#E8E044";
const SURFACE = "rgba(255,255,255,0.025)";
const spin = stylex.keyframes({ from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } });

export const dialog = stylex.create({
  overlay: { position: "fixed", inset: 0, zIndex: 200, backgroundColor: "rgba(0,0,0,0.75)", backdropFilter: "blur(8px)" },
  // `outline-none` is Tailwind's transparent 2px outline, not `outline: none`,
  // so forced-colours mode still has an outline to repaint.
  content: { position: "fixed", left: "50%", top: "50%", zIndex: 210, width: "min(760px, calc(100vw - 2rem))", maxHeight: "92vh", transform: "translate(-50%, -50%)", overflowY: "auto", borderWidth: "1px", borderStyle: "solid", borderColor: "rgba(255,255,255,0.1)", borderRadius: "1rem", backgroundColor: "#0d1014", padding: "1.5rem", color: "#fff", boxShadow: "0 25px 50px -12px rgba(0,0,0,0.5)", outlineWidth: "2px", outlineStyle: "solid", outlineColor: "transparent", outlineOffset: "2px" },
  title: { display: "flex", alignItems: "center", gap: "0.5rem", fontSize: "1.5rem", lineHeight: "2rem", fontWeight: 600, letterSpacing: "-0.025em" },
  description: { marginTop: "0.25rem", fontSize: text.sizeSm, lineHeight: "1.25rem", color: "rgba(255,255,255,0.45)" },
  close: { position: "absolute", right: "1rem", top: "1rem", borderRadius: "0.375rem", padding: "0.5rem", color: "rgba(255,255,255,0.45)", ":hover": { backgroundColor: "rgba(255,255,255,0.05)", color: "#fff" }, ":disabled": { opacity: 0.4 } },
  form: { marginTop: "1.5rem", display: "flex", flexDirection: "column", gap: "1.25rem" },
  grid: { display: "grid", gap: "1rem", [SM]: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" } },
  span2: { [SM]: { gridColumn: "span 2" } },
  footer: { marginTop: "1.25rem", display: "flex", flexDirection: "column", gap: "1.25rem" },
  progressText: { marginBottom: "0.25rem", display: "flex", justifyContent: "space-between", fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.45)" },
  progress: { height: "0.375rem", overflow: "hidden", borderRadius: "9999px", backgroundColor: "rgba(255,255,255,0.07)" },
  progressBar: { height: "100%", backgroundColor: ACCENT, transitionProperty: "width", transitionDuration: "150ms" },
  progressPulse: { animationName: spin, animationDuration: "1s", animationTimingFunction: "linear", animationIterationCount: "infinite" },
  drop: { display: "flex", minHeight: "8rem", width: "100%", flexDirection: "column", alignItems: "center", justifyContent: "center", borderWidth: "1px", borderStyle: "dashed", borderColor: "rgba(255,255,255,0.15)", borderRadius: "0.75rem", backgroundColor: SURFACE, paddingInline: "1.5rem", textAlign: "center", transitionProperty: "border-color, background-color", transitionDuration: "150ms", ":hover": { borderColor: "rgba(232,224,68,0.4)", backgroundColor: "rgba(232,224,68,0.03)" }, ":focus-visible": { outlineWidth: "2px", outlineStyle: "solid", outlineColor: "transparent", outlineOffset: "2px", boxShadow: `0 0 0 2px ${ACCENT}` } },
  panel: { marginTop: "1.5rem", display: "flex", flexDirection: "column", gap: "1.25rem" },
  card: { borderWidth: "1px", borderStyle: "solid", borderColor: "rgba(255,255,255,0.1)", borderRadius: "0.75rem", backgroundColor: SURFACE, padding: "1rem" },
  tabGroup: { marginTop: "1.25rem", display: "flex", width: "fit-content", borderWidth: "1px", borderStyle: "solid", borderColor: "rgba(255,255,255,0.1)", borderRadius: "0.375rem", backgroundColor: SURFACE, padding: "0.25rem" },
  tab: { display: "flex", alignItems: "center", gap: "0.375rem", borderRadius: "0.25rem", paddingInline: "1rem", paddingBlock: "0.375rem", fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.4)", ":hover": { color: "#fff" }, ":disabled": { opacity: 0.4 } },
  tabActive: { backgroundColor: "rgba(255,255,255,0.1)", color: "#fff" },
  stat: { borderWidth: "1px", borderStyle: "solid", borderColor: "rgba(255,255,255,0.07)", borderRadius: "0.5rem", backgroundColor: "rgba(255,255,255,0.03)", padding: "0.75rem" },
  // Only the four utilities the gallery toolbar layered on the primitive:
  // `mx-auto max-w-[1500px] border-b-0 bg-transparent px-0 sm:px-0`. Layout
  // (flex, wrap, centring, gap) stays the primitive's.
  toolbar: { maxWidth: "1500px", marginInline: "auto", borderBottomWidth: 0, backgroundColor: "transparent", paddingInline: 0 },
  icon: { width: "1rem", height: "1rem" },
  iconSm: { width: "0.875rem", height: "0.875rem" },
  iconAccent: { marginBottom: "0.75rem", width: "1.5rem", height: "1.5rem", color: ACCENT },
  // The two "loading preview" boxes are unrelated: the drawer's is a bordered
  // 18rem card on the theme tokens, the generate dialog's is a bare 16/7 slot.
  drawerPreviewLoading: { display: "grid", height: "18rem", placeItems: "center", borderWidth: "1px", borderStyle: "solid", borderColor: "hsl(var(--border))", borderRadius: "0.75rem", backgroundColor: "hsl(var(--card))", fontSize: text.sizeXs, lineHeight: "1rem", color: "hsl(var(--muted-foreground))" },
  generatePreviewLoading: { display: "flex", aspectRatio: "16 / 7", alignItems: "center", justifyContent: "center", color: "rgba(255,255,255,0.3)" },
  previewSpinner: { marginRight: "0.5rem", width: "1.25rem", height: "1.25rem" },
  drawerTitle: { paddingRight: "2rem", fontSize: "1.5rem", lineHeight: "2rem" },
  statLabel: { fontSize: "10px", textTransform: "uppercase", letterSpacing: "0.05em", color: "rgba(255,255,255,0.35)" },
  statValue: { marginTop: "0.25rem", fontSize: text.sizeSm, lineHeight: "1.25rem", fontVariantNumeric: "tabular-nums" },
  // `grid gap-5 md:grid-cols-[240px_1fr]` — the preflight summary only, at the
  // md breakpoint and with a literal first track.
  preflightGrid: { display: "grid", gap: "1.25rem", "@media (min-width: 768px)": { gridTemplateColumns: "240px 1fr" } },
  statText: { marginTop: "0.25rem", fontSize: text.sizeSm, lineHeight: "1.25rem", color: "rgba(255,255,255,0.7)" },
  mutedTextMt2: { marginTop: "0.5rem", fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.4)" },
  helpText: { marginTop: "0.375rem", fontSize: text.sizeXs, lineHeight: "1.25rem", color: "rgba(255,255,255,0.4)" },
  faintText: { fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.35)" },
  alignEndRow: { display: "flex", alignItems: "flex-end" },
  uploadLabelMb: { marginBottom: "0.25rem", fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.45)" },
  padOnly: { padding: "1rem" },
  mutedTextMt1: { marginTop: "0.25rem", fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.4)" },
  hintMt2: { marginTop: "0.5rem", fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.35)" },
  noteMt1: { marginTop: "0.25rem", fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.55)" },
  noteMt2: { marginTop: "0.5rem", fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.55)" },
  dlXs: { display: "flex", flexDirection: "column", gap: "0.5rem", fontSize: text.sizeXs, lineHeight: "1rem" },
  dlLabel: { color: "rgba(255,255,255,0.35)" },
  truncate: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  // Drawer copy runs on the theme tokens; the upload/generate dialogs are
  // deliberately on white alphas, so these do not share a key.
  drawerNote: { fontSize: text.sizeXs, lineHeight: "1.25rem", color: "hsl(var(--muted-foreground))" },
  drawerClipTag: { fontSize: text.sizeXs, lineHeight: "1rem", color: "hsl(var(--muted-foreground))" },
  drawerBody: { fontSize: text.sizeSm, lineHeight: "1.5rem", color: "hsl(var(--foreground) / 0.8)" },
  drawerBodyMuted: { marginTop: "0.5rem", fontSize: text.sizeSm, lineHeight: "1.25rem", color: "hsl(var(--muted-foreground))" },
  uploadLocality: { marginTop: "0.25rem", display: "flex", alignItems: "center", gap: "0.375rem", fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.45)" },
  uploadWarnTitle: { fontSize: text.sizeSm, lineHeight: "1.25rem", fontWeight: 600, color: "#fef3c7" },
  uploadWarnNote: { marginTop: "0.25rem", fontSize: text.sizeXs, lineHeight: "1.25rem", color: "rgba(254,243,199,0.7)" },
  tagList: { display: "flex", flexWrap: "wrap", gap: "0.375rem" },
  tag: { borderWidth: "1px", borderStyle: "solid", borderColor: "hsl(var(--border))", borderRadius: "9999px", paddingInline: "0.625rem", paddingBlock: "0.25rem", fontSize: text.sizeXs, lineHeight: "1rem", color: "hsl(var(--muted-foreground))" },
  sectionHeading: { fontSize: text.sizeXs, lineHeight: "1rem", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.05em", color: "hsl(var(--muted-foreground))" },
  clipList: { marginTop: "0.5rem", display: "flex", flexDirection: "column", gap: "0.25rem", borderWidth: "1px", borderStyle: "solid", borderColor: "hsl(var(--border))", borderRadius: "0.5rem", padding: "0.75rem", fontSize: text.sizeSm, lineHeight: "1.25rem" },
  // `divide-y divide-white/[0.06]` moved onto the rows; the layer list has no
  // padding or row gap of its own, unlike the drawer's clip list.
  layerList: { marginTop: "0.5rem", borderWidth: "1px", borderStyle: "solid", borderColor: "rgba(255,255,255,0.07)", borderRadius: "0.5rem" },
  layerRow: { display: "flex", alignItems: "center", gap: "0.5rem", paddingInline: "0.75rem", paddingBlock: "0.5rem", fontSize: text.sizeSm, lineHeight: "1.25rem", borderTopWidth: "1px", borderTopStyle: "solid", borderTopColor: "rgba(255,255,255,0.06)", ":first-child": { borderTopWidth: 0 } },
  layerId: { flexShrink: 0 },
  layerFile: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontFamily: text.fontMono, fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.3)" },
  layerMeta: { marginLeft: "auto", flexShrink: 0, fontVariantNumeric: "tabular-nums", fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.4)" },
  listRow: { display: "flex", justifyContent: "space-between", gap: "0.75rem" },
  drawerMono: { wordBreak: "break-all", borderRadius: "0.5rem", backgroundColor: "hsl(var(--muted) / 0.4)", paddingInline: "0.75rem", paddingBlock: "0.5rem", fontFamily: text.fontMono, fontSize: text.sizeXs, lineHeight: "1rem", color: "hsl(var(--muted-foreground))" },
  uploadMono: { marginTop: "0.25rem", wordBreak: "break-all", borderRadius: "0.5rem", backgroundColor: "rgba(0,0,0,0.3)", paddingInline: "0.75rem", paddingBlock: "0.5rem", fontFamily: text.fontMono, color: "rgba(255,255,255,0.6)" },
  fieldLabel: { fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.45)" },
  fieldControl: { marginTop: "0.25rem" },
  actionsRow: { display: "flex", justifyContent: "flex-end", gap: "0.5rem" },
  preview: { aspectRatio: "1", width: "100%", borderWidth: "1px", borderStyle: "solid", borderColor: "rgba(255,255,255,0.1)", borderRadius: "0.75rem", backgroundImage: "radial-gradient(circle,#27303a,#101317)", objectFit: "contain" },
  stack: { display: "flex", flexDirection: "column", gap: "0.75rem" },
  grid2: { display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: "0.75rem" },
  errorText: { fontSize: text.sizeSm, lineHeight: "1.25rem", color: "#fca5a5" },
  recent: { marginTop: "1.25rem", borderWidth: "1px", borderStyle: "solid", borderColor: "rgba(232,224,68,0.2)", borderRadius: "0.75rem", backgroundColor: "rgba(232,224,68,0.04)", padding: "1rem" },
  recentList: { marginTop: "0.5rem", display: "flex", flexDirection: "column", gap: "0.5rem" },
  recentItem: { display: "flex", width: "100%", alignItems: "center", justifyContent: "space-between", borderRadius: "0.5rem", backgroundColor: "rgba(255,255,255,0.04)", paddingInline: "0.75rem", paddingBlock: "0.5rem", textAlign: "left", fontSize: text.sizeSm, lineHeight: "1.25rem", ":hover": { backgroundColor: "rgba(255,255,255,0.07)" } },
  accentText: { color: ACCENT },
  subText: { marginTop: "0.25rem", display: "block", fontSize: "11px", lineHeight: "1rem", color: "rgba(255,255,255,0.35)" },
  dropHint: { marginTop: "0.25rem", fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.35)" },
  cardSuccess: { borderWidth: "1px", borderStyle: "solid", borderColor: "rgba(52,211,153,0.2)", borderRadius: "0.75rem", backgroundColor: "rgba(52,211,153,0.06)", padding: "1rem" },
  cardWarning: { borderWidth: "1px", borderStyle: "solid", borderColor: "rgba(252,211,77,0.25)", borderRadius: "0.75rem", backgroundColor: "rgba(252,211,77,0.05)", padding: "1rem" },
  searchIcon: { pointerEvents: "none", position: "absolute", left: "0.75rem", top: "50%", width: "1rem", height: "1rem", transform: "translateY(-50%)", color: "hsl(var(--muted-foreground))" },
  searchSpinner: { color: "hsl(var(--primary))" },
  clearButton: { position: "absolute", right: "0.5rem", top: "50%", display: "grid", width: "1.5rem", height: "1.5rem", placeItems: "center", transform: "translateY(-50%)", borderRadius: "0.25rem", color: "hsl(var(--muted-foreground))", transitionProperty: "color", transitionDuration: "150ms", transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)", ":hover": { color: "hsl(var(--foreground))" }, ":focus-visible": { outlineWidth: "2px", outlineStyle: "solid", outlineColor: "transparent", outlineOffset: "2px", boxShadow: "0 0 0 2px hsl(var(--ring))" } },
  toolbarCount: { flexShrink: 0, fontSize: text.sizeXs, lineHeight: "1rem", color: "hsl(var(--muted-foreground))" },
  cellStrong: { fontWeight: 500 },
  srOnly: { position: "absolute", width: "1px", height: "1px", padding: 0, margin: "-1px", overflow: "hidden", clip: "rect(0,0,0,0)", whiteSpace: "nowrap", borderWidth: 0 },
  titleText: { fontWeight: 500 },
  searchWrap: { position: "relative", minWidth: 0, flex: 1, [SM]: { maxWidth: "24rem" } },
  // [&::-webkit-search-cancel-button]:hidden — WebKit draws its own clear
  // affordance inside `type="search"`; the toolbar supplies one of its own.
  searchInput: { height: "2.25rem", paddingLeft: "2.25rem", paddingRight: "2.25rem", "::-webkit-search-cancel-button": { display: "none" } },
  generateCard: { borderWidth: "1px", borderStyle: "solid", borderColor: "rgba(232,224,68,0.2)", borderRadius: "0.75rem", backgroundColor: "rgba(232,224,68,0.03)", padding: "1rem" },
  generateHeading: { fontSize: "10px", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.18em", color: ACCENT },
  generateText: { marginTop: "0.375rem", fontSize: text.sizeXs, lineHeight: "1.25rem", color: "rgba(255,255,255,0.5)" },
  artifactList: { marginTop: "0.75rem", display: "flex", flexDirection: "column", gap: "0.375rem" },
  artifactItem: { display: "flex", alignItems: "flex-start", gap: "0.5rem", fontSize: text.sizeXs, lineHeight: "1.25rem", color: "rgba(255,255,255,0.5)" },
  artifactDot: { marginTop: "0.5rem", width: "0.25rem", height: "0.25rem", flexShrink: 0, borderRadius: "9999px", backgroundColor: "rgba(232,224,68,0.6)" },
  toolbarGroup: { marginLeft: "auto" },
  toolbarCountValue: { fontVariantNumeric: "tabular-nums", color: "hsl(var(--foreground))" },
  iconButton: { width: "0.875rem", height: "0.875rem" },
  toolbarSelect: { height: "2.25rem", fontSize: text.sizeXs, lineHeight: "1rem" },
  // `sm:w-48` / `sm:w-40` over the trigger's own `w-full`: `width` is one
  // merge key, so the default has to be restated alongside the 640px step.
  toolbarActor: { width: { default: "100%", [SM]: "12rem" } },
  toolbarCarla: { width: { default: "100%", [SM]: "10rem" } },
  toolbarSort: { height: "2.25rem", display: "inline-flex", alignItems: "center", gap: "0.375rem", fontSize: text.sizeXs, lineHeight: "1rem" },
  detailSheet: { width: "100%", overflowY: "auto", borderColor: "hsl(var(--border))", backgroundColor: "hsl(var(--background))", [SM]: { maxWidth: "36rem" } },
  renameForm: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: "0.5rem" },
  inputCompact: { height: "2.25rem", minWidth: 0, flex: 1 },
  buttonCompact: { height: "2.25rem" },
  deleteBox: { borderWidth: "1px", borderStyle: "solid", borderColor: "hsl(var(--destructive) / 0.5)", borderRadius: "0.5rem", backgroundColor: "hsl(var(--destructive) / 0.1)", padding: "0.75rem" },
  deleteHeading: { fontSize: text.sizeSm, lineHeight: "1.25rem", fontWeight: 600 },
  usageLoading: { marginTop: "0.5rem", display: "inline-flex", alignItems: "center", gap: "0.375rem", fontSize: text.sizeXs, lineHeight: "1rem", color: "hsl(var(--muted-foreground))" },
  usageIcon: { width: "0.75rem", height: "0.75rem" },
  usageWarning: { marginTop: "0.5rem", display: "inline-flex", alignItems: "center", gap: "0.5rem", borderWidth: "1px", borderStyle: "solid", borderColor: "hsl(var(--primary) / 0.4)", borderRadius: "0.375rem", backgroundColor: "hsl(var(--primary) / 0.1)", paddingInline: "0.625rem", paddingBlock: "0.375rem", fontSize: text.sizeSm, lineHeight: "1.25rem", fontWeight: 600, color: "hsl(var(--primary))" },
  usageWarningIcon: { width: "1rem", height: "1rem" },
  usageNote: { marginTop: "0.5rem", fontSize: text.sizeXs, lineHeight: "1rem", color: "hsl(var(--muted-foreground))" },
  deleteActions: { marginTop: "0.75rem", display: "flex", flexWrap: "wrap", gap: "0.5rem" },
  errorDanger: { fontSize: text.sizeSm, lineHeight: "1.25rem", color: "#fca5a5" },
  uploadPreviewGrid: { display: "grid", gap: "1.25rem", [SM]: { gridTemplateColumns: "240px 1fr" } },
  uploadControls: { display: "flex", flexDirection: "column", gap: "0.75rem" },
  uploadGrid2: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "0.75rem" },
  uploadGrid: { display: "grid", gap: "1rem", [SM]: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" } },
  uploadSpan2: { [SM]: { gridColumn: "span 2" } },
  uploadRow: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: "0.5rem" },
  uploadBottom: { marginTop: "1.25rem", display: "flex", flexDirection: "column", gap: "1.25rem" },
  uploadStatus: { marginBottom: "0.25rem", display: "flex", justifyContent: "space-between", fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.45)" },
  uploadBar: { height: "0.375rem", overflow: "hidden", borderRadius: "9999px", backgroundColor: "rgba(255,255,255,0.07)" },
  uploadBarFill: { height: "100%", backgroundColor: ACCENT, transitionProperty: "width", transitionDuration: "150ms" },
  uploadText: { fontSize: text.sizeSm, lineHeight: "1.25rem", color: "#fca5a5" },
  uploadActions: { display: "flex", justifyContent: "flex-end", gap: "0.5rem" },
  uploadDropLabel: { fontSize: text.sizeSm, lineHeight: "1.25rem", fontWeight: 500 },
  uploadImage: { aspectRatio: "1", width: "100%", borderWidth: "1px", borderStyle: "solid", borderColor: "rgba(255,255,255,0.1)", borderRadius: "0.75rem", backgroundImage: "radial-gradient(circle,#27303a,#101317)", objectFit: "contain" },
  uploadMeta: { marginTop: "0.5rem", fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.4)" },
  uploadLabel: { fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.45)" },
  uploadField: { marginTop: "0.25rem" },
  motionOption: { borderWidth: "1px", borderStyle: "solid", borderColor: "rgba(255,255,255,0.12)", borderRadius: "0.5rem", backgroundColor: "rgba(255,255,255,0.03)", padding: "0.75rem", textAlign: "left", ":hover": { backgroundColor: "rgba(255,255,255,0.06)" } },
  motionOptionActive: { borderColor: "rgba(232,224,68,0.6)", backgroundColor: "rgba(232,224,68,0.1)" },
  motionTitle: { display: "block", fontSize: text.sizeSm, lineHeight: "1.25rem", color: "#fff" },
  motionDescription: { marginTop: "0.125rem", display: "block", fontSize: text.sizeXs, lineHeight: "1.25rem", color: "rgba(255,255,255,0.55)" },
  warningText: { fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(253,230,138,0.7)" },
  clipsTitle: { fontSize: text.sizeXs, lineHeight: "1rem", color: "rgba(255,255,255,0.45)" },
  clipsText: { marginTop: "0.25rem", fontSize: text.sizeSm, lineHeight: "1.25rem", color: "rgba(255,255,255,0.7)" },
  successText: { fontSize: text.sizeSm, lineHeight: "1.25rem", fontWeight: 500, color: "#d1fae5" },
  uploadFullButton: { width: "100%", borderColor: "rgba(255,255,255,0.1)", backgroundColor: "transparent" },
  uploadTransparent: { borderColor: "rgba(255,255,255,0.1)", backgroundColor: "transparent" },
  autoSize: { borderColor: "rgba(232,224,68,0.4)", backgroundColor: "transparent", color: "#E8E044", ":hover": { backgroundColor: "rgba(232,224,68,0.1)" } },
  uploadMotionGrid: { display: "grid", gap: "0.5rem", [SM]: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" } },
});

export const drawer = stylex.create({
  root: { display: "flex", flexDirection: "column", gap: "1.5rem" },
  stats: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "0.75rem", fontSize: text.sizeSm, lineHeight: "1.25rem" },
  tile: { borderWidth: "1px", borderStyle: "solid", borderColor: "hsl(var(--border))", borderRadius: "0.5rem", backgroundColor: "hsl(var(--muted) / 0.3)", padding: "0.75rem" },
  eyebrow: { fontSize: "10px", textTransform: "uppercase", letterSpacing: "0.05em", color: "hsl(var(--muted-foreground))" },
  value: { marginTop: "0.25rem", fontVariantNumeric: "tabular-nums" },
  valueCapitalize: { marginTop: "0.25rem", textTransform: "capitalize" },
  valueUppercase: { marginTop: "0.25rem", textTransform: "uppercase" },
  actions: { display: "flex", flexWrap: "wrap", gap: "0.5rem" },
  section: { display: "flex", flexDirection: "column", gap: "0.75rem" },
});