import * as stylex from "@stylexjs/stylex";
import { colors, space, stroke, text } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

export const styles = stylex.create({
  insightsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: space.s5,
  },
  scenarioFamiliesHeading: {
    marginBottom: space.s2_5,
    color: colors.mutedForeground,
  },
  scenarioFamilyList: {
    display: "flex",
    flexDirection: "column",
    gap: space.s2,
  },
  candidateLocationsHeader: {
    display: "flex",
    alignItems: "center",
    gap: space.s1,
  },
  candidateLocationsToggle: {
    display: "flex",
    flex: "1 1 0%",
    alignItems: "center",
    gap: space.s1_5,
    color: { default: colors.mutedForeground, ":hover": colors.text },
  },
  chevron: {
    width: "0.75rem",
    height: "0.75rem",
    flexShrink: 0,
  },
  rotate90: {
    transform: "rotate(90deg)",
  },
  loadingIndicator: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.s1,
    backgroundColor: colors.fillSubtle,
    paddingInline: space.s1_5,
    paddingBlock: "1px",
    fontSize: text.sizeMicro,
    color: colors.mutedForeground,
  },
  loadingSpinner: {
    width: "0.625rem",
    height: "0.625rem",
  },
  candidateCountBadge: {
    backgroundColor: "rgba(67, 20, 7, 0.6)",
    paddingInline: space.s1_5,
    paddingBlock: "1px",
    fontSize: text.sizeMicro,
    fontWeight: text.weightSemibold,
    color: "#fdba74",
  },
  activeFilterButton: {
    display: "flex",
    alignItems: "center",
    gap: space.s0_5,
    backgroundColor: { default: colors.accentWash, ":hover": colors.accentWash },
    paddingInline: space.s2,
    paddingBlock: space.s0_5,
    fontSize: text.sizeMicro,
    color: colors.primary,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: colors.accentLineSubtle,
  },
  clearFilterIcon: {
    width: "0.625rem",
    height: "0.625rem",
  },
  candidateExplorerContent: {
    display: "flex",
    flexDirection: "column",
    gap: space.s2,
    marginTop: space.s2,
  },
  familyFilterChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: space.s1,
  },
  insightChip: {
    paddingInline: space.s2,
    paddingBlock: space.s0_5,
    fontSize: text.sizeMicro,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
  },
  insightChipActive: {
    backgroundColor: colors.accentWash,
    color: colors.primary,
    borderColor: colors.accentLineSubtle,
  },
  insightChipIdle: {
    backgroundColor: { default: colors.fillFaint, ":hover": colors.fillSubtle },
    color: colors.mutedForeground,
    borderColor: colors.hairline,
  },
  familyCandidateCount: {
    color: colors.inkFaint,
  },
  candidateLoadingMessage: {
    display: "flex",
    alignItems: "center",
    gap: space.s1_5,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.mutedForeground,
  },
  candidateLoadingSpinner: {
    width: "0.75rem",
    height: "0.75rem",
  },
  candidateEmptyMessage: {
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.mutedForeground,
  },
  candidateLocationList: {
    display: "flex",
    flexDirection: "column",
    gap: space.s1_5,
  },
  scenarioFamilyCard: {
    backgroundColor: colors.fillFaint,
  },
  scenarioFamilyToggle: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    gap: space.s2,
    paddingInline: space.s3,
    paddingBlock: space.s2_5,
    textAlign: "left",
    backgroundColor: { default: null, ":hover": colors.fillFaint },
  },
  chevronMutedShrink: {
    width: "0.75rem",
    height: "0.75rem",
    flexShrink: 0,
    color: colors.mutedForeground,
  },
  scenarioFamilyIcon: {
    width: "0.875rem",
    height: "0.875rem",
    color: colors.primary,
    flexShrink: 0,
  },
  scenarioFamilyName: {
    flex: "1 1 0%",
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    fontWeight: text.weightMedium,
    color: colors.text,
  },
  scenarioFamilyLocationCount: {
    backgroundColor: colors.fillSubtle,
    paddingInline: space.s1_5,
    paddingBlock: "1px",
    fontSize: text.sizeMicro,
    color: colors.mutedForeground,
  },
  expandedFamilyContent: {
    borderTopWidth: stroke.hairline,
    borderTopStyle: "solid",
    borderColor: colors.hairline,
    paddingInline: space.s3,
    paddingBlock: space.s2_5,
  },
  familyDescriptionTrigger: {
    textAlign: "left",
    fontSize: text.sizeMeta,
    color: colors.mutedForeground,
    lineHeight: text.lineRelaxed,
    cursor: "help",
    textDecorationLine: "underline",
    textDecorationStyle: "dotted",
    textUnderlineOffset: "2px",
  },
  stackY2_5: { marginTop: { default: space.s2_5, ":first-child": 0 } },
  familyTagsTooltip: {
    maxWidth: "20rem",
    whiteSpace: "pre-line",
    fontSize: text.sizeXs,
    lineHeight: text.lineRelaxed,
  },
  familyDescription: {
    fontSize: text.sizeMeta,
    color: colors.mutedForeground,
    lineHeight: text.lineRelaxed,
  },
});
