import * as stylex from "@stylexjs/stylex";
import { colors, text, space, motion } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

export const styles = stylex.create({
  insightsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "1.25rem",
  },
  scenarioFamiliesHeading: {
    marginBottom: "0.625rem",
    fontSize: "10px",
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: colors.mutedForeground,
  },
  scenarioFamilyList: {
    display: "flex",
    flexDirection: "column",
    gap: space.s2,
  },
  candidateLocationsHeader: {
    display: "flex",
    alignItems: "center",
    gap: space.s1,
  },
  candidateLocationsToggle: {
    display: "flex",
    flex: "1 1 0%",
    alignItems: "center",
    gap: space.s1_5,
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.025em",
    color: { default: colors.mutedForeground, ":hover": colors.text },
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  chevron: {
    width: "0.75rem",
    height: "0.75rem",
    flexShrink: 0,
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  rotate90: {
    transform: "rotate(90deg)",
  },
  loadingIndicator: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.s1,
    backgroundColor: "hsl(var(--muted) / 0.5)",
    paddingInline: space.s1_5,
    paddingBlock: "1px",
    fontSize: "10px",
    color: colors.mutedForeground,
  },
  loadingSpinner: {
    width: "0.625rem",
    height: "0.625rem",
    animationName: spin,
    animationDuration: "1s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
  },
  candidateCountBadge: {
    backgroundColor: "rgba(67, 20, 7, 0.6)",
    paddingInline: space.s1_5,
    paddingBlock: "1px",
    fontSize: "10px",
    fontWeight: 600,
    color: "#fdba74",
  },
  activeFilterButton: {
    display: "flex",
    alignItems: "center",
    gap: space.s0_5,
    backgroundColor: { default: "hsl(var(--primary) / 0.1)", ":hover": "hsl(var(--primary) / 0.2)" },
    paddingInline: space.s2,
    paddingBlock: space.s0_5,
    fontSize: "10px",
    color: colors.primary,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "hsl(var(--primary) / 0.2)",
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  clearFilterIcon: {
    width: "0.625rem",
    height: "0.625rem",
  },
  candidateExplorerContent: {
    display: "flex",
    flexDirection: "column",
    gap: space.s2,
    marginTop: space.s2,
  },
  familyFilterChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: space.s1,
  },
  insightChip: {
    paddingInline: space.s2,
    paddingBlock: space.s0_5,
    fontSize: "10px",
    borderWidth: "1px",
    borderStyle: "solid",
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  insightChipActive: {
    backgroundColor: "hsl(var(--primary) / 0.15)",
    color: colors.primary,
    borderColor: "hsl(var(--primary) / 0.3)",
  },
  insightChipIdle: {
    backgroundColor: { default: "hsl(var(--muted) / 0.3)", ":hover": "hsl(var(--muted) / 0.5)" },
    color: colors.mutedForeground,
    borderColor: colors.border,
  },
  familyCandidateCount: {
    color: "hsl(var(--muted-foreground) / 0.6)",
  },
  candidateLoadingMessage: {
    display: "flex",
    alignItems: "center",
    gap: space.s1_5,
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    color: colors.mutedForeground,
  },
  candidateLoadingSpinner: {
    width: "0.75rem",
    height: "0.75rem",
    animationName: spin,
    animationDuration: "1s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
  },
  candidateEmptyMessage: {
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    color: colors.mutedForeground,
  },
  candidateLocationList: {
    display: "flex",
    flexDirection: "column",
    gap: space.s1_5,
  },
  scenarioFamilyCard: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: "hsl(var(--muted) / 0.1)",
  },
  scenarioFamilyToggle: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    gap: space.s2,
    paddingInline: space.s3,
    paddingBlock: "0.625rem",
    textAlign: "left",
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
    backgroundColor: { default: null, ":hover": "hsl(var(--muted) / 0.2)" },
  },
  chevronMutedShrink: {
    width: "0.75rem",
    height: "0.75rem",
    flexShrink: 0,
    color: colors.mutedForeground,
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  scenarioFamilyIcon: {
    width: "0.875rem",
    height: "0.875rem",
    color: colors.primary,
    flexShrink: 0,
  },
  scenarioFamilyName: {
    flex: "1 1 0%",
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 500,
    color: colors.text,
  },
  scenarioFamilyLocationCount: {
    backgroundColor: "hsl(var(--muted) / 0.5)",
    paddingInline: space.s1_5,
    paddingBlock: "1px",
    fontSize: "10px",
    color: colors.mutedForeground,
  },
  expandedFamilyContent: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderColor: colors.border,
    paddingInline: space.s3,
    paddingBlock: "0.625rem",
  },
  familyDescriptionTrigger: {
    textAlign: "left",
    fontSize: "11px",
    color: colors.mutedForeground,
    lineHeight: 1.625,
    cursor: "help",
    textDecorationLine: "underline",
    textDecorationStyle: "dotted",
    textUnderlineOffset: "2px",
  },
  stackY2_5: { marginTop: { default: "0.625rem", ":first-child": 0 } },
  familyTagsTooltip: {
    maxWidth: "20rem",
    whiteSpace: "pre-line",
    fontSize: text.sizeXs,
    lineHeight: 1.625,
  },
  familyDescription: {
    fontSize: "11px",
    color: colors.mutedForeground,
    lineHeight: 1.625,
  },
});
