import * as stylex from "@stylexjs/stylex";
import { colors, text, space, motion } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

export const styles = stylex.create({
  quickStatCard: {
    padding: space.s3,
    backgroundColor: { default: "hsl(var(--secondary) / 0.5)", ":hover": "hsl(var(--secondary) / 0.7)" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  quickStatLabelRow: {
    display: "flex",
    alignItems: "center",
    gap: space.s2,
    color: colors.mutedForeground,
    marginBottom: space.s2,
  },
  quickStatLabel: {
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 500,
  },
  quickStatValue: {
    fontSize: text.sizeLg,
    lineHeight: "1.75rem",
    fontWeight: 600,
    color: colors.text,
    fontFamily: "var(--font-mono), ui-monospace, monospace",
  },
  quickStatTooltip: {
    fontSize: text.sizeXs,
    lineHeight: 1.625,
  },
  overviewContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "1.25rem",
  },
  assetHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: space.s2,
  },
  assetTitleBlock: {
    minWidth: 0,
  },
  assetTitle: {
    fontSize: text.sizeSm,
    lineHeight: 1.375,
    fontWeight: 600,
  },
  assetLocation: {
    marginTop: space.s0_5,
    fontSize: "11px",
    color: colors.mutedForeground,
  },
  descriptionBlock: {
    marginTop: space.s1,
  },
  overviewDescription: {
    fontSize: text.sizeXs,
    lineHeight: 1.625,
    color: colors.mutedForeground,
  },
  clamp2: {
    overflow: "hidden",
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
  },
  descriptionToggle: {
    marginTop: space.s0_5,
    fontSize: "10px",
    color: { default: "hsl(var(--muted-foreground) / 0.6)", ":hover": colors.mutedForeground },
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: space.s2,
  },
  sectionTitle: {
    fontSize: "10px",
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: colors.mutedForeground,
  },
  viewAllButton: {
    display: "flex",
    alignItems: "center",
    gap: space.s0_5,
    fontSize: "10px",
    color: { default: colors.primary, ":hover": "hsl(var(--primary) / 0.8)" },
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  viewAllChevron: {
    width: "0.75rem",
    height: "0.75rem",
  },
  quickStatsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "0.625rem",
  },
  quickStatIcon: {
    width: "1rem",
    height: "1rem",
  },
  insightsStatsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: space.s1_5,
    marginBottom: space.s3,
  },
  locationCount: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.s1,
    backgroundColor: "hsl(var(--muted) / 0.5)",
    paddingInline: space.s2,
    paddingBlock: space.s0_5,
    fontSize: "10px",
    color: colors.mutedForeground,
  },
  loadingIcon: {
    width: "0.625rem",
    height: "0.625rem",
    animationName: spin,
    animationDuration: "1s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
  },
  familyCount: {
    display: "inline-flex",
    alignItems: "center",
    backgroundColor: "hsl(var(--muted) / 0.5)",
    paddingInline: space.s2,
    paddingBlock: space.s0_5,
    fontSize: "10px",
    color: colors.mutedForeground,
  },
  confidenceCount: {
    display: "inline-flex",
    alignItems: "center",
    backgroundColor: "rgba(2, 44, 34, 0.4)",
    paddingInline: space.s2,
    paddingBlock: space.s0_5,
    fontSize: "10px",
    color: "#34d399",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(4, 120, 87, 0.3)",
  },
  familyGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: space.s2,
  },
  familyCard: {
    minWidth: 0,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: { default: "hsl(var(--muted) / 0.2)", ":hover": "hsl(var(--muted) / 0.4)" },
    paddingInline: space.s3,
    paddingBlock: "0.625rem",
    textAlign: "left",
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  familyCardHeader: {
    display: "flex",
    alignItems: "center",
    gap: space.s2,
  },
  familyIcon: {
    width: "0.875rem",
    height: "0.875rem",
    color: colors.primary,
    flexShrink: 0,
  },
  familyName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: text.sizeXs,
    lineHeight: "1rem",
    fontWeight: 500,
    color: colors.text,
  },
  familySummary: {
    marginTop: space.s0_5,
    fontSize: "10px",
    color: "hsl(var(--muted-foreground) / 0.7)",
  },
  familyTooltip: {
    display: "flex",
    flexDirection: "column",
    gap: space.s1,
    maxWidth: "20rem",
    fontSize: text.sizeXs,
    lineHeight: 1.625,
  },
  tooltipLabel: {
    fontWeight: 600,
  },
  tooltipAction: {
    color: colors.mutedForeground,
  },
  expandFamiliesButton: {
    marginTop: space.s2,
    display: "flex",
    alignItems: "center",
    gap: space.s0_5,
    fontSize: "10px",
    color: { default: colors.primary, ":hover": "hsl(var(--primary) / 0.8)" },
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  chevronBare: {
    width: "0.75rem",
    height: "0.75rem",
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "150ms",
  },
  rotate90: {
    transform: "rotate(90deg)",
  },
});
