import * as stylex from "@stylexjs/stylex";
import { colors, motion, space, stroke, text } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

export const styles = stylex.create({
  pathChain: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: space.s1,
    paddingLeft: space.s2,
    paddingTop: space.s0_5,
    fontSize: text.sizeMicro,
    color: colors.mutedForeground,
  },
  pathLabel: {
    fontWeight: text.weightMedium,
    textTransform: "uppercase",
    letterSpacing: text.trackingWide,
    color: colors.inkMuted,
  },
  pathStepWrapper: {
    display: "flex",
    alignItems: "center",
    gap: space.s1,
  },
  pathEllipsisIcon: {
    width: "0.75rem",
    height: "0.75rem",
    color: colors.inkFaint,
  },
  pathEllipsisSeparator: {
    width: "0.625rem",
    height: "0.625rem",
    color: colors.inkFaint,
  },
  stepChip: {
    display: "flex",
    alignItems: "center",
    gap: space.s1,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    paddingInline: space.s1_5,
    paddingBlock: space.s0_5,
  },
  stepChipOn: {
    borderColor: colors.accentLine,
    backgroundColor: colors.accentWash,
  },
  stepChipOff: {
    borderColor: colors.hairline,
    backgroundColor: colors.fillSubtle,
  },
  pathStepIcon: {
    width: "0.625rem",
    height: "0.625rem",
    flexShrink: 0,
  },
  pathStepObjectId: {
    maxWidth: "200px",
    fontFamily: text.fontMono,
    color: colors.inkMuted,
  },
  pathStepDistance: {
    fontFamily: text.fontMono,
    color: colors.inkMuted,
  },
  pathStepSeparator: {
    width: "0.625rem",
    height: "0.625rem",
    flexShrink: 0,
    color: colors.inkFaint,
  },
  highlightToggleXs: {
    width: "1rem",
    height: "1rem",
  },
  highlightToggleDefault: {
    width: "1.25rem",
    height: "1.25rem",
  },
  highlightIconXs: {
    width: "0.625rem",
    height: "0.625rem",
    flexShrink: 0,
  },
  highlightIconDefault: {
    width: "0.75rem",
    height: "0.75rem",
    flexShrink: 0,
  },
  highlightToggle: {
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  highlightToggleOn: {
    backgroundColor: { default: "hsl(var(--primary) / 0.3)", ":hover": "hsl(var(--primary) / 0.4)" },
    color: colors.primary,
  },
  highlightToggleOff: {
    color: { default: colors.mutedForeground, ":hover": colors.text },
    backgroundColor: { default: null, ":hover": colors.muted },
  },
  emptyQueryState: {
    display: "flex",
    height: "100%",
    minHeight: 0,
    flexDirection: "column",
  },
  emptyQueryInputPanel: {
    display: "flex",
    flexDirection: "column",
    gap: space.s4,
    flexShrink: 0,
    paddingInline: space.s4,
    paddingTop: space.s4,
    paddingBottom: space.s3,
  },
  queryPrompt: {
    display: "flex",
    flexDirection: "column",
    gap: space.s1,
  },
  queryPromptHeading: {
    fontSize: text.sizeSm,
    lineHeight: text.lineSm,
    fontWeight: text.weightSemibold,
    color: colors.text,
  },
  queryPromptDescription: {
    fontSize: text.sizeXs,
    lineHeight: text.lineRelaxed,
    color: colors.mutedForeground,
  },
  searchExamplesPanel: {
    minHeight: 0,
    flex: "1 1 0%",
    overflowY: "auto",
    paddingInline: space.s4,
    paddingBottom: space.s4,
  },
  resultsPage: {
    display: "flex",
    height: "100%",
    flexDirection: "column",
    gap: space.s3,
    padding: space.s4,
  },
  resultsHeader: {
    display: "flex",
    flexDirection: "column",
    gap: space.s2_5,
  },
  debugPanel: {
    display: "flex",
    flexDirection: "column",
    gap: space.s2,
    borderWidth: stroke.hairline,
    borderStyle: "dashed",
    borderColor: colors.hairline,
    backgroundColor: "hsl(var(--secondary) / 0.2)",
    padding: space.s2,
    fontSize: text.sizeMeta,
  },
  debugSectionLabel: {
    color: colors.mutedForeground,
  },
  parsedQueryLabel: {
    fontWeight: text.weightSemibold,
    color: colors.text,
  },
  debugTokenList: {
    display: "flex",
    flexWrap: "wrap",
    gap: space.s1,
  },
  debugTokenBadge: {
    paddingInline: space.s1_5,
    paddingBlock: 0,
    fontFamily: text.fontMono,
    fontSize: text.sizeMicro,
    lineHeight: "inherit",
  },
  filterChipsRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: space.s1,
    paddingInline: space.s1,
  },
  debugToggle: {
    display: "inline-flex",
    width: "1.25rem",
    height: "1.25rem",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    color: { default: colors.mutedForeground, ":hover": colors.text },
    backgroundColor: { default: null, ":hover": "hsl(var(--secondary) / 0.4)" },
  },
  debugToggleOn: {
    backgroundColor: "hsl(var(--secondary) / 0.6)",
    color: colors.text,
  },
  compactContextIcon: {
    width: "0.75rem",
    height: "0.75rem",
  },
  tooltipContent: {
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
  },
  relationChip: {
    display: "inline-flex",
    alignItems: "center",
    overflow: "hidden",
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: colors.accentLineSubtle,
    backgroundColor: colors.accentWash,
    fontSize: text.sizeMeta,
    fontWeight: text.weightNormal,
  },
  relationOperator: {
    paddingInline: space.s1_5,
    paddingBlock: 0,
    color: colors.primary,
  },
  relationObject: {
    paddingInline: space.s1_5,
    paddingBlock: 0,
    color: colors.text,
    backgroundColor: colors.accentWash,
  },
  structuredFilterBadge: {
    borderColor: "transparent",
    backgroundColor: "hsl(var(--secondary) / 0.5)",
    paddingInline: space.s1_5,
    paddingBlock: 0,
    fontSize: text.sizeMeta,
    lineHeight: "inherit",
    fontWeight: text.weightNormal,
    color: colors.text,
  },
  freeTextBadge: {
    borderStyle: "dashed",
    backgroundColor: "transparent",
    paddingInline: space.s1_5,
    paddingBlock: 0,
    fontSize: text.sizeMeta,
    lineHeight: "inherit",
    fontWeight: text.weightNormal,
    color: colors.mutedForeground,
  },
  resultsContent: {
    display: "flex",
    minHeight: 0,
    flex: "1 1 0%",
    flexDirection: "column",
    overflow: "hidden",
    borderTopWidth: stroke.hairline,
    borderTopStyle: "solid",
    borderColor: colors.hairline,
    paddingTop: space.s2,
  },
  loadingStatus: {
    marginBottom: space.s2,
    display: "flex",
    alignItems: "center",
    gap: space.s1_5,
    color: colors.mutedForeground,
  },
  loadingIcon: {
    width: "0.75rem",
    height: "0.75rem",
  },
  resultsHeaderActions: {
    marginBottom: space.s2,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    color: colors.mutedForeground,
  },
  resultList: {
    flex: "1 1 0%",
    overflowY: "auto",
  },
  resultCardsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: space.s2,
    paddingRight: space.s2,
  },
  resultCard: {
    width: "100%",
    cursor: "pointer",
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    paddingInline: space.s3,
    paddingBlock: space.s2_5,
    textAlign: "left",
    transitionProperty: "all",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durStandard,
  },
  resultCardSelected: {
    borderColor: colors.accentLine,
    backgroundColor: colors.accentWash,
  },
  resultCardIdle: {
    borderColor: colors.hairline,
    backgroundColor: { default: "hsl(var(--secondary) / 0.2)", ":hover": "hsl(var(--secondary) / 0.4)" },
  },
  resultCardHeader: {
    display: "flex",
    alignItems: "center",
    gap: space.s2,
  },
  resultTypeIcon: {
    width: "0.875rem",
    height: "0.875rem",
    flexShrink: 0,
    color: colors.mutedForeground,
  },
  resultTitle: {
    minWidth: 0,
    flex: "1 1 0%",
    fontSize: text.sizeSm,
    lineHeight: text.lineSm,
    fontWeight: text.weightSemibold,
    color: colors.text,
  },
  selectedCheckIcon: {
    width: "1rem",
    height: "1rem",
    flexShrink: 0,
    color: colors.primary,
  },
  resultMetadataGrid: {
    marginTop: space.s1_5,
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: space.s2,
    fontSize: text.sizeMeta,
  },
  metadataItem: {
    minWidth: 0,
  },
  metadataLabel: {
    color: colors.mutedForeground,
  },
  metadataValue: {
    fontWeight: text.weightMedium,
    color: colors.text,
  },
  confidenceValue: {
    fontWeight: text.weightMedium,
    color: colors.positive,
  },
  attributeBadgeRow: {
    marginTop: space.s1_5,
    display: "flex",
    flexWrap: "wrap",
    gap: space.s1,
  },
  attributeBadge: {
    borderColor: "transparent",
    backgroundColor: "hsl(var(--secondary) / 0.5)",
    paddingInline: space.s2,
    paddingBlock: space.s0_5,
    fontSize: text.sizeTag,
    lineHeight: "inherit",
    color: colors.text,
  },
  relatedRefsList: {
    display: "flex",
    flexDirection: "column",
    gap: space.s1,
    marginTop: space.s1_5,
  },
  relatedRefItem: {
    display: "flex",
    flexDirection: "column",
    gap: space.s0_5,
  },
  refChip: { display: "flex", alignItems: "center", gap: space.s1_5, padding: space.s1, borderWidth: stroke.hairline, borderStyle: "solid", fontSize: text.sizeXs },
  refChipOn: { backgroundColor: colors.secondary, borderColor: colors.primary },
  refChipOff: { backgroundColor: colors.muted, borderColor: colors.hairline },
  relationLabelRow: {
    display: "flex",
    alignItems: "center",
    gap: space.s1,
    color: colors.primary,
  },
  relationText: {
    fontWeight: text.weightMedium,
  },
  relatedRefIcon: {
    width: "0.75rem",
    height: "0.75rem",
    flexShrink: 0,
    color: colors.mutedForeground,
  },
  relatedRefTitle: {
    minWidth: 0,
    flex: "1 1 0%",
    color: colors.text,
  },
  relatedRefDistance: {
    flexShrink: 0,
    color: colors.mutedForeground,
  },
  relatedRefDebugMetadata: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: space.s1,
    paddingLeft: space.s2,
    fontSize: text.sizeMicro,
    color: colors.inkMuted,
  },
  debugValue: {
    fontFamily: text.fontMono,
  },
  resultDebugPanel: {
    display: "flex",
    flexDirection: "column",
    gap: space.s0_5,
    marginTop: space.s1_5,
    fontSize: text.sizeMicro,
    color: colors.mutedForeground,
  },
  resultDebugIdentity: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: space.s1,
  },
  resultActions: {
    marginTop: space.s2,
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: space.s1,
  },
  resultActionIcon: {
    width: "0.875rem",
    height: "0.875rem",
  },
  emptyResultsState: {
    borderWidth: stroke.hairline,
    borderStyle: "dashed",
    borderColor: colors.hairline,
    paddingInline: space.s3,
    paddingBlock: space.s6,
    textAlign: "center",
  },
  emptyResultsLoading: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: space.s1_5,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.mutedForeground,
  },
  noResultsHeading: {
    fontSize: text.sizeSm,
    lineHeight: text.lineSm,
    fontWeight: text.weightMedium,
    color: colors.text,
  },
  noResultsGuidance: {
    marginTop: space.s1,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.mutedForeground,
  },
  alternativeQueriesSection: {
    marginTop: space.s3,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: space.s1_5,
  },
  alternativeQueriesHeading: {
    fontSize: text.sizeMeta,
    color: colors.mutedForeground,
  },
  alternativeQueriesList: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: space.s1_5,
  },
  alternativeQueryButton: {
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: { default: colors.hairline, ":hover": colors.accentLineSubtle },
    backgroundColor: { default: "hsl(var(--secondary) / 0.3)", ":hover": colors.accentWash },
    paddingInline: space.s2_5,
    paddingBlock: space.s1,
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.text,
  },
});
