from os import PathLike
from typing import Any

RENDER_TIMELINE_VERSION: str
SAMPLER_VERSION: str
TIMELINE_DT_S: float
POSE_ARRAY_LEN: int

Pose = dict[str, Any]

class Timeline:
    @staticmethod
    def from_json(data: bytes | str) -> Timeline: ...
    @staticmethod
    def load(path: str | PathLike[str]) -> Timeline: ...
    def to_json(self) -> str: ...
    def to_canonical_json(self) -> str: ...
    @property
    def sha256(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def trace_sha256(self) -> str: ...
    @property
    def map_id(self) -> str: ...
    @property
    def xodr_sha256(self) -> str | None: ...
    @property
    def dt(self) -> float: ...
    @property
    def tick_count(self) -> int: ...
    @property
    def warmup_s(self) -> float: ...
    @property
    def clip_end_s(self) -> float: ...
    @property
    def times(self) -> list[float]: ...
    @property
    def actor_ids(self) -> list[str]: ...
    def actor(self, actor_id: str) -> dict[str, Any]: ...
    def props(self) -> list[dict[str, Any]]: ...
    def pose(self, actor_id: str, t: float) -> Pose: ...
    def pose_array(self, actor_id: str, t: float) -> list[float]: ...
    def poses(self, t: float) -> dict[str, Pose]: ...
    def signals_at(self, t: float) -> dict[str, str]: ...
    def lights_at(self, actor_id: str, t: float) -> dict[str, bool]: ...
    def light_modes_at(self, actor_id: str, t: float) -> dict[str, str]: ...
    def scene_state_json(self, times: list[float], yaw_only: bool = False) -> str: ...

def pose(timeline: Timeline, actor_id: str, t: float) -> Pose: ...
def build_timeline(
    trace: bytes | str,
    xodr: bytes | str | None = None,
    topology: bytes | str | None = None,
    catalog_digest: str | None = None,
    flat_z: float | None = None,
    plane: tuple[float, float, float] | None = None,
) -> str: ...
def timeline_key(trace_sha256: str, height_field_digest: str, catalog_digest: str | None = None) -> str: ...
def trace_sha256(trace: bytes | str) -> str: ...
def compare_observed(
    timeline: Timeline, observed_jsonl: str, profile: str | dict[str, Any] | None = None
) -> dict[str, Any]: ...
