"use client";
import type { CSSProperties, ReactNode } from "react";
import * as stylex from "@stylexjs/stylex";
import { LoaderCircle } from "lucide-react";
import { SkyCloudBackdrop } from "./SkyCloudBackdrop";
import { mergeStyleProps } from "./stylex/surface";
import { styles } from "./CloudLoadingSurface.stylex";

export type CloudLoadingTelemetry = { transferred: string; total?: string | null; speed?: string | null; eta?: string | null; stalled?: boolean; stalledFor?: string | null };
export type CloudLoadingSurfaceProps = { scope?: "screen" | "pane" | "embedded"; eyebrow?: string; title: string; detail?: string | null; progress?: number | null; progressLabel?: string; progressValueLabel?: string; telemetry?: CloudLoadingTelemetry | null; icon?: ReactNode; children?: ReactNode; className?: string; xstyle?: stylex.StyleXStyles; style?: CSSProperties; backdropClassName?: string; contentWrapClassName?: string; contentClassName?: string; testId?: string; contentTestId?: string; telemetryTestId?: string; role?: "status" | "alert"; ariaBusy?: boolean; ariaHidden?: boolean; dataLoadKind?: string; dataLoadPhase?: string; dataTransitionState?: "covering" | "revealing" };

export function CloudLoadingSurface({ scope = "pane", eyebrow = "SimForge", title, detail, progress, progressLabel = "Loading", progressValueLabel, telemetry, icon, children, className, xstyle, style, backdropClassName, contentWrapClassName, contentClassName, testId = "cloud-loading-surface", contentTestId = "cloud-loading-content", telemetryTestId = "cloud-loading-telemetry", role = "status", ariaBusy = role !== "alert", ariaHidden = false, dataLoadKind, dataLoadPhase, dataTransitionState }: CloudLoadingSurfaceProps) {
  const normalizedProgress = normalizeProgress(progress); const hasProgress = progress !== undefined;
  return <div aria-busy={ariaBusy} aria-hidden={ariaHidden || undefined} aria-live={role === "alert" ? "assertive" : "polite"} {...mergeStyleProps(stylex.props(styles.root, scope === "screen" && styles.screen, scope === "pane" && styles.pane, scope === "embedded" && styles.embedded, xstyle), className, style)} data-cloud-loading-scope={scope} data-load-kind={dataLoadKind} data-load-phase={dataLoadPhase} data-transition-state={dataTransitionState} data-testid={testId} role={role}>
    <SkyCloudBackdrop animated={scope !== "pane"} className={backdropClassName} />
    <div {...mergeStyleProps(stylex.props(styles.wrap), contentWrapClassName)}><div {...mergeStyleProps(stylex.props(scope === "pane" ? styles.paneContent : styles.fullContent), contentClassName)} data-testid={contentTestId}>
      <div {...stylex.props(styles.row)}><div {...stylex.props(styles.icon)}>{icon ?? <LoaderCircle aria-hidden="true" {...stylex.props(styles.spin)} />}</div><div {...stylex.props(styles.body)}><p {...stylex.props(styles.eyebrow)}>{eyebrow}</p><h2 {...stylex.props(styles.title, scope === "pane" ? styles.titlePane : styles.titleFull)}>{title}</h2>{detail ? <p {...stylex.props(styles.detail)}>{detail}</p> : null}{telemetry ? <CloudLoadingTelemetryPanel telemetry={telemetry} testId={telemetryTestId} /> : null}</div></div>
      {hasProgress ? <div {...stylex.props(styles.progressWrap)}><div aria-label={`${title} progress`} aria-valuemax={100} aria-valuemin={0} aria-valuenow={normalizedProgress ?? undefined} {...stylex.props(styles.progressTrack)} role="progressbar">{normalizedProgress == null ? <div {...stylex.props(styles.shimmer)} /> : <div {...stylex.props(styles.progressFill)} style={{ width: `${normalizedProgress}%` }} />}</div><div {...stylex.props(styles.progressMeta)}><span>{progressLabel}</span><span>{progressValueLabel ?? (normalizedProgress == null ? "Working" : `${normalizedProgress}%`)}</span></div></div> : null}
      {children}
    </div></div>
  </div>;
}
export function CloudActivityIndicator({ label, className, xstyle, iconXstyle, testId }: { label?: string; className?: string; xstyle?: stylex.StyleXStyles; iconXstyle?: stylex.StyleXStyles; testId?: string }) { return <span {...mergeStyleProps(stylex.props(styles.activity, xstyle), className)} data-testid={testId} role={label ? "status" : undefined}><LoaderCircle aria-hidden="true" {...stylex.props(styles.activityIcon, iconXstyle)} />{label ? <span>{label}</span> : null}</span>; }
function CloudLoadingTelemetryPanel({ telemetry, testId }: { telemetry: CloudLoadingTelemetry; testId: string }) { return <div {...stylex.props(styles.telemetry, telemetry.stalled && styles.telemetryStalled)} data-testid={testId}><div {...stylex.props(styles.telemRow)}><span>{telemetry.transferred}{telemetry.total ? ` / ${telemetry.total}` : " downloaded"}</span>{telemetry.speed ? <span>{telemetry.speed}</span> : null}</div>{telemetry.eta ? <p {...stylex.props(styles.telemText)}>{telemetry.eta} remaining</p> : null}{telemetry.stalled ? <p {...stylex.props(styles.telemWarn)}>No bytes received for {telemetry.stalledFor ?? "several seconds"}</p> : null}</div>; }
function normalizeProgress(progress: number | null | undefined) { if (progress == null || !Number.isFinite(progress)) return null; return Math.max(0, Math.min(100, Math.round(progress))); }
