import * as stylex from "@stylexjs/stylex";

export const hoverScale = stylex.defineVars({ value: "1" });
export const hoverBrightness = stylex.defineVars({ value: "1" });
export const progressHeight = stylex.defineVars({ value: "3px" });
export const thumbScale = stylex.defineVars({ value: "0" });
const primary = "hsl(var(--primary))";

export const styles = stylex.create({
  root: {
    position: "relative",
    aspectRatio: "16 / 9",
    overflow: "hidden",
    backgroundColor: "black",
    [hoverScale.value]: "1",
    [hoverBrightness.value]: "1",
    ":hover": {
      [hoverScale.value]: "1.03",
      [hoverBrightness.value]: "1.1",
    },
  },
  video: {
    display: "block",
    height: "100%",
    width: "100%",
    objectFit: "cover",
    transform: `scale(${hoverScale.value})`,
    filter: `brightness(${hoverBrightness.value})`,
    transitionProperty: "transform, filter",
    transitionDuration: "300ms",
  },
  overlay: {
    pointerEvents: "none",
    position: "absolute",
    insetInline: 0,
    top: 0,
    zIndex: 20,
    display: "flex",
    height: "3.5rem",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "0.75rem",
    backgroundImage:
      "linear-gradient(to bottom, rgb(0 0 0 / 75%), rgb(0 0 0 / 35%), transparent)",
    paddingInline: "0.75rem",
    paddingBlock: "0.5rem",
  },
  labelWrap: { minWidth: 0 },
  eyebrow: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "10px",
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: "0.14em",
    color: "rgb(255 255 255 / 55%)",
  },
  label: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "0.75rem",
    fontWeight: 600,
    textTransform: "capitalize",
    color: "white",
    textShadow: "0 1px 3px rgb(0 0 0 / 100%)",
  },
  badge: { pointerEvents: "auto", flexShrink: 0 },
  progressArea: {
    position: "absolute",
    insetInline: 0,
    bottom: 0,
    zIndex: 30,
    display: "flex",
    height: "1rem",
    cursor: "pointer",
    alignItems: "flex-end",
    opacity: 0,
    transitionProperty: "opacity",
    transitionDuration: "150ms",
    ":hover": { opacity: 1 },
  },
  progressAreaScrubbing: { opacity: 1 },
  progressTrack: {
    [progressHeight.value]: "3px",
    height: progressHeight.value,
    width: "100%",
    backgroundColor: "rgb(255 255 255 / 15%)",
    transitionProperty: "height",
    transitionDuration: "150ms",
    ":hover": { [progressHeight.value]: "5px" },
  },
  progressTrackScrubbing: { [progressHeight.value]: "5px" },
  progress: {
    position: "relative",
    height: "100%",
    backgroundColor: primary,
    transitionProperty: "width",
    transitionDuration: "75ms",
  },
  thumb: {
    [thumbScale.value]: "0",
    position: "absolute",
    right: "-5px",
    top: "50%",
    width: "0.625rem",
    height: "0.625rem",
    borderRadius: "9999px",
    backgroundColor: primary,
    transform: `translateY(-50%) scale(${thumbScale.value})`,
    transitionProperty: "transform",
    transitionDuration: "150ms",
    ":hover": { [thumbScale.value]: "1" },
  },
  thumbScrubbing: { [thumbScale.value]: "1" },
  empty: {
    position: "absolute",
    inset: 0,
    zIndex: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgb(9 9 11)",
    paddingInline: "1.5rem",
    textAlign: "center",
    fontFamily: "monospace",
    fontSize: "10px",
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    color: "rgb(255 255 255 / 35%)",
  },
});
