import * as stylex from "@stylexjs/stylex";
import { colors, layers, motion, space, text } from "../stylex/tokens.stylex";

export const hoverScale = stylex.defineVars({ value: "1" });
export const hoverBrightness = stylex.defineVars({ value: "1" });
export const progressHeight = stylex.defineVars({ value: "3px" });
export const thumbScale = stylex.defineVars({ value: "0" });

export const styles = stylex.create({
  root: {
    position: "relative",
    aspectRatio: "16 / 9",
    overflow: "hidden",
    backgroundColor: "black",
    [hoverScale.value]: "1",
    [hoverBrightness.value]: "1",
    ":hover": {
      [hoverScale.value]: "1.03",
      [hoverBrightness.value]: "1.1",
    },
  },
  video: {
    display: "block",
    height: "100%",
    width: "100%",
    objectFit: "cover",
    transform: `scale(${hoverScale.value})`,
    filter: `brightness(${hoverBrightness.value})`,
    transitionProperty: "transform, filter",
    transitionDuration: motion.durSlow,
  },
  overlay: {
    pointerEvents: "none",
    position: "absolute",
    insetInline: 0,
    top: 0,
    zIndex: layers.float,
    display: "flex",
    height: "3.5rem",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: space.s3,
    backgroundImage:
      "linear-gradient(to bottom, rgb(0 0 0 / 75%), rgb(0 0 0 / 35%), transparent)",
    paddingInline: space.s3,
    paddingBlock: space.s2,
  },
  labelWrap: { minWidth: 0 },
  eyebrow: {
    color: colors.inkMuted,
  },
  label: {
    fontSize: text.sizeXs, lineHeight: text.lineXs,
    fontWeight: text.weightSemibold,
    textTransform: "capitalize",
    color: colors.ink,
    textShadow: "0 1px 3px rgb(0 0 0 / 100%)",
  },
  badge: { pointerEvents: "auto", flexShrink: 0 },
  progressArea: {
    position: "absolute",
    insetInline: 0,
    bottom: 0,
    zIndex: layers.sticky,
    display: "flex",
    height: "1rem",
    cursor: "pointer",
    alignItems: "flex-end",
    opacity: 0,
    transitionProperty: "opacity",
    transitionDuration: motion.durStandard,
    ":hover": { opacity: 1 },
  },
  progressAreaScrubbing: { opacity: 1 },
  progressTrack: {
    [progressHeight.value]: "3px",
    height: progressHeight.value,
    width: "100%",
    backgroundColor: colors.fillStronger,
    transitionProperty: "height",
    transitionDuration: motion.durStandard,
    ":hover": { [progressHeight.value]: "5px" },
  },
  progressTrackScrubbing: { [progressHeight.value]: "5px" },
  progress: {
    position: "relative",
    height: "100%",
    backgroundColor: colors.primary,
    transitionProperty: "width",
    transitionDuration: motion.durInstant,
  },
  thumb: {
    [thumbScale.value]: "0",
    position: "absolute",
    right: "-5px",
    top: "50%",
    width: "0.625rem",
    height: "0.625rem",
    backgroundColor: colors.primary,
    transform: `translateY(-50%) scale(${thumbScale.value})`,
    transitionProperty: "transform",
    transitionDuration: motion.durStandard,
    ":hover": { [thumbScale.value]: "1" },
  },
  thumbScrubbing: { [thumbScale.value]: "1" },
  empty: {
    position: "absolute",
    inset: 0,
    zIndex: layers.raised,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgb(9 9 11)",
    paddingInline: space.s6,
    textAlign: "center",
    color: colors.inkFaint,
  },
});
