import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { packClosure } from '../../../scripts/actor-assets/closures.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../../catalog/pedestrians-carla');
const { pedestrians } = JSON.parse(readFileSync(resolve(root, 'manifest.json'), 'utf8')) as {
  pedestrians: Record<string, { file: string; display: string; age: string; dims_xyz_m: number[]; clips: Record<string, unknown> }>;
};
// Per-clip grounding lifts measured at ingest (tools/ground.py, emitted by
// tools/finalize.py): the one derivation both renderers use.
const { entries: sidecar } = JSON.parse(readFileSync(resolve(root, 'catalog-models.json'), 'utf8')) as {
  entries: Record<string, { model: { clipGroundOffsetM?: Record<string, number> } }>;
};
// Content hashes come from the pack's sealed closure: the models are not in git.
const sealed = packClosure('pedestrians-carla');
const bindings: string[] = [];
const entries: string[] = [];
for (const [blueprint, item] of Object.entries(pedestrians).sort(([a], [b]) => a.localeCompare(b))) {
  if (!item.clips.walk || !item.clips.idle) throw new Error(`${blueprint}: missing locomotion clips`);
  const hash = sealed.members.get(item.file)?.sha256;
  if (!hash) throw new Error(`${blueprint}: ${item.file} is not a member of the sealed pedestrians-carla closure; run scripts/actor-assets/seal-packs.mjs seal`);
  const lifts = sidecar[blueprint]?.model.clipGroundOffsetM;
  if (typeof lifts?.idle !== 'number' || typeof lifts.locomotion !== 'number') {
    throw new Error(`${blueprint}: catalog-models.json has no measured clipGroundOffsetM; run tools/ground.py and tools/finalize.py`);
  }
  bindings.push(`  '${blueprint}': { kind: 'glb', url: '/catalog/pedestrians-carla/${item.file}', contentHash: '${hash}', yawRad: Math.PI / 2, animated: true, clips: { idle: 'idle', locomotion: 'walk' }, groundOffsets: { idle: ${lifts.idle}, locomotion: ${lifts.locomotion} } },`);
  const id = blueprint.replace('walker.pedestrian.', 'pedestrian.carla.');
  // Source gait advances along +Z; the binding rotates it onto actor +X.
  const [w, h, l] = item.dims_xyz_m;
  entries.push(`  { id: '${id}', label: '${item.display}', class: 'pedestrian', description: 'CARLA ${item.age} pedestrian with native in-place walk, idle and run clips.', dims: { l: ${l}, w: ${w}, h: ${h} }, tags: ['vru', 'occlusion:low', 'sidewalk'], defaultParams: { height: ${h}, pose: 'standing' }, model: CARLA_PEDESTRIAN_MODELS['${blueprint}'] },`);
}
writeFileSync(resolve(here, '../src/pedestrians-carla.generated.ts'), `// Generated by scripts/generate-pedestrian-models.ts. Do not edit by hand.
import type { CatalogEntry, ExternalModelBinding } from './types';

export const CARLA_PEDESTRIAN_MODELS = {
${bindings.join('\n')}
} as const satisfies Readonly<Record<string, ExternalModelBinding>>;

export const CARLA_PEDESTRIAN_ENTRIES = [
${entries.join('\n')}
] as const satisfies readonly CatalogEntry[];
`);
console.log(`Generated ${bindings.length} animated pedestrian bindings and selectable entries`);
