import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../../catalog/pedestrians-carla');
const { pedestrians } = JSON.parse(readFileSync(resolve(root, 'manifest.json'), 'utf8')) as {
  pedestrians: Record<string, { file: string; display: string; age: string; dims_xyz_m: number[]; clips: Record<string, unknown> }>;
};
const bindings: string[] = [];
const entries: string[] = [];
for (const [blueprint, item] of Object.entries(pedestrians).sort(([a], [b]) => a.localeCompare(b))) {
  if (!item.clips.walk || !item.clips.idle) throw new Error(`${blueprint}: missing locomotion clips`);
  const hash = createHash('sha256').update(readFileSync(resolve(root, item.file))).digest('hex');
  bindings.push(`  '${blueprint}': { kind: 'glb', url: '/catalog/pedestrians-carla/${item.file}', contentHash: '${hash}', animated: true, clips: { idle: 'idle', locomotion: 'walk' } },`);
  const id = blueprint.replace('walker.pedestrian.', 'pedestrian.carla.');
  const [l, h, w] = item.dims_xyz_m;
  entries.push(`  { id: '${id}', label: '${item.display}', class: 'pedestrian', description: 'CARLA ${item.age} pedestrian with native in-place walk, idle and run clips.', dims: { l: ${l}, w: ${w}, h: ${h} }, tags: ['vru', 'occlusion:low', 'sidewalk'], defaultParams: { height: ${h}, pose: 'standing' }, model: CARLA_PEDESTRIAN_MODELS['${blueprint}'] },`);
}
writeFileSync(resolve(here, '../src/pedestrians-carla.generated.ts'), `// Generated by scripts/generate-pedestrian-models.ts. Do not edit by hand.
import type { CatalogEntry, ExternalModelBinding } from './types';

export const CARLA_PEDESTRIAN_MODELS = {
${bindings.join('\n')}
} as const satisfies Readonly<Record<string, ExternalModelBinding>>;

export const CARLA_PEDESTRIAN_ENTRIES = [
${entries.join('\n')}
] as const satisfies readonly CatalogEntry[];
`);
console.log(`Generated ${bindings.length} animated pedestrian bindings and selectable entries`);
