/**
 * Emit `catalog.json` from the code catalog, validating it on the way out.
 *
 * The JSON is the artefact non-three.js consumers (agents, tooling, other
 * services) read; keeping it generated means the code is the single source of
 * truth and the two can never disagree.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { CATALOG, CATALOG_ALIASES } from '../src/catalog.js';
import { catalogSchema } from '../src/schema.js';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '..', 'catalog.json');
const carlaSource = resolve(here, '../../../studio/app/generated/carla-object-catalog.json');
const carlaOut = resolve(here, '../src/carla-object-catalog.generated.ts');
const carlaCatalog = JSON.parse(readFileSync(carlaSource, 'utf8')) as {
  objects: Array<Record<string, unknown>>;
};
const carla = `// Generated from studio/app/generated/carla-object-catalog.json. Do not edit by hand.
import type { CatalogEntry, ExternalModelBinding } from './types';

type CarlaObjectCatalogEntry = Omit<CatalogEntry, 'id' | 'model'> & { readonly id: string; readonly model: ExternalModelBinding };

export const CARLA_OBJECT_CATALOG: readonly CarlaObjectCatalogEntry[] = [
${carlaCatalog.objects.map((entry) => {
  const json = (value: unknown) => JSON.stringify(value).replace(/"([^"]+)":/g, '$1: ').replaceAll(',', ', ');
  return `  { id: ${json(entry.id)}, label: ${json(entry.label)}, class: ${json(entry.class)}, actorClass: ${json(entry.actorClass)}, description: ${json(entry.description)}, dims: ${json(entry.dims)}, tags: ${json(entry.tags)}, defaultParams: ${json(entry.defaultParams)}, model: { kind: 'proxy' } },`;
}).join('\n')}
] as const;

`;
const parsed = catalogSchema.parse(CATALOG);
const rustOut = resolve(here, '../../../native/crates/simforge-core/src/catalog_aliases.generated.rs');
const rust = `// Generated by packages/asset-catalog/scripts/generate-catalog.ts. Do not edit.
pub const CATALOG_ALIASES: &[(&str, &str)] = &[
${Object.entries(CATALOG_ALIASES).map(([alias, target]) => `    (${JSON.stringify(alias)}, ${JSON.stringify(target)}),`).join('\n')}
];

pub fn canonical_catalog_id(id: &str) -> &str {
    CATALOG_ALIASES.iter().find(|(alias, _)| *alias == id).map_or(id, |(_, target)| *target)
}
`;
const targets: Array<[path: string, content: string]> = [
  [out, `${JSON.stringify(parsed, null, 2)}\n`],
  [rustOut, rust],
  [carlaOut, carla],
];
for (const [path, content] of targets) {
  if (process.argv.includes('--check')) {
    if (readFileSync(path, 'utf8') !== content) throw new Error(`Generated catalog drift: ${path}`);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, 'utf8');
  }
}

const byClass = new Map<string, number>();
for (const entry of parsed) byClass.set(entry.class, (byClass.get(entry.class) ?? 0) + 1);
const summary = [...byClass.entries()].map(([cls, n]) => `${cls}=${n}`).join(' ');
process.stdout.write(`catalog.json: ${parsed.length} entries (${summary})\n`);
