/**
 * Layout of the map download panel, plus the few looks that belong to it
 * alone (the storage meter's segments, the road the progress car drives on,
 * a tile's selected edge). Every value is a token.
 */
import * as stylex from "@stylexjs/stylex";
import { colors, layout, motion, space, stroke, text } from "../stylex/tokens.stylex";

/** A tile publishes its hover so the city inside it can wake up. */
export const tileMarker = stylex.defineMarker();

export const styles = stylex.create({
  root: {
    position: "relative",
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr) auto",
    minWidth: 0,
    minHeight: 0,
    height: "100%",
    color: colors.ink,
  },
  scroller: {
    display: "grid",
    alignContent: "start",
    gap: space.s5,
    minWidth: 0,
    minHeight: 0,
    overflowY: "auto",
    paddingBottom: space.s4,
    scrollbarWidth: "thin",
  },

  header: {
    display: "flex",
    flexDirection: { default: "column", [layout.bpMd]: "row" },
    alignItems: { default: "stretch", [layout.bpMd]: "flex-end" },
    justifyContent: "space-between",
    gap: space.s3,
    minWidth: 0,
  },
  headerText: { display: "grid", gap: space.s1_5, minWidth: 0, maxWidth: layout.formMeasure },
  title: { margin: 0 },
  lede: { margin: 0 },
  headerStats: { display: "flex", flexWrap: "wrap", gap: space.s2 },

  /** Stage beside settings from LG; stacked on narrower screens. */
  top: {
    display: "grid",
    gap: space.s3,
    gridTemplateColumns: { default: "minmax(0, 1fr)", [layout.bpLg]: "minmax(0, 1.35fr) minmax(0, 1fr)" },
    alignItems: "stretch",
  },

  stage: {
    position: "relative",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto auto",
    gap: space.s3,
    minWidth: 0,
    padding: { default: space.s3, [layout.bpSm]: space.s4 },
    overflow: "hidden",
  },
  stageHead: { display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: space.s3, minWidth: 0 },
  stageName: { display: "flex", alignItems: "center", gap: space.s2, minWidth: 0 },
  headlineIcon: { flexShrink: 0, color: colors.accent },
  stageCity: {
    // Several breakpoints on one property are literal queries (see the style guide).
    height: { default: "11rem", "@media (min-width: 640px)": "14rem", "@media (min-width: 1024px)": "16rem" },
    minHeight: 0,
  },
  stageEmpty: {
    display: "grid",
    placeItems: "center",
    height: "100%",
    textAlign: "center",
    paddingInline: space.s6,
  },
  stats: {
    display: "grid",
    gridTemplateColumns: { default: "repeat(2, minmax(0, 1fr))", [layout.bpSm]: "repeat(4, minmax(0, 1fr))" },
    gap: space.s2,
    margin: 0,
  },
  stat: { display: "grid", gap: space.s0_5, minWidth: 0 },
  statValue: { margin: 0, fontSize: text.sizeBase, lineHeight: text.lineBase, color: colors.ink },
  sparkline: { display: "block", width: "100%", height: "1.25rem", overflow: "visible" },
  sparkPath: { fill: "none", stroke: colors.accentLine, strokeWidth: 1.5, vectorEffect: "non-scaling-stroke" },
  sparkArea: { fill: colors.accentWash, stroke: "none" },

  /** The road the progress car drives along: paved (lit) behind it. */
  road: {
    position: "relative",
    height: "2rem",
    marginInline: space.s1,
  },
  roadBed: {
    position: "absolute",
    insetInline: 0,
    bottom: space.s1,
    height: space.s1,
    backgroundColor: colors.fillStrong,
    backgroundImage: `repeating-linear-gradient(90deg, ${colors.inkGhost} 0 0.5rem, transparent 0.5rem 1rem)`,
    backgroundSize: "100% 1px",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
  },
  roadPaved: {
    position: "absolute",
    insetInlineStart: 0,
    bottom: space.s1,
    height: space.s1,
    width: "calc(var(--road-progress, 0) * 100%)",
    backgroundColor: colors.accent,
    transitionProperty: "width",
    transitionDuration: { default: motion.durSlow, [layout.reducedMotion]: "0s" },
    transitionTimingFunction: motion.easeStandard,
  },
  car: {
    position: "absolute",
    bottom: space.s2,
    // The car stops short of the finish flag, which lights when it arrives.
    left: "calc(var(--road-progress, 0) * (100% - 2.75rem))",
    width: "1.5rem",
    height: "1.5rem",
    color: colors.accent,
    transitionProperty: "left",
    transitionDuration: { default: motion.durSlow, [layout.reducedMotion]: "0s" },
    transitionTimingFunction: motion.easeStandard,
  },
  carIdle: { color: colors.inkMuted },
  flag: {
    position: "absolute",
    insetInlineEnd: 0,
    bottom: space.s2,
    width: "1rem",
    height: "1rem",
    color: colors.inkFaint,
    transitionProperty: "color",
    transitionDuration: { default: motion.durSlow, [layout.reducedMotion]: "0s" },
  },
  flagDone: { color: colors.accent },

  side: { display: "grid", alignContent: "start", gap: space.s3, minWidth: 0 },
  section: { display: "grid", gap: space.s2_5, minWidth: 0, padding: { default: space.s3, [layout.bpSm]: space.s4 } },
  sectionHead: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: space.s2, minWidth: 0 },

  choices: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: space.s1_5 },
  choice: {
    display: "grid",
    alignContent: "start",
    gap: space.s1,
    minWidth: 0,
    minHeight: "4.25rem",
    padding: space.s2_5,
    textAlign: "start",
    backgroundColor: { default: colors.fillSubtle, ":hover": colors.fill },
    color: colors.ink,
  },
  choiceCurrent: { borderColor: colors.accentLine, backgroundColor: colors.accentWash },
  choiceName: { fontSize: text.sizeXs, fontWeight: text.weightSemibold, lineHeight: text.lineXs },
  choiceSize: { color: colors.inkMuted },
  choiceSizeCurrent: { color: colors.accent },

  meter: {
    position: "relative",
    height: space.s2,
    overflow: "hidden",
    backgroundColor: colors.fillStrong,
  },
  meterCached: {
    position: "absolute",
    insetBlock: 0,
    insetInlineStart: 0,
    width: "calc(min(var(--meter-cached, 0), 1) * 100%)",
    backgroundColor: colors.inkMuted,
  },
  meterIncoming: {
    position: "absolute",
    insetBlock: 0,
    left: "calc(min(var(--meter-cached, 0), 1) * 100%)",
    width: "calc(max(0, min(var(--meter-incoming, 0), 1 - var(--meter-cached, 0))) * 100%)",
    backgroundColor: colors.accent,
    transitionProperty: "width",
    transitionDuration: { default: motion.durBase, [layout.reducedMotion]: "0s" },
  },
  meterOver: { backgroundColor: colors.critical },
  legend: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    columnGap: space.s3,
    rowGap: space.s1_5,
    margin: 0,
  },
  legendItem: { display: "grid", gap: space.s0_5, minWidth: 0 },
  legendValue: { margin: 0, color: colors.ink },
  swatch: { display: "inline-block", width: space.s2, height: space.s2, marginInlineEnd: space.s1_5 },
  swatchCached: { backgroundColor: colors.inkMuted },
  swatchIncoming: { backgroundColor: colors.accent },
  presets: { display: "flex", flexWrap: "wrap", gap: space.s1_5, alignItems: "center" },
  confirm: { display: "grid", gap: space.s2, padding: space.s3, backgroundColor: colors.criticalWash },
  confirmActions: { display: "flex", flexWrap: "wrap", gap: space.s2 },

  notice: { display: "flex", alignItems: "flex-start", gap: space.s2, padding: space.s3, margin: 0 },
  noticeWarning: { backgroundColor: colors.warningWash, color: colors.warning },
  noticeCritical: { backgroundColor: colors.criticalWash, color: colors.critical },
  noticeInfo: { backgroundColor: colors.fillSubtle, color: colors.inkSecondary },
  noticeIcon: { width: "1rem", height: "1rem", flexShrink: 0, marginTop: space.s0_5 },
  noticeText: { margin: 0, minWidth: 0 },

  mapsHead: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.s2,
  },
  mapsHeadActions: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: space.s2 },
  tiles: {
    display: "grid",
    gap: space.s2,
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 640px)": "repeat(2, minmax(0, 1fr))",
      "@media (min-width: 1024px)": "repeat(3, minmax(0, 1fr))",
      "@media (min-width: 1280px)": "repeat(4, minmax(0, 1fr))",
    },
  },
  tile: {
    position: "relative",
    display: "grid",
    gridTemplateRows: "auto auto",
    minWidth: 0,
    overflow: "hidden",
    backgroundColor: { default: colors.fillFaint, ":hover": colors.fillSubtle },
  },
  tileSelected: { borderColor: colors.accentLineSubtle, backgroundColor: colors.accentWash },
  tileUnavailable: { opacity: 0.6 },
  tileArt: {
    position: "relative",
    height: "6.5rem",
    paddingBlock: space.s2,
    paddingInline: space.s3,
    backgroundSize: "cover",
    backgroundPosition: "center",
  },
  /** The thumbnail sits under the city, dimmed, so the blocks read first. */
  tileThumb: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    opacity: { default: 0.14, [stylex.when.ancestor(":hover", tileMarker)]: 0.24 },
    filter: "grayscale(1)",
    transitionProperty: "opacity",
    transitionDuration: { default: motion.durBase, [layout.reducedMotion]: "0s" },
  },
  tileCity: { position: "relative", height: "100%" },
  tileCheck: { position: "absolute", top: space.s2, insetInlineStart: space.s2 },
  /** An opaque plate under the state chip: the city behind it must not bleed through its wash. */
  tileBadge: { position: "absolute", top: space.s2, insetInlineEnd: space.s2, display: "inline-flex", backgroundColor: colors.panelSolid },
  tileBody: { display: "grid", gap: space.s1, minWidth: 0, paddingInline: space.s3, paddingBlock: space.s2_5 },
  tileRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: space.s2, minWidth: 0 },
  tileName: { minWidth: 0, fontSize: text.sizeSm, fontWeight: text.weightMedium, lineHeight: text.lineSm, color: colors.ink },
  tileReason: { margin: 0, color: colors.critical },
  checkbox: { width: "1rem", height: "1rem", accentColor: colors.accent, cursor: "pointer" },
  /** The whole tile toggles selection; the label covers it under the controls. */
  tileHit: { position: "absolute", inset: 0, cursor: "pointer" },
  tileControls: { position: "relative", display: "flex", alignItems: "center", gap: space.s1 },

  bar: {
    display: "flex",
    flexDirection: { default: "column", [layout.bpSm]: "row" },
    alignItems: { default: "stretch", [layout.bpSm]: "center" },
    justifyContent: "space-between",
    gap: space.s3,
    paddingBlock: space.s3,
    paddingInline: { default: space.s3, [layout.bpSm]: space.s4 },
    backgroundColor: colors.panel,
    borderTopWidth: stroke.hairline,
    borderTopStyle: "solid",
    borderTopColor: colors.hairline,
  },
  barSummary: { display: "grid", gap: space.s0_5, minWidth: 0 },
  barHint: { display: { default: "none", [layout.bpSm]: "block" } },
  barActions: { display: "flex", flexWrap: "wrap", gap: space.s2, justifyContent: "flex-end" },
  icon: { width: "1rem", height: "1rem" },
});
