import * as stylex from "@stylexjs/stylex";
import { colors, layers, motion, space, stroke, text } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

export const hovered = stylex.defineVars({
railIconOpacity: "0"
});

export const styles = stylex.create({
  openPanelButton: {
    flexShrink: 0,
    borderLeftWidth: stroke.hairline,
    borderLeftStyle: "solid",
    borderColor: colors.border,
    backgroundColor: { default: colors.bg, ":hover": colors.muted },
    display: "flex",
    alignItems: "center",
    paddingInline: space.s1_5,
  },
  openPanelButtonContent: {
    display: "flex",
    alignItems: "center",
    gap: space.s1_5,
    writingMode: "vertical-lr",
    transform: "rotate(180deg)",
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: { default: colors.mutedForeground, ":hover": colors.text },
    paddingBlock: space.s3,
  },
  openPanelIcon: {
    width: "0.875rem",
    height: "0.875rem",
    transform: "rotate(90deg)",
  },
  panelContainer: {
    position: "relative",
    width: "24rem",
    flexShrink: 0,
    minHeight: 0,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  collapsePanelButton: {
    position: "absolute",
    top: "0",
    bottom: "0",
    left: "0",
    zIndex: layers.float,
    width: "1rem",
    transform: "translateX(-50%)",
    transitionProperty: "all",
    transitionTimingFunction: motion.easeLinear,
    transitionDuration: motion.durStandard,
    cursor: "e-resize",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    [hovered.railIconOpacity]: "0",
    ":hover": {
      [hovered.railIconOpacity]: "1",
    },
    "::after": {
      content: '""',
      position: "absolute",
      top: "0",
      bottom: "0",
      left: "50%",
      transform: "translateX(-50%)",
      transitionProperty: "all",
      transitionTimingFunction: motion.easeStandard,
      transitionDuration: motion.durStandard,
      width: { default: "2px", ":hover": "0.25rem" },
      backgroundColor: { default: null, ":hover": "hsl(var(--primary) / 0.4)" },
    },
  },
  collapsePanelIcon: {
    width: "0.75rem",
    height: "0.75rem",
    color: colors.mutedForeground,
    opacity: hovered.railIconOpacity,
    transitionProperty: "opacity",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durStandard,
  },
  panelContent: {
    width: "100%",
    borderLeftWidth: stroke.hairline,
    borderLeftStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.bg,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  tabsContainer: {
    flex: "1 1 0%",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  tabList: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    flexShrink: 0,
    width: "100%",
    borderBottomWidth: stroke.hairline,
    borderBottomStyle: "solid",
    borderColor: colors.border,
    height: "2.5rem",
    backgroundColor: "transparent",
    padding: 0,
  },
  tabTrigger: {
    gap: space.s1,
    borderBottomWidth: stroke.thick,
    borderBottomStyle: "solid",
    borderColor: { default: "transparent", "[data-state=active]": colors.primary },
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: { default: colors.mutedForeground, "[data-state=active]": colors.text },
    backgroundColor: { default: null, "[data-state=active]": "transparent" },
    boxShadow: { default: null, "[data-state=active]": "none" },
    minWidth: 0,
    paddingInline: space.s1,
  },
  tabIcon: {
    width: "0.875rem",
    height: "0.875rem",
    flexShrink: 0,
  },
  tabContent: {
    flex: "1 1 0%",
    overflowY: "auto",
    padding: space.s3,
    marginTop: 0,
    display: { default: null, "[data-state=inactive]": "none" },
  },
});
