import * as stylex from "@stylexjs/stylex";
import { colors, layers, motion, shadows, space, stroke, text } from "@simforge-oss/studio-ui/stylex/tokens.stylex";

export const styles = stylex.create({
  mapWorkspace: {
    position: "relative",
    display: "flex",
    height: "100%",
    flexDirection: "column",
  },
  overlayHeader: {
    display: "flex",
    height: "3rem",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: stroke.hairline,
    borderBottomStyle: "solid",
    borderColor: colors.hairline,
    backgroundColor: colors.bg,
    paddingInline: space.s3,
  },
  workspaceTitle: {
    fontSize: text.sizeXs,
    lineHeight: text.lineXs,
    color: colors.mutedForeground,
  },
  closeButton: {
    display: "grid",
    width: "2rem",
    height: "2rem",
    placeItems: "center",
    color: { default: colors.mutedForeground, ":hover": colors.text },
    backgroundColor: { default: null, ":hover": colors.muted },
  },
  controlIcon: {
    width: "1rem",
    height: "1rem",
  },
  finalizingBanner: {
    display: "flex",
    alignItems: "center",
    gap: space.s2,
    borderBottomWidth: stroke.hairline,
    borderBottomStyle: "solid",
    borderColor: colors.warning,
    backgroundColor: colors.warningWash,
    paddingInline: space.s4,
    paddingBlock: space.s2,
    fontSize: text.sizeSm,
    lineHeight: text.lineSm,
    color: colors.warning,
  },
  loadingIcon: {
    height: "1rem",
    width: "1rem",
    flexShrink: 0,
  },
  mainContent: {
    position: "relative",
    flex: "1 1 0%",
    display: "flex",
    minHeight: 0,
  },
  searchPanel: {
    position: "relative",
    width: "30rem",
    flexShrink: 0,
    minHeight: 0,
  },
  searchResultsContainer: {
    position: "absolute",
    inset: "0",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    borderRightWidth: stroke.hairline,
    borderRightStyle: "solid",
    borderColor: colors.hairline,
    backgroundColor: colors.bg,
  },
  collapseSearchButton: {
    position: "absolute",
    top: "1.25rem",
    right: "-1rem",
    zIndex: layers.float,
    display: "flex",
    width: "2rem",
    height: "2rem",
    alignItems: "center",
    justifyContent: "center",
    color: { default: colors.mutedForeground, ":hover": colors.text },
  },
  mapCanvas: {
    flex: "1 1 0%",
    position: "relative",
  },
  mapControls: {
    position: "absolute",
    top: "0.75rem",
    right: "0.75rem",
    zIndex: layers.float,
    display: "flex",
    alignItems: "center",
    gap: space.s1_5,
  },
  resetViewButton: {
    display: "inline-flex",
    width: "2rem",
    height: "2rem",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "hsl(var(--background) / 0.95)",
    backdropFilter: motion.blurMd,
    boxShadow: shadows.elevationSm,
    color: { default: colors.mutedForeground, ":hover": colors.text },
  },
  resetViewIcon: {
    width: "0.875rem",
    height: "0.875rem",
  },
  viewModeToggle: {
    display: "flex",
    backgroundColor: "hsl(var(--background) / 0.95)",
    padding: space.s0_5,
    boxShadow: shadows.elevationSm,
  },
  viewModeSegment: {
    paddingLeft: space.s2,
    paddingRight: space.s2,
    paddingTop: space.s1,
    paddingBottom: space.s1,
    fontSize: text.sizeMeta,
    fontWeight: text.weightMedium,
    textTransform: "uppercase",
  },
  viewModeSegmentActive: {
    backgroundColor: colors.text,
    color: colors.bg,
  },
  viewModeSegmentInactive: {
    color: { default: colors.mutedForeground, ":hover": colors.text },
  },
  floatingSearchBar: {
    position: "absolute",
    top: "0.75rem",
    left: "0.75rem",
    zIndex: layers.float,
    width: "30rem",
  },
  openSearchButton: {
    position: "relative",
    width: "100%",
    height: "2.5rem",
    paddingLeft: "2.25rem",
    paddingRight: space.s3,
    borderWidth: stroke.hairline,
    borderStyle: "solid",
    borderColor: { default: colors.accentLine, ":hover": colors.primary },
    backgroundColor: { default: "hsl(var(--background) / 0.95)", ":hover": colors.bg },
    backdropFilter: motion.blurMd,
    boxShadow: { default: "0 0 0 1px hsl(var(--primary)/0.15),0 4px 12px -2px hsl(var(--primary)/0.25)", ":hover": "0 0 0 1px hsl(var(--primary)/0.25),0 6px 16px -2px hsl(var(--primary)/0.35)" },
    display: "flex",
    alignItems: "center",
    fontSize: text.sizeSm,
    lineHeight: text.lineSm,
    color: { default: colors.inkSecondary, ":hover": colors.text },
    transitionProperty: "color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durStandard,
  },
  searchIcon: {
    pointerEvents: "none",
    position: "absolute",
    left: "0.75rem",
    top: "50%",
    width: "1rem",
    height: "1rem",
    transform: "translateY(-50%)",
    color: colors.primary,
  },
  searchResultCount: {
    marginTop: space.s1,
    paddingLeft: space.s1,
    fontSize: text.sizeMeta,
    color: colors.mutedForeground,
  },
  mapRendererContainer: {
    position: "absolute",
    inset: "0",
  },
});
