/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class CompileResult {
  get input(): ScenarioInput
  get manifestJson(): string
  /** Lowered observations (`LoweredObservation[]`). */
  get observationsJson(): string
}
export type JsCompileResult = CompileResult

export declare class EnvSession {
  constructor(input: ScenarioInput, graph: LaneGraph, episodeJson?: string | undefined | null, maxObjects?: number | undefined | null)
  get ego(): string
  get decisionHz(): number
  get decisionTicks(): number
  get clipSeconds(): number
  get maxObjects(): number
  get bevShape(): BevShape | null
  reset(seed?: number | string | undefined | null): StepResult
  /** `action` is one flat `Float64Array(ACTION_WIDTH)` row (NaN = unset) or `null` for choreography. */
  step(action?: Float64Array | undefined | null): StepResult
  checkpoint(): Buffer
  restore(checkpoint: Buffer): StepResult
  /** `[tS, x, y, yawRad, speedMps]`. */
  egoPose(): Float64Array
  /** Actors in the world at the observation instant; throws before `reset()`. */
  get actorCount(): number
  /** Canonical ids in snapshot order (the row order of `actors()`/`present()`/`actorDims`); throws before `reset()`. */
  get actorIds(): Array<string>
  get actorKinds(): Array<string>
  /** `Float64Array(N * 3)` rows `[l, w, h]`. */
  get actorDims(): Float64Array
  /** `Float64Array(N * ACTOR_ROW)` rows `[x, y, headingRad, speedMps, accelMps2, lateralOffsetM, lateralRateMps, s]` (xodr-local) at the observation instant. */
  actors(): Float64Array
  present(): Uint8Array
  signalBookJson(): string
  /** The accumulated `CausalChannel` of the current episode as JSON. */
  causalChannelJson(): string
}
export type JsEnvSession = EnvSession

export declare class LaneGraph {
  static fromTopology(data: Uint8Array): LaneGraph
  get digest(): string
  get byteDigest(): string
  get laneCount(): number
  get laneIds(): Array<string>
  laneLengthM(rsl: string): number
  /** `[rsl, s, d]` of the nearest drivable lane, or `null`. */
  nearestLane(x: number, y: number, maxDistM?: number | undefined | null): [string, number, number] | null
  laneWidthAt(rsl: string, s: number): number
  /** `[x, y, headingRad]` at arc length `s` measured along the traversal direction (`reversed` = from the last polyline point, storage `len - s`). */
  sampleLane(rsl: string, s: number, reversed?: boolean | undefined | null): Float64Array
  /** `[s, d]` projection of a point onto the lane polyline. */
  projectOntoLane(rsl: string, x: number, y: number): Float64Array
  /** Directed successors as `[rsl, reversed]` pairs. */
  successors(rsl: string, reversed?: boolean | undefined | null): Array<[string, boolean]>
  nominalReversed(rsl: string): boolean | null
  /** The decoded `TopologyLane` record as JSON. */
  laneJson(rsl: string): string
  /** Connected legal-direction lane chain for a newly placed road actor, or `null` when no route provides the runway. */
  defaultPlacementRoute(startRsl: string, startStorageS: number, requiredDownstreamM: number): JsPlacementRoute | null
  /** Lane rsls walking successors from `startRsl` consuming `turns` (`Straight|Left|Right|UTurnLeft|UTurnRight`); `null` when `strictTurns` finds a turn unavailable. */
  followRoute(startRsl: string, turns: Array<string>, maxLengthM: number, startReversed?: boolean | undefined | null, strictTurns?: boolean | undefined | null): Array<string> | null
  /** Resolve a `RouteSpec` document to a route handle; throws the `RouteBuildError` JSON on failure. */
  route(specJson: string): JsRoute
  /** Turn relation of the first gate whose connecting lane is `rsl`, or `null`. */
  turnRelationOf(rsl: string): string | null
}
export type JsLaneGraph = LaneGraph

export declare class MapBundle {
  /** Load an installed map directory from the immutable map corpus. */
  static load(path: string): MapBundle
  static fromTopology(mapId: string, topology: Uint8Array): MapBundle
  get mapId(): string
  get digest(): string
  /** `simforge.map-closure/v1`: identity of everything a simulation reads from this map. */
  get closureDigest(): string
  get graph(): LaneGraph
  /** Bundle from in-memory sources: `sourcesJson = {mapId, derived?, locations?, searchIndex?, xodr?, signalsGeojson?}` plus the topology sidecar bytes. */
  static fromSources(sourcesJson: string, topology: Uint8Array): MapBundle
  /**
   * Attach the map's ground surface (`derived/ground/ground-mesh.bin`);
   * returns its digest. Worlds built afterwards ground every body on it.
   */
  attachGround(groundMesh: Uint8Array): string
  get groundDigest(): string | null
  /** `{signalPrograms, roadControls}` bound from the map's signal catalog. */
  controlPlanJson(): string
  /** The merged `TopologyIndex`. */
  topologyJson(): string
  /** The `MapSignalCatalog`. */
  signalCatalogJson(): string
  signalControlIndexJson(): string
  controlPlanJsonWithCatalog(catalogJson: string): string
  signalControlIndexJsonWithCatalog(catalogJson: string): string
  signalControlIndexJsonWithPrograms(programsJson: string, catalogJson: string): string
  expandMapSignalMovementsJson(programsJson: string, plansJson: string): string
  compileSignalPlansJson(programsJson: string, plansJson: string, optionsJson: string, catalogJson: string): string
  selectSignalReferenceJson(indexJson: string, referenceJson: string): string | null
  evaluateSignalReferenceJson(indexJson: string, selectionJson: string, optionsJson: string): string
  /** The matcher's `DerivedMapIndex`. */
  indexJson(): string
  staticColliderDiagnosticsJson(): string
  /** `SiteSignalPlan` JSON for the site's origin junction. */
  siteSignalPlanJson(site: JsSite): string
  /** Resolve `{"handle": id}` | `{"featureId", "approach"}` to a concrete program id, or `null`. */
  resolveSiteSignalProgram(site: JsSite, refJson: string): string | null
}
export type JsMapBundle = MapBundle

/** A route re-based onto its lateral neighbour, plus where the actor lands on it. */
export declare class NeighbourRetarget {
  /** The rebuilt route on the neighbour lane. */
  get route(): Route
  /**
   * `{s, separationM, legal, targetRsl}` JSON: `s` on the new route,
   * the signed lane separation, whether the change is legal there, and the
   * lane it landed on.
   */
  get detailJson(): string
}
export type JsNeighbourRetarget = NeighbourRetarget

/** Deadline-accounted policy executor owning its `EnvSession`. */
export declare class PolicySession {
  constructor(input: ScenarioInput, graph: LaneGraph, episodeJson?: string | undefined | null, deadlineMs?: number | undefined | null, fallback?: string | undefined | null, execution?: string | undefined | null, maxObjects?: number | undefined | null)
  get ego(): string
  get execution(): string
  reset(seed?: number | string | undefined | null): StepResult
  actControl(throttle: number, brake: number, steer: number, elapsedMs?: number | undefined | null): PolicyStepResult
  /** `points` is `Float64Array(K * 5)` rows `[x, y, headingRad, speedMps, tS]` in the ego frame at issuance. */
  actTrajectory(points: Float64Array, elapsedMs?: number | undefined | null): PolicyStepResult
  /** Env continuation state plus the executor's held plan / last applied action. */
  checkpoint(): Buffer
  restore(checkpoint: Buffer): StepResult
  egoPose(): Float64Array
}
export type JsPolicySession = PolicySession

/** A resolved route: engine-frame geometry plus its persisted snapshot. */
export declare class Route {
  get lengthM(): number
  /** Empty for polyline routes. */
  get laneRsls(): Array<string>
  /** `[x, y, headingRad]` at arc length `s` (clamped). */
  poseAt(s: number): Float64Array
  /** `RouteSnapshot` JSON. */
  snapshotJson(): string
  /** `[s, d]` of the closest point on the route to `(x, y)`. */
  projectPoint(x: number, y: number): Float64Array
  /** `[s, d]` with an explicit coarse scan step (0.5 m for stop-line-grade matching). */
  projectPointWithStep(x: number, y: number, stepM: number): Float64Array
  /** Lane width at arc length `s` (clamped). */
  widthAt(s: number): number
  /** `[{rsl, reversed, sStartM, lengthM, turnRelation}]` JSON; empty for a polyline route. */
  legsJson(): string
  /** `{x, y, headingRad, rsl, laneS, storageS, reversed, legIndex}` JSON at `s`. */
  poseJson(s: number): string
  /**
   * Re-base onto the lateral neighbour at `s`; `null` when there is none.
   * `side` is the driver's side ("left" | "right").
   */
  retargetToNeighbour(s: number, side: string, legalOnly?: boolean | undefined | null, maxLengthM?: number | undefined | null): JsNeighbourRetarget | null
}
export type JsRoute = Route

export declare class ScenarioInput {
  /** Validate a scenario JSON document (string or bytes; raw input or `scenario-instance` envelope). */
  static parse(document: string | Uint8Array): ScenarioInput
  toJson(): string
  withSeed(seed: number | string): ScenarioInput
  withClipSeconds(clipSeconds: number): ScenarioInput
  get contentHash(): string
  get mapId(): string
  /** The authored seed as JSON (`number | string`). */
  get seedJson(): string
  get clipSeconds(): number
  get warmupSeconds(): number
  get dt(): number
  get metricSubject(): string | null
  get actorIds(): Array<string>
  get physicsMode(): string
}
export type JsScenarioInput = ScenarioInput

export declare class SessionBatch {
  constructor(inputs: Array<ScenarioInput>, graphs: Array<LaneGraph>, episodeJson?: string | undefined | null, threads?: number | undefined | null, maxObjects?: number | undefined | null)
  get size(): number
  get egos(): Array<string>
  get decisionHz(): number
  get maxObjects(): number
  get bevShape(): BevShape | null
  resetAll(seeds?: Array<number | string> | undefined | null): BatchResult
  /** Reset only `worlds`; `seeds[k]` (may be `null`) applies to `worlds[k]`. */
  resetWorlds(worlds: Array<number>, seeds?: Array<number | string | undefined | null> | undefined | null): BatchResult
  /** `actions` is `Float64Array(N * ACTION_WIDTH)`; `mask[i] == 0` skips world `i`. */
  stepBatch(actions: Float64Array, mask?: Uint8Array | undefined | null): BatchResult
  objectIds(world: number): Array<string>
  infoJson(world: number): string
  checkpoint(world: number): Buffer
  restore(world: number, checkpoint: Buffer): void
}
export type JsSessionBatch = SessionBatch

/** Bare engine world: explicit per-actor action batches, no episode semantics. */
export declare class Simulation {
  constructor(input: ScenarioInput, graph: LaneGraph, optionsJson?: string | undefined | null)
  get tS(): number
  get dtS(): number
  get tickIndex(): number
  get done(): boolean
  /** The completed run's `SimResult` JSON (`{input, trace, issues, arrival}`); errors until `done`. */
  resultJson(): string
  /** Recorded trace prefix; does not advance or finalize the simulation. */
  traceJson(): string
  inputJson(): string
  issuesJson(): string
  arrivalJson(): string
  get actorCount(): number
  get actorIds(): Array<string>
  get actorKinds(): Array<string>
  /** `Float64Array(N * 3)` rows `[l, w, h]`. */
  get actorDims(): Float64Array
  actorIndex(id: string): number
  /** `actions` is `Float64Array(K * (1 + ACTION_WIDTH))` rows `[actorIndex, ...action]`; returns `[ticksAdvanced, done ? 1 : 0]`. */
  advance(maxTicks: number, actions?: Float64Array | undefined | null): Array<number>
  /** `Float64Array(N * ACTOR_ROW)` rows `[x, y, headingRad, speedMps, accelMps2, lateralOffsetM, lateralRateMps, s]` (xodr-local). */
  actors(): Float64Array
  present(): Uint8Array
  laneRsls(): Array<string | undefined | null>
  minimaJson(): string
  drainEventsJson(): string
  signalStateJson(): string
  checkpoint(): Buffer
  restore(checkpoint: Buffer): void
}
export type JsSimulation = Simulation

/** One grounded matched site (native handle; `toJson()` for the `MatchedSite` document). */
export declare class Site {
  get siteId(): string
  get mapId(): string
  toJson(): string
}
export type JsSite = Site

export declare class Trace {
  /**
   * Parse plain or gzip trace JSON of any released format; older formats
   * are upgraded in memory (see `upgradeJson`), unknown ones rejected.
   */
  static parse(data: Uint8Array): Trace
  digest(): string
  /**
   * `simforge.trace-upgrade/v1` JSON when the stored trace was an older
   * format upgraded in memory; `null` for a current-format trace.
   */
  upgradeJson(): string | null
  toJson(): string
  sceneStateJson(): string
  metricsJson(): string
  evaluateJson(filtersJson?: string | undefined | null): string
  /** `IntentEvaluation` JSON for an intent rubric document. */
  intentRubricJson(rubricJson: string): string
  /** `BlindReviewPacket` JSON. */
  blindReviewPacketJson(rubricJson: string): string
  /** `BehaviorSummary` JSON; `limitsJson` is an optional camelCase `BehaviorSummaryLimits`. */
  behaviorSummaryJson(limitsJson?: string | undefined | null): string
  /** `InvariantResidualReport[]` JSON; `optionsJson = {scope?: ExprScope, arrival?: ArrivalSolution[], speedLimitKph?}`. */
  invariantsJson(templateJson: string, optionsJson?: string | undefined | null): string
}
export type JsTrace = Trace

/**
 * Contact-ownership handoff between an external traffic provider (browser SUMO) and the native contact solver.
 * Poses are scene ground-plane `x/z`; released bodies stay owned until `clear()`.
 */
export declare class TrafficHandoff {
  constructor()
  /** `StaticMapCollider[]` JSON (scene-frame OBBs) released bodies collide with; retained across `clear()`. */
  setStaticColliders(collidersJson: string): void
  /** Return every actor to its owner. */
  clear(): void
  /**
   * One provider interval. `authored`/`traffic` are `Float64Array(N * HANDOFF_ACTOR_ROW)` rows
   * `[x, z, headingRad, speedMps, lengthM, widthM, present, static]` with one id and kind per row.
   * Returns the number of traffic actors released to physics during this step.
   */
  step(dtS: number, authoredIds: Array<string>, authoredKinds: Array<string>, authored: Float64Array, trafficIds: Array<string>, trafficKinds: Array<string>, traffic: Float64Array): number
  get bodyCount(): number
  /** Traffic actors currently owned by physics. */
  get trafficBodyCount(): number
  /** Released body ids in `bodies()` row order. */
  bodyIds(): Array<string>
  /** `Float64Array(N * HANDOFF_BODY_ROW)` rows `[origin, x, z, headingRad, speedMps, angularVelocityRadS]`; `origin` 0 = traffic, 1 = authored. */
  bodies(): Float64Array
}
export type JsTrafficHandoff = TrafficHandoff

export declare class TruthSubscription {
  /** Every queued tick frame (JSON), oldest first. */
  drain(): Array<string>
  /** Every queued frame as `u32le length || msgpack(TruthFrame)` (the truth-stream wire framing). */
  drainFrames(): Array<Buffer>
  get dropped(): number
  get queued(): number
  get active(): boolean
  close(): void
}
export type JsTruthSubscription = TruthSubscription

export declare class WorldSession {
  /** `optionsJson`: `{mode?: "clip"|"live", horizonSeconds?}`. */
  constructor(input: ScenarioInput, graph: LaneGraph, optionsJson?: string | undefined | null)
  get time(): number
  get tick(): number
  get digest(): string
  /** Apply one `WorldCommand` JSON; returns the `CommandOutcome` JSON. */
  command(commandJson: string, clientId?: string | undefined | null, seq?: number | undefined | null): string
  /**
   * Hold one actor's pedals and wheel until replaced. Omit `throttle`,
   * `brake` and `steer` — pass `null` for the whole command — to release
   * the actor back to its scenario controller. Returns the
   * `CommandOutcome` JSON.
   */
  setDriverCommand(actorId: string, throttle?: number | undefined | null, brake?: number | undefined | null, steer?: number | undefined | null, handbrake?: boolean | undefined | null, clientId?: string | undefined | null, seq?: number | undefined | null): string
  /** Advance engine ticks; returns the `AdvanceResult` JSON. */
  advance(ticks: number): string
  snapshot(): WorldSnapshot
  subscribe(capacity?: number | undefined | null): TruthSubscription
  logJson(): string
  checkpoint(): Buffer
  restore(checkpoint: Buffer): void
}
export type JsWorldSession = WorldSession

/** Binding ABI version; the JS loader refuses any other value. */
export declare const ABI_VERSION: number

export declare function abiVersion(): number

export declare const ACTION_WIDTH: number

export declare function actionFields(): Array<string>

export declare const ACTOR_ROW: number

/** `AdaptNote[]` JSON (`{path, reason, severity, code?}`); needs no map. */
export declare function adaptTemplateNotesJson(templateJson: string): string

/** Ambient turn-feasibility verdicts held for `graph` (`simforge.ambient-turn-verdicts/v1`); persist beside the map closure. */
export declare function ambientTurnVerdictsJson(graph: LaneGraph): string

/** `SituationTransactionResult` JSON (no simulation). */
export declare function applySituationTransaction(documentJson: string, transactionJson: string): string

/** World-major flat results of one batch call; every array is an owned copy. */
export interface BatchResult {
  size: number
  tS: Float64Array
  reward: Float64Array
  terminated: Uint8Array
  truncated: Uint8Array
  /** `(N, STATE_VECTOR_SIZE)` row-major. */
  stateVector: Float64Array
  /** `(N, maxObjects, OBJECT_FEATURES)` row-major. */
  objects: Float32Array
  objectCount: Uint32Array
  /** `(N, 3)` row-major. */
  rewardTerms: Float64Array
  /** `(N, height, width, channels)` row-major when BEV is configured. */
  bev?: Float32Array
}

export interface BevShape {
  height: number
  width: number
  channels: number
}

/** Probe every transition of a map for every steered class and return the complete verdict table (with `closureDigest`); what a map publish ships. */
export declare function buildAmbientTurnVerdicts(bundle: MapBundle): string

export declare function canonicalJson(document: string): string

/** `sha256(templateId|paramsVersion|siteId|drawIndex)`, the per-cell seed. */
export declare function cellSeed(templateId: string, paramsVersion: string, siteId: string, drawIndex: number): string

/** The `t = 0` feasibility guards alone; returns the `SimIssue[]` JSON (no clip run). */
export declare function checkFeasibility(input: ScenarioInput, graph: LaneGraph): string

/** `SituationComparison` JSON. Options add `reactiveRoleIds?`. */
export declare function compareSituation(documentJson: string, transactionJson: string, bundle: MapBundle, optionsJson?: string | undefined | null, policy?: ((arg: string) => string | null) | undefined | null): string

/** Returns `[scenarioInput, boundSituationJson]`. */
export declare function compileSituation(documentJson: string, bundle: MapBundle, optionsJson?: string | undefined | null): [ScenarioInput, string]

/** `site = null` picks the top-ranked matched site; map-bound documents skip matching. */
export declare function compileTemplate(templateJson: string, bundle: MapBundle, site?: string | undefined | null, seed?: number | string | undefined | null, optionsJson?: string | undefined | null): CompileResult

/** Compile at a site already resolved by `findSite`, without re-matching. */
export declare function compileTemplateAtSite(templateJson: string, bundle: MapBundle, site: Site, seed?: number | string | undefined | null, optionsJson?: string | undefined | null): CompileResult

export declare function contentHash(document: string): string

export declare const DEFAULT_MAX_OBJECTS: number

export declare const ENGINE_HZ: number

/** Build provenance JSON (never a cache key). */
export declare function engineBuild(): string

/** Engine semantics version; `engineVersion()` is its former name. */
export declare function engineSemVer(): string

export declare function engineVersion(): string

/** The refinements every executor applies to the input it runs (stable high-speed world routes, cruise restoration). */
export declare function executionRefinements(input: ScenarioInput): ScenarioInput

/** Resolve one site: `siteId = null` picks the top-ranked site. */
export declare function findSite(templateJson: string, bundle: MapBundle, siteId?: string | undefined | null): Site

export declare function findSites(templateJson: string, bundle: MapBundle): Array<string>

/** Row width of `TrafficHandoff.step` actor inputs. */
export declare const HANDOFF_ACTOR_ROW: number

/** Row width of `TrafficHandoff.bodies()`. */
export declare const HANDOFF_BODY_ROW: number

/**
 * Lift a map-bound template to portable JSON. Refusals remain successful
 * values with structured diagnostics (`template: null`, `issues: [...]`).
 */
export declare function liftMapBoundTemplate(templateJson: string, bundle: MapBundle, optionsJson?: string | undefined | null): string

/** Load persisted ambient turn verdicts into this process; returns the count. Refuses another ENGINE_SEM_VER. */
export declare function loadAmbientTurnVerdicts(json: string): number

/** Ranked `SiteMatch` JSON (`{mapId, report: MatchReport, notes}`); `optionsJson = {minScore?, maxSites?, exactCatalogSiteResolution?}`. */
export declare function matchSites(templateJson: string, bundle: MapBundle, optionsJson?: string | undefined | null): string

/** Materialise an ambient-traffic profile onto `input` over `graph`; returns `[scenarioInput, provenanceJson]`. */
export declare function materializeAmbientTraffic(input: ScenarioInput, graph: LaneGraph, profileJson: string, optionsJson?: string | undefined | null): [ScenarioInput, string]

/**
 * The motion envelope the engine integrates for an actor class, as JSON:
 * `{accelMax, brakeComfort, brakeHard, lateralRateMax, lateralAccelMax, lateralJerkMax}`.
 */
export declare function motionLimitsJson(kind: string): string

export declare const OBJECT_FEATURES: number

export declare function parseMapSignalCatalog(xodr: string, geojsonJson: string): string

export interface PlacementRoute {
  lanes: Array<string>
  downstreamM: number
}

export interface PolicyStepResult {
  step: StepResult
  deadlineLimitMs?: number
  deadlineElapsedMs?: number
  deadlineMiss: boolean
  /** `policy | repeat-last | zero-control | scripted`. */
  applied: string
  executorJson?: string
}

/** `SituationRehearsal` JSON. `optionsJson = {materialize?, siteId?, geometryBindings?, runtime?}`. */
export declare function rehearseSituation(documentJson: string, bundle: MapBundle, optionsJson?: string | undefined | null, policy?: ((arg: string) => string | null) | undefined | null): string

export declare function replayWorldLog(logJson: string, input: ScenarioInput, graph: LaneGraph): string

/** Run a whole clip; returns the `SimResult` JSON document. */
export declare function runSimulation(input: ScenarioInput, graph: LaneGraph, optionsJson?: string | undefined | null): string

/** One blob (full form): bytes in memory, or a file whose sha256 is given. */
export interface ScenarioPackageBlob {
  data?: Uint8Array
  sha256?: string
  file?: string
}

export interface ScenarioPackageBlobOut {
  sha256: string
  data: Buffer
}

export interface ScenarioPackageContents {
  manifestJson: string
  receiptJson?: string
  /** `Verification` as JSON. */
  reportJson: string
  members: Array<ScenarioPackageMemberOut>
  blobs: Array<ScenarioPackageBlobOut>
}

/** Structure, manifest and version checks only (no member hashing). */
export declare function scenarioPackageInspect(bytes: Uint8Array, cliVersion?: string | undefined | null): string

/** One listed member: its path (`document.json`, `timeline/<sha>.json`, ...) and bytes. */
export interface ScenarioPackageMember {
  path: string
  data: Uint8Array
}

export interface ScenarioPackageMemberOut {
  path: string
  data: Buffer
}

/** Verify, then return every member and blob (each re-proven as it is read). */
export declare function scenarioPackageRead(bytes: Uint8Array, cliVersion?: string | undefined | null): ScenarioPackageContents

export interface ScenarioPackageReceipt {
  exportedAt: string
  exporterRelease: string
  textureTier?: string
}

/**
 * Fully verify a container (bytes, or a file path). Returns the
 * `Verification` report as JSON. `cliVersion` is the reading CLI's version
 * for the `producer.minCli` check; `null` when a producer re-checks its own
 * output (the report then says `cliCheck: "not-evaluated"`).
 */
export declare function scenarioPackageVerify(bytes?: Uint8Array | undefined | null, path?: string | undefined | null, cliVersion?: string | undefined | null): string

/**
 * Write a package. `manifestDraftJson` is the whole v1 manifest except
 * `members`, which the writer computes. With `outPath` the container is
 * written to that file (via a temporary sibling) instead of returned.
 */
export declare function scenarioPackageWrite(manifestDraftJson: string, members: Array<ScenarioPackageMember>, blobs: Array<ScenarioPackageBlob>, receipt?: ScenarioPackageReceipt | undefined | null, outPath?: string | undefined | null): ScenarioPackageWritten

export interface ScenarioPackageWritten {
  packageId: string
  form: string
  /** `manifest.json`: the exact canonical bytes whose sha256 is the package id. */
  manifestJson: string
  /** `WriteOutcome` as JSON (form, sizes, content report). */
  reportJson: string
  /** The container, when no `outPath` was given. */
  bytes?: Buffer
}

export declare function sha256Hex(data: Uint8Array): string

/** `SituationSolveResult` JSON; `onEvaluation` receives each `{program, rehearsal}` JSON. Options add `maxEvaluations?`, `relativeResolution?`. */
export declare function solveSituation(documentJson: string, bundle: MapBundle, optionsJson?: string | undefined | null, onEvaluation?: ((arg: string) => void) | undefined | null, policy?: ((arg: string) => string | null) | undefined | null): string

export declare const STATE_VECTOR_SIZE: number

/** One decision's result; every typed array is an owned copy. */
export interface StepResult {
  tS: number
  reward: number
  terminated: boolean
  truncated: boolean
  /** `Float64Array(STATE_VECTOR_SIZE)` (empty when disabled). */
  stateVector: Float64Array
  /** `Float32Array(maxObjects * OBJECT_FEATURES)` row-major, zero-padded. */
  objects: Float32Array
  objectCount: number
  objectIds: Array<string>
  /** `Float32Array(height * width * channels)` when BEV is configured. */
  bev?: Float32Array
  /** `[progress, proximity, comfort]`. */
  rewardTerms: Float64Array
  /** JSON `{events, minima, causal}`. */
  infoJson: string
}

/** The document's Studio content applied to a materialised input: paint tags on role actors, then baked parked cars. */
export declare function studioConcreteInput(input: ScenarioInput, templateJson: string): ScenarioInput

/** `{templateId, paramsVersion}`: the replay-key identity of a template. */
export declare function templateIdentityJson(templateJson: string): string

export interface WorldSnapshot {
  tS: number
  tick: number
  done: boolean
  actorIds: Array<string>
  kinds: Array<string>
  laneRsls: Array<string | undefined | null>
  present: Uint8Array
  /** `(N, 6)` rows `[x, z, headingRad, speedMps, s, longitudinalSpeedMps]` in the scene frame. */
  pose: Float64Array
}
